import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-used-book',
  templateUrl: './used-book.component.html',
  styleUrls: ['./used-book.component.css']
})
export class UsedBookComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }
  books: Array<any> =  [
   
    {
      "name":"Humsafar ",
      "author":"Ashutosh Singh ",
      "bookImage":"book112.webp",
      "bookPrize":"$ 799.00",
      "orginalBookPrize":"$ 892.00",
      "publisher":"Rigi Publication  ",
      "relesedDate":" 1 November 2019  ",
      "bookStockDetails":"Available",
      "aboutbook":"This story belongs to a person who was addicted of drugs because their friends were also addicted. Vikrant belongs to a rich family but his friends seduced him that they are his closed friend but they were about to robbery his property. His father was a businessman and loved his son and also he was proud of them that he will help to grow business but Vikrant could not understand the importance of time and everything has ruined but his lover Shweta helped him at last to learning them that don't make a friend like this who are addicted in drugs and about to robbery your property. So if you want make a friend in your life, please careful because not every friend is friends.",
      "aboutAuthor":"A writer by day and a reader by night, he is loathe to discuss himself in the third person, but can be persuaded to do so from time to time.A writer by day and a reader by night, he is loathe to discuss himself in the third person, but can be persuaded to do so from time to time.A writer by day and a reader by night, he is loathe to discuss himself in the third person, but can be persuaded to do so from time to time.A writer by day and a reader by night, he is loathe to discuss himself in the third person, but can be persuaded to do so from time to time.      ",
     
    },
    {
      "name":"The Monsoon Murders",
      "author":" Karan Parmanandka",
      "bookImage":"book100.webp",
      "bookPrize":"$ 1,054 ",
      "orginalBookPrize":"$ 1,121",
      "publisher":"Srishti Publishers And Distributors",
      "relesedDate":"01 Sep 2014   ",
      "bookStockDetails":"Available",
      "aboutbook":"Harry Potter is lucky to reach the age of thirteen, since he has survived the murderous attacks of the feared Dark Lord on more than one occasion. His hopes for a quiet school term concentrating on Quidditch are dashed, though, when a maniacal mass-murderer escapes from Azkaban, pursued by the soul-sucking Dementors who guard the prison. It’s assumed that Hogwarts is the safest place for Harry to be. But is it his imagination that is making him feel eyes watching him in the dark, and should he be taking Professor Trelawney’s ghoulish predictions seriously?These new editions of the classic and internationally bestselling, multi-award-winning series feature instantly pick-up-able new jackets by Jonny Duddle, with huge child appeal, to bring Harry Potter to the next generation of readers. It’s time to PASS THE MAGIC ON …",
      "aboutAuthor":"Joanne Rowling is an English writer. She achieved cult-status with seven Harry Potter books, The Tales of Beedle The Bard, Fantastic Beasts and Where To Find Them and Quidditch Through The Ages. She has also written two murder mystery novels under the pseudonym of Robert Galbraith.Jo completed her B.A. in French and Classics at the University of Exeter. She was awarded the title of Officer of the Most Excellent Order of the British Empire for her contributions to charity and literature. "
    
    },
    {
      "name":"Roses Are Blood Red",
      "author":"Novoneel Chakraborty",
      "bookImage":"book102.webp",
      "bookPrize":"$ 119.00",
      "orginalBookPrize":"$ 197.00",
      "publisher":" Penguin Random House India Pvt. Ltd ",
      "relesedDate":"   10 Dec 2019 ",
      "bookStockDetails":"Available",
      "aboutbook":"'I'll gift you a love story that every girl desires, but few get to live.He'd told me once. And boy, did he stick to his words! Vanav Thakur is the perfect boyfriend that any girl can have. He ticks every box you can ever have for your Mr Right. Trust me on this. He cares for me, respects me, never objectifies me, never says no to me for anything, understands me, is progressive and has no shadow of any male chauvinism in him. Sometimes, I wonder if I really deserve him. My parents, like me, had no option but to accept him as my boyfriend. Everything was hunky dory and I thought I would be that one girl who would never have any relationship hiccup until I stumbled upon the reason behind his perfection.Is love capable of healing the deep wounds which love itself creates within you? Mysteriously thrilling in its essence, Roses Are Blood Red is the haunting story of a passion and eternal love. ",
      "aboutAuthor":"Novoneel Chakraborty is the bestselling author of fourteen bestselling thriller novels and one short story collection titled Cheaters. His novel, Forget Me Not, Stranger, debuted as the No. 1 bestseller across India. While All Yours, Stranger ranked in the top five thriller novels on Amazon, India-the only one to feature amid other international bestsellers. His novel Black Suits You was in top five thrillers category on Amazon for fifteen weeks. While his Forever series was in the bestseller list for ten weeks straight after its release with Forever Is a Lie featuring in the highest selling books on Flipkart for 2017. Forever Is True made it to Amazon's Memorable Books of 2017 and Times of India's Most Stunning Books of 2017.",
    },
    {
      "name":"One Arranged Murder",
      "author":"Chetan Bhagat",
      "bookImage":"book101.webp",
      "bookPrize":"$ 135.00",
      "orginalBookPrize":"$ 250.00",
      "publisher":" Westland ",
      "relesedDate":" 28 September 2020  ",
      "bookStockDetails":"Available",
      "aboutbook":"Saurabh Maheshwari is engaged to Prerna Malhotra. His wedding is three months away. On the night of Karva Chauth, however, Prerna is murdered after being pushed from her terrace. With Inspector Vijender Singh and aided by ACP Rana, the case is investigated by Saurabh and Keshav Rajpurohit. They interrogate all the people in the family. Prerna has a cousin sister called Anjali, and Keshav falls in love with her. Anjali is revealed to be the killer and is arrested..One Arranged Murder is the ninth novel and the twelfth book overall written by the Indian author Chetan Bhagat. The novel is the sequel to Bhagat's 2018 novel The Girl in Room 105. A sequel to the book named 400 Days was released in 2021",
      "aboutAuthor":"Chetan Bhagat is the author of nine blockbuster books. These include seven novels—Five Point Someone (2004), One Night @ the Call Center (2005), The 3 Mistakes of My Life (2008), 2 States (2009), Revolution 2020 (2011), Half Girlfriend (2014) and One Indian Girl (2016) and two non-fiction titles— What Young India Wants (2012) and Making India Awesome(2015). His upcoming book 400 Days is now available to preorder and will release on 17th September 2021. Chetan’s books have remained bestsellers since their release. Four out his five novels have been already adapted into successful Bollywood films and the others are in process of being adapted as well. The New York Times called him the ‘the biggest selling English language novelist in India’s history’. Time magazine named him amongst the ‘100 most influential people in the world’ and Fast Company, USA, listed him as one of the world’s ‘100 most creative people in business’. Chetan writes columns for leading English and Hindi newspapers, focusing on youth and national development issues. He is also a motivational speaker and screenplay writer. Chetan quit his international investment banking career in 2009 to devote his entire time to writing and make change happen in the country. He lives in Mumbai with his wife, Anusha, an ex-classmate from IIM-A, and his twin boys.",
    },
    {
      "name":"7 Days",
      "author":" Stanish Gill",
      "bookImage":"book103.webp",
      "bookPrize":"$ 99.00",
      "orginalBookPrize":"$ 125.00",
      "publisher":" Frog in Well ",
      "relesedDate":" 7 October 2016  ",
      "bookStockDetails":"Available",
      "aboutbook":"All that Apurva wanted was to live a happily married life with the woman he loved the most, but what he didn't expect to face was a drastic and dangerous challenge on the ﬁrst night of his honeymoon. He woke up the ﬁrst morning and discovered his wife to be affected by something he didn't have any clue about. He was faced with two options, either leave her and save himself or stay and ﬁnd a solution. What will Apurva choose to do? Will he be successful in his decision? 7 days is a romantic, psychological thriller with paranormal element in it.",
      "aboutAuthor":"Stanish Gill is a young writer associated with Film Writer Association as an Associate Writer. Apart from writing fictional novels, he also writes Hindi songs. Some of his work has been published in newspapers and on the Film Writer Association portal. He is an Educationist by profession and lives along with his wife and two sons in Mumbai.",
    },
    {
      "name":"Without Merit",
      "author":"Colleen Hoover",
      "bookImage":"book104.webp",
      "bookPrize":"$ 329.00 ",
      "orginalBookPrize":"$ 599.00",
      "publisher":" Atria Books ",
      "relesedDate":" 03 Oct 2017  ",
      "bookStockDetails":"Available",
      "aboutbook":"Not every mistake deserves a consequence. Sometimes the only thing it deserves is forgiveness.The Voss family is anything but normal. They live in a repurposed church, newly baptized Dollar Voss. The once cancer-stricken mother lives in the basement, the father is married to the mother's former nurse, the little half-brother isn't allowed to do or eat anything fun, and the eldest siblings are irritatingly perfect. Then, there's Merit.Merit Voss collects trophies she hasn't earned and secrets her family forces her to keep. While browsing the local antiques shop for her next trophy, she finds Sagan. His wit and unapologetic idealism disarm and spark renewed life into her--until she discovers that he's completely unavailable. Merit retreats deeper into herself, watching her family from the sidelines, when she learns a secret that no trophy in the world can fix.Fed up with the lies, Merit decides to shatter the happy family illusion that she's never been a part of before leaving them behind for good. When her escape plan fails, Merit is forced to deal with the staggering consequences of telling the truth and losing the one boy she loves.",
      "aboutAuthor":"Colleen Hoover is the #1 New York Times bestselling author of more than twenty-three novels, including It Ends with Us, All Your Perfects, Ugly Love, and Verity. In 2015, Colleen and her family founded a nonprofit called The Bookworm Box, a bookstore and monthly book subscription service. Colleen lives in Texas with her husband and their three boys.",
    },
    {
      "name":"Lost Symbol",
      "author":"Dan Brown",
      "bookImage":"book105.webp",
      "bookPrize":"$ 359.00",
      "orginalBookPrize":"$ 478.00 ",
      "publisher":"  Transworld Publishers Ltd ",
      "relesedDate":"   22 Jul 2010 ",
      "bookStockDetails":"Available",
      "aboutbook":"WHAT WAS LOST WILL BE FOUND...Washington DC: Harvard symbologist Robert Langdon is summoned at the last minute to deliver an evening lecture in the Capitol Building. Within moments of his arrival, however, a disturbing object - gruesomely encoded with five symbols - is discovered at the epicentre of the Rotunda. It is, he recognises, an ancient invitation, meant to beckon its recipient towards a long-lost world of hidden esoteric wisdom. When Langdon's revered mentor, Peter Solomon - philanthropist and prominent mason - is brutally kidnapped, Langdon realizes that his only hope of saving his friend's life is to accept this mysterious summons and follow wherever it leads him. Langdon finds himself quickly swept behind the facade of America's most historic city into the unseen chambers, temples and tunnels which exist there. All that was familiar is transformed into a shadowy, clandestine world of an artfully concealed past in which Masonic secrets and never-before-seen revelations seem to be leading him to a single impossible and inconceivable truth. A brilliantly composed tapestry of veiled histories, arcane icons and enigmatic codes, The Lost Symbol is an intelligent, lightning-paced thriller that offers surprises at every turn. For, as Robert Langdon will discover, there is nothing more extraordinary or shocking than the secret which hides in plain sight...  ",
      "aboutAuthor":"Daniel Gerhard Brown is an American author best known for his thriller novels, including the Robert Langdon novels Angels & Demons, The Da Vinci Code, The Lost Symbol, Inferno, and Origin. His novels are treasure hunts which usually take place over a period of 24 hours.Daniel Gerhard Brown (born June 22, 1964) is an American author best known for his thriller novels, including the Robert Langdon novels Angels & Demons (2000), The Da Vinci Code (2003), The Lost Symbol (2009), Inferno (2013), and Origin (2017). His novels are treasure hunts which usually take place over a period of 24 hours.[3] They feature recurring themes of cryptography, art, and conspiracy theories. His books have been translated into 57 languages and, as of 2012, have sold over 200 million copies. Three of them, Angels & Demons, The Da Vinci Code, and Inferno, have been adapted into films, while one of them, The Lost Symbol, was adapted into a television show. ",
    },
    {
      "name":"Over My Dead Body",
      "author":"Archer, Jeffrey ",
      "bookImage":"book106.webp",
      "bookPrize":"$ 332.00",
      "orginalBookPrize":"$ 429.00",
      "publisher":"HarperCollins  ",
      "relesedDate":" 12 Oct 2021  ",
      "bookStockDetails":"Available",
      "aboutbook":"An unputdownable story of murder, revenge and betrayal from international number one bestseller Jeffrey Archer.In London, the Metropolitan Police set up a new Unsolved Murders Unit—a cold case squad—to catch the criminals nobody else can. In Geneva, millionaire art collector Miles Faulkner—convicted of forgery and theft—was pronounced dead two months ago. So why is his unscrupulous lawyer still representing a dead client? And at the heart of all three investigations are Detective Chief Inspector William Warwick, rising star of the department, and ex-undercover agent Ross Hogan, brought in from the cold.",
      "aboutAuthor":"Jeffrey Howard Archer, Baron Archer of Weston-super-Mare (born 15 April 1940) is an English author and former politician.He was a Member of Parliament and deputy chairman of the Conservative Party, and became a life peer in 1992. His political career, having suffered several controversies, ended after a conviction for perverting the course of justice and his subsequent imprisonment. He is married to Mary Archer, a scientist specialising in solar power. Outside politics, he is a novelist, playwright and short story writer.",
    },
    {
      "name":"My Imperfect Dream",
      "author":"Vaibhav Thakur",
      "bookImage":"book107.webp",
      "bookPrize":"$ 1,038.0",
      "orginalBookPrize":"$ 1342.0",
      "publisher":"  Zorba Books ",
      "relesedDate":" 29 May 2018  ",
      "bookStockDetails":"Available",
      "aboutbook":"Armaan has left his hometown Manali in order to prepare for the Pre-Medical Entrance Test (PMT) in Chandigarh. Little does he know that he would be forging an ever-lasting friendship with a pair of guys there who are also preparing for the PMT-Rajat and Vikas. All three of them have their lives running smoothly till one day Armaan discloses his past. Caught between the struggles of cracking the medical entrance exam and dealing with a mysterious and heart-breaking past that seems to be on the brink of jeopardising his future, Armaan is torn between different directions! As the days pass, his desire to resist the temptations of his past becomes uncontrollable. But he can barely fathom the consequences his impetuous yearning for his past may bring! What is his mysterious past? Will he be able to overcome it? What will happen when his past endangers his present? What if a sudden encounter with someone changes his life forever? Will he crack the entrance test? Will he be able to fulfil his dream to become a doctor? MY IMPERFECT DREAM is the bitter-sweet story of campus relationships, of overbearing studies and overwhelming love and a dearly loved dream that is just short of attaining perfection!",
      "aboutAuthor":"Experienced Co-Founder with a demonstrated history of working in the computer software industry. Skilled in Team Building, Mentoring, Trading, and Marketing. Strong business development professional graduated from Guru Gobind Singh Indraprastha University. ",
    },
    {
      "name":"That Man in the Mirror",
      "author":"Rajeev Ranjan ",
      "bookImage":"book108.webp",
      "bookPrize":"$ 151.00",
      "orginalBookPrize":"$ 189.00",
      "publisher":"LiFi Publications Private Limited  ",
      "relesedDate":"  1 January 2015 ",
      "bookStockDetails":"Available",
      "aboutbook":"How far one should go to help his sibling. Can we draw a line in blood relationships?What happens. when we stop counting our blessings and long for fictitious pleasures, when lust takes over gentle senile notions of love and when you lie to yourself and then justify it?Is there any date sheet for emotions?This novel tries answering these questions through a beautiful story. Besides it also touches the emotions that cross our heart when we embark on the journey of betrayal. It is also an attempt to locate that man in the mirror that we generally choose to ignore. ",
      "aboutAuthor":"Rajeev Ranjan graduated in physics from University of Delhi in the year 1996. He works for Government of India in senior executive position. A voracious reader and writer, Rajeev has written two more bestselling novels.",
    },
    {
      "name":"400 Days ",
      "author":" Bhagat, Chetan",
      "bookImage":"book109.webp",
      "bookPrize":"$ 150.00",
      "orginalBookPrize":"$ 277.00",
      "publisher":"HarperCollins India  ",
      "relesedDate":" 20 Jul 2022  ",
      "bookStockDetails":"Available",
      "aboutbook":"400 Days is the tenth novel and the thirteenth book overall written by the Indian author Chetan Bhagat. It is the third installment of the author's popular Keshav-Saurabh mystery series after The Girl in Room 105 and One Arranged Murder.After the incidents of One Arranged Murder, Keshav and Saurabh are living with Keshav's parents in their new apartment in a gated community called Icon. Keshav has quit his job at Cybersafe and prepares for IPS while Saurabh continues to work and is determined to get fit as he is upset with his physical appearance. One day Keshav is called by his parents to meet a woman known as Alia Arora, whom they hope to be a suitable bride for him. They are astonished to see that she also brought her child, Suhana. She is a neighbor living in the adjacent building and asks for his help to find her missing daughter Siya, who had disappeared 9 months ago. Though reluctant at first, Keshav is encouraged by his parents to take up the case as Alia had promised huge payments irrespective of the result. Keshav agrees and begins his investigations.",
      "aboutAuthor":"Chetan Bhagat is the author of seven novels and two nonfiction books. The New York Times called him the “the biggest selling English language novelist in India’s history” and Time magazine named him among the “100 most influential people in the world.” Chetan also writes about youth and national development issues in India. He lives in Mumbai with his wife and their twin boys.      ",
    },
    {
      "name":"The Secret of the Druids",
      "author":"Christopher C Doyle ",
      "bookImage":"book110.webp",
      "bookPrize":"$ 1,113.0",
      "orginalBookPrize":"$ 1,289.0",
      "publisher":" Brilliance Audio ",
      "relesedDate":" 06 Oct 2020  ",
      "bookStockDetails":"Available",
      "aboutbook":"Julius Caesar invades Britain twice...only to leave empty handed.The Romans single-mindedly target the extermination of the Druids and the destruction of their sacred sites. What fear drives them to do so?Who were the Druids? Were they priests or astronomers? Scientists or sorcerers? What is the ancient and terrifying secret from the Mahabharata that links the megalithic sites of Britain to the Druids, Julius Caesar and a mysterious queen who lived 4,000 years ago? These are the riddles that Vijay Singh and the task force must answer if they are to save the world from a fate worse than death. But time is running out....5 B.C. and 54 B.C. - Julius Caesar invades Britain twice, only to leave empty handed... A.D. 60 - The Romans single-mindedly target the extermination of the Druids and the destruction of their sacred sites. What fear drives them to do so?... Present day - Who were the Druids? Were they priests or astronomers? ",
      "aboutAuthor":"Christopher C. Doyle is an author who transports the reader into a fascinating world where ancient secrets buried in legends blend with science and history to create a gripping story.Brought up as a boy on a steady diet of books ranging from classical literature to science fiction and fantasy, Christopher has been writing since his schooldays. Since childhood, his literary mentors have been Jules Verne, H G Wells, Isaac Asimov and Robert Heinlein, JRR Tolkein, Robert Jordan and Terry Brooks.Along the way to publishing his debut novel, The Mahabharata Secret, Christopher pursued a career in the corporate world after graduating from St. Stephens College, Delhi with a degree in Economics and studying business management at IIM Calcutta. Over the course of his corporate career, he has worked with leading multinational organizations as a senior executive and CEO before setting up a strategic consultancy in India in partnership with a US based consulting firm.",
    },
    {
      "name":"Leopard",
      "author":"Nesbo Jo",
      "bookImage":"book111.webp",
      "bookPrize":"$ 757.00",
      "orginalBookPrize":"$ 876.00",
      "publisher":" Vintage Publishing ",
      "relesedDate":"  01 Jul 2011 ",
      "bookStockDetails":"Available",
      "aboutbook":"In the depths of winter, two young women are found dead, both drowned in their own blood. Inspector Harry Hole, deeply traumatized by an investigation that threatened the lives of those he holds most dear, initially wants nothing to do with the case but his instincts take over when a prominent MP is found brutally murdered. The victims appear completely unconnected to one another, but it's not long before Harry makes a discovery: the women all spent the night in the same isolated mountain hostel. And someone is picking off the guests, one by one... ",
      "aboutAuthor":"",
    },
    {
      "name":"Angels And Demons",
      "author":"Dan Brown ",
      "bookImage":"book113.webp",
      "bookPrize":"$ 359.00",
      "orginalBookPrize":"$ 499.00",
      "publisher":" Transworld Publishers Ltd ",
      "relesedDate":"  28 Aug 2009 ",
      "bookStockDetails":"Available",
      "aboutbook":"CERN Institute, Switzerland: a world-renowned scientist is found brutally murdered with a mysterious symbol seared onto his chest. nnThe Vatican, Rome: the College of Cardinals assembles to elect a new pope. Somewhere beneath them, an unstoppable bomb of terrifying power relentlessly counts down to oblivion. nnIn a breathtaking race against time, Harvard professor Robert Langdon must decipher a labyrinthine trail of ancient symbols if he is to defeat those responsible – the Illuminati, a secret brotherhood presumed extinct for nearly four hundred years, reborn to continue their deadly vendetta against their most hated enemy, the Catholic Church.",
      "aboutAuthor":"Dan Brown is the bestselling author of Digital Fortress, Deception Point, Angels and Demons, The Da Vinci Code and The Lost Symbol. He is a graduate of Amherst College and Phillips Exeter Academy, where he has taught English and creative writing. He lives in New England.",

    },
    {
      "name":"Love Story ",
      "author":"Erich Segal",
      "bookImage":"book114.webp",
      "bookPrize":"$107.00 ",
      "orginalBookPrize":"$ 117.00",
      "publisher":" Harper & Row (USA)",
      "relesedDate":" 14 February 1970   ",
      "bookStockDetails":"Available",
      "aboutbook":"Love Story is a 1970 novel by American writer Erich Segal. Segal wrote a screenplay that was subsequently approved for production by Paramount Pictures. Paramount requested that Segal adapt the story into a novel as part of the film's marketing campaign",
      "aboutAuthor":"Erich Segal (June 16, 1937 – January 17, 2010) was an American author, screenwriter, and Classics Professor. He was best known for writing the phenomenally successful novel Love Story (1970), and the hit major motion picture of the same name.When Erich was at Midwood High School, he had a serious canoeing accident and as part of his rehabilitation, the high school coach recommended that he jog. This became a lifelong passion and he competed in the Boston Marathon more than twelve times, breaking 3 hours. This led to him being a commentator for the marathon at the 1972 ABC Olympics and at Montreal in 1976.      ",
    },
    {
      "name":"A COUNTRY CALLED CHILDHOOD",
      "author":"Deepti Naval",
      "bookImage":"book123.jpg",
      "bookPrize":"$ 679.00",
      "orginalBookPrize":"$ 976.00",
      "publisher":" Rupa & Co ",
      "relesedDate":"	2 July 2022    ",
      "bookStockDetails":"Available",
      "aboutbook":"A Country Called Childhood is a beautifully told memoir of growing up in Amritsar in the tumultuous 1950s and 60s by award-winning actress Deepti Naval. In extremely visual and evocative prose, Naval describes an unforgettable childhood filled with love, adventure, mystery, tragedy, and joy. She uncovers, in great detail, life in an unconventional Punjabi family while plunging the reader into the distinctive sights, smells, and sounds of a fast-vanishing India. Starting at the moment of her birth on a rainy night, she tracks her journey to adulthood, a path punctuated by many personal turning points as also momentous events of national importance, such as the Sino-Indian War of 1962 and the Indo-Pak War of 1965.Moving and illuminating, A Country Called Childhood shows how Naval’s early love affair with cinema and the experiences of her childhood shaped her career as one of the country’s most admired actors.",
      "aboutAuthor":"Deepti Naval is an Indian actress, director, and writer, predominantly active in Hindi cinema. Her major contribution has been in the area of art cinema, winning critical acclaim for her sensitive and 'close to life' characters that emphasized the changing roles of women in India. ",
    },
    {
      "name":"The Psychology of Money",
      "author":"Morgan Housel ",
      "bookImage":"book130.jpg",
      "bookPrize":"$ 296.00",
      "orginalBookPrize":"$ 398.00",
      "publisher":" Jaico Publishing House ",
      "relesedDate":" 01 Sep 2020 ",
      "bookStockDetails":"Available",
      "aboutbook":"Timeless lessons on wealth, greed, and happiness doing well with money isn?t necessarily about what you know. It?s about how you behave. And behavior is hard to teach, even to really smart people. How ...Doing well with money isn't necessarily about what you know. It's about how you behave. And behavior is hard to teach, even to really smart people",
      "aboutAuthor":"Morgan Housel is a partner at Collaborative Fund and author of the book The Psychology of Money.Doing well with money isn't necessarily about what you know. It's about how you behave. And behavior is hard to teach, even to really smart people",
    },
    {
      "name":"How to Win Friends and Influence People",
      "author":"Dale Carnegie",
      "bookImage":"book212.jpg",
      "bookPrize":"$ 88.00",
      "orginalBookPrize":"$ 23.00",
      "publisher":"  Srishti Publishers & Distributors",
      "relesedDate":" 12 October 2020 ",
      "bookStockDetails":"Available",
      "aboutbook":"Do you feel stuck in life, not knowing how to make it more successful? Do you wish to become more popular? Are you craving to earn more? Do you wish to expand your horizon, earn new clients and win people over with your ideas? How to Win Friends and Influence People is a well-researched and comprehensive guide that will help you through these everyday problems and make success look easier. You can learn to expand your social circle, polish your skill set, find ways to put forward your thoughts more clearly, and build mental strength to counter all hurdles that you may come across on the path to success. Having helped millions of readers from the world over achieve their goals, the clearly listed techniques and principles will be the answers to all your questions. ",
      "aboutAuthor":"Dale Carnegie has authored close to eleven books and multiple articles on solving everyday problems and achieving success, his books have helped millions of people feel better prepared for life.",
    },
]

}
