import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-main',
  templateUrl: './main.component.html',
  styleUrls: ['./main.component.css']
})
export class MainComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }
  newArrivals: Array<any> = [
    {
      "name":"The Challenge",
      "author":"Danielle Steel",
      "bookImage":"book1.webp",
      "bookPrize":"$ 345.72",
      "orginalBookPrize":"$ 392.77",
      "publisher":"Delacorte Press",
      "relesedDate":"16 August 2022",
      "bookStockDetails":"Available",
      "aboutbook":" In this thrilling novel from #1 New York Times bestselling author Danielle Steel, a small community is tested when their children go missing while exploring a dangerous local peak, forcing them to band together during the crisis. Fishtail, Montana, is home to Anne and Pitt Pollock, local royalty, high school sweethearts, and owners of the successful Pollock ranch. The sprawling foothills of the Beartooth Mountains surround the town, overlooking the Pollocks’ property and the nearby ranch belonging to Bill and Pattie Brown. The two couples have known each other since childhood.Their sons Peter Pollock and Matt Brown are also the best of friends. When they and two other local kids meet Juliet Marshall, new to town after her parents’ bitter divorce, the five of them are soon inseparable, spending their summer days swimming, horseback riding, hiking, and fishing.But one August afternoon, their latest adventure takes a dangerous turn—and quickly escalates into a battle for survival—when they find themselves trapped on Granite Peak. Fear reverberates through the town as their parents grow ever more desperate to hear word that their children have been found. They must place their own trials aside amid a massive search-and-rescue operation. As they come to lean on one another for support, a media frenzy ensues, heightening tensions and testing some already fragile relationships.In the aftermath of this one fateful event, devastating secrets are revealed, new love appears on the horizon, and families are forced to reconsider what they once held dear. In The Challenge, Danielle Steel deftly weaves a story that is a portrait of courage and a striking tale of the bonds of love and family. ",
      "aboutAuthor":" Danielle Steel has been hailed as one of the world’s bestselling authors, with almost a billion copies of her novels sold. Her many international bestsellers include All That Glitters, Royal, Daddy’s Girls, The Wedding Dress, The Numbers Game, Moral Compass, Spy, and other highly acclaimed novels. She is also the author of His Bright Light, the story of her son Nick Traina’s life and death; A Gift of Hope, a memoir of her work with the homeless; Expect a Miracle, a book of her favorite quotations for inspiration and comfort; Pure Joy, about the dogs she and her family have loved; and the children’s books Pretty Minnie in Paris and Pretty Minnie in Hollywood. "
    },
    {
      "name":"Dharma",
      "author":"Amish and Bhavna Dive",
      "bookImage":"book3.jpg",
      "bookPrize":"$ 359.72",
      "orginalBookPrize":"$ 499.00",
      "publisher":" Westland ",
      "relesedDate":" 28 December 2020",
      "bookStockDetails":"Out Of Stock",
      "aboutbook":" The spiritual self-help book is co-authored by Amish and his sister Bhavna Roy. In 'Dharma: Decoding the Epics for a Meaningful Life', as the title suggests, Amish and Bhavna Roy discuss the intriguing concepts of Dharma, Karma, the meaning of life and how it can help one achieve the most in life.Stories can be both entertaining and educative. They can also be insightful and illuminating, especially when they have travelled down the generations, through the centuries, taking on and eliding new meanings with each retelling. In this genre-bending book, the first of a series, Amish and Bhavna dive into the priceless treasure trove of the ancient Indian epics, as well as the vast and complex universe of Amish’s Meluha (through his Shiva Trilogy and Ram Chandra Series), to explore some of the key concepts of Indian philosophy. ",
      "aboutAuthor":" AMISH is a 1974-born IIM (Kolkata)-educated, boring banker turned happy author. The success of his debut book, The Immortals of Meluha (Book 1 of the Shiva Trilogy), encouraged him to give up a fourteen-year-old career in financial services to focus on writing. He is passionate about history, mythology and philosophy, finding beauty and meaning in all world religions. Amish's books have sold more than 5.5 million copies and have been translated into over 19 languages. BHAVNA ROY was educated in Mussoorie, Pune and Mumbai. After graduating in psychology from Mumbai University, she worked first as a volunteer in a school for special children in Malegaon, and later in an NGO in Nashik called SOS. She is the wife of the late Himanshu Roy IPS, senior police officer of the Maharashtra cadre. She lives in Mumbai."
  },
  {
    "name":" The Alchemist",
    "author":"Paulo Coelho ",
    "bookImage":"book7.webp",
  
    "bookPrize":"$ 140.07",
    "orginalBookPrize":"$ 249.12",
    "publisher":"HarperTorch (English translation) ",
    "relesedDate":"1988  ",
    "bookStockDetails":"Available",
    "aboutbook": " Combining magic, mysticism, wisdom, and wonder into an inspiring tale of self-discovery, The Alchemist has become a modern classic, selling millions of copies around the world and transforming the lives of countless readers across generations.Paulo Coelho's masterpiece tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest will lead him to riches far different—and far more satisfying—than he ever imagined. Santiago's journey teaches us about the essential wisdom of listening to our hearts, recognizing opportunity and learning to read the omens strewn along life's path, and, most importantly, following our dreams." ,
    "aboutAuthor":" The Brazilian author PAULO COELHO was born in 1947 in the city of Rio de Janeiro. Before dedicating his life completely to literature, he worked as theatre director and actor, lyricist and journalist.The Alchemist is a novel by Brazilian author Paulo Coelho which was first published in 1988. Originally written in Portuguese, it became a widely translated international bestseller  "

  },
  {
    "name":"RAM Scion of Ikshvaku",
    "author":" Amish Tripathi",
    "bookImage":"book4.jpg",
    "bookPrize":"$ 201",
    "orginalBookPrize":"$388.00",
    "publisher":"Westland Press ",
    "relesedDate":" 22 June 2015",
    "bookStockDetails":"Available",
    "aboutbook":"Scion of Ikshvaku (also known as Ram: Scion of Ikshvaku) is a one to one replica of the events taking place before the epic tale 'Ramayana' and also the fourth book of Amish Tripathi, fourth book of Amishverse, and first book of Ram Chandra Series. It was released on 22 June 2015. It is based on Ram, the legendary Indian king regarded as an incarnation of Vishnu. The title was revealed by the author at the Jaipur Literature Festival. The story begins with King Dashrath of Ayodhya being defeated in a war by Lankan trader Raavan, and the birth of his son Ram. It follows through Ram's childhood and tutelage, along with the politics surrounding his ascension to the throne, and ultimately his 14-year exile, accompanied by wife Sita and brother Lakshman. ",
    "aboutAuthor":"Amish is a 1974-born, IIM (Kolkata)-educated banker-turned-author. The success of his debut book, The Immortals of Meluha (Book 1 of the Shiva Trilogy), encouraged him to give up his career in financial services to focus on writing. Besides being an author, he is also an Indian-government diplomat, a host for TV documentaries, and a film producer. Amish is passionate about history, mythology and philosophy, finding beauty and meaning in all world religions. His books have sold more than 6 million copies and have been translated into over 20 languages. His Shiva Trilogy is the fastest selling and his Ram Chandra Series the second fastest selling book series in Indian publishing history   "

  },
  {
    "name":"A Court of Thorns and Roses",
    "author":"Sarah J. Maas",
    "bookImage":"book8.jpg", 
    "bookPrize":"$ 386",
    "orginalBookPrize":"$ 417.02",
    "publisher":"Bloomsbury Publishing ",
    "relesedDate":" 5 May 2015 ",
    "bookStockDetails":"Available",
    "aboutbook":"Feyre's survival rests upon her ability to hunt and kill – the forest where she lives is a cold, bleak place in the long winter months. So when she spots a deer in the forest being pursued by a wolf, she cannot resist fighting it for the flesh. But to do so, she must kill the predator and killing something so precious comes at a price..Dragged to a magical kingdom for the murder of a faerie, Feyre discovers that her captor, his face obscured by a jewelled mask, is hiding far more than his piercing green eyes would suggest. Feyre's presence at the court is closely guarded, and as she begins to learn why, her feelings for him turn from hostility to passion and the faerie lands become an even more dangerous place. Feyre must fight to break an ancient curse, or she will lose him forever. ",
    "aboutAuthor":"Sarah J. Maas is the #1 New York Times and internationally bestselling author of the Crescent City, A Court of Thorns and Roses, and the Throne of Glass series. Her books have sold more than twelve million copies and are published in thirty-seven languages.Sarah Janet Maas is an American fantasy author known for her fantasy series Throne of Glass and A Court of Thorns and Roses. As of 2021, she has sold over twelve million copies of her books and her work has been translated into 37 languages "

  },
  {
    "name":"Fairy Tale",
    "author":" Stephen King",
    "bookImage":"book11.jpg",
   
    "bookPrize":"$ 387.00",
    "orginalBookPrize":"$ 402.03",
    "publisher":" Scribner ",
    "relesedDate":" 6 September 2022",
    "bookStockDetails":"Available",
    "aboutbook": "Fairy Tale is a dark fantasy novel by American author Stephen King, published on September 6, 2022 by Scribner. The novel follows Charlie Reade, a 17-year-old who inherits keys to a hidden, otherworldly realm, and finds himself leading the battle between forces of good and evil.Legendary storyteller Stephen King goes deep into the well of his imagination in this spellbinding novel about a seventeen-year-old boy who inherits the keys to a parallel world where good and evil are at war, and the stakes could not be higher—for their world or ours.A story as old as myth, and as startling and iconic as the rest of King’s work, Fairy Tale is about an ordinary guy forced into the hero’s role by circumstance, and it is both spectacularly suspenseful and satisfying.  ",
    "aboutAuthor":"Stephen Edwin King (born September 21, 1947) is an American author of horror, supernatural fiction, suspense, crime, science-fiction, and fantasy novels. Described as the King of Horror, a play on his surname and a reference to his high standing in pop culture,[2] his books have sold more than 350 million copies,[3] and many have been adapted into films, television series, miniseries, and comic books. King has published 64 novels, including seven under the pen name Richard Bachman, and five non-fiction books.[4] He has also written approximately 200 short stories, most of which have been published in book collections" 

  },

]
favorite: Array<any> = [
  
    {
      "name":"Looking for Alaska",
      "author":"Jhon Green",
      "bookImage":"book40.jpg",
      "bookPrize":"$ 669.00",
      "orginalBookPrize":"$ 917.00",
      "publisher":"  Harper Collins India Ltd  ",
      "relesedDate":" 28 Feb 2013  ",
      "bookStockDetails":"Available",
      "aboutbook":"“If people were rain, I was drizzle and she was a hurricane.Gorgeous, clever and undoubtedly screwed-up, Alaska draws Miles into her reckless world and irrevocably steals his heart. For Miles, nothing can ever be the same again.‘Looking for Alaska’ brilliantly captures the exquisite painful joy of living and loving. Poignant, funny, heartbreaking and compelling, this novel will stay with you forever.The unmissable first novel from bestselling and award-winning author of THE FAULT IN OUR STARS and TURTLES ALL THE WAY DOWN.",
      "aboutAuthor":"John Green is an award-winning, New York Times bestselling author who has received numerous accolades including the Printz Medal, a Printz Honor and the Edgar Award. John is also one half of the Vlogbrothers; co-creator, with his brother, Hank, of the popular video blog Brotherhood 2.0, which has been watched more than 30 million times by Nerdfighter fans all over the globe (youtube.com/vlogbrothers).",
    },
    {
      "name":"Long Winter",
      "author":"Laura Ingalls Wilder ",
      "bookImage":"book39.jpg",
      "bookPrize":"$ 339.00",
      "orginalBookPrize":"$ 513.00",
      "publisher":" Egmont UK Ltd ",
      "relesedDate":"  30 Jul 2015 ",
      "bookStockDetails":"Available",
      "aboutbook":"When a blizzard cuts the town of De Smet off from the railroad, the community is left for weeks without food or fuel deliveries and the Ingalls family are forced to eke out the last of their supplies. As the terrible winter drags on, things begin to look desperate, until Almanzo Wilder and his friend brave the icy storms in search of help.The Long Winter is an autobiographical children's novel written by Laura Ingalls Wilder and published in 1940, the sixth of nine books in her Little House series. It is set in southeastern Dakota Territory during the severe winter of 1880–1881, when she turned 14 years old.On the empty winter prairie, gray clouds to the northwest meant only one thing: a blizzard was seconds away. The first blizzard came in October. It snowed almost without stopping until April. The temperature dropped to forty below. Snow reached the roof-tops. And no trains could get through with food and coal. The townspeople began to starve. The Ingalls family barely lived through that winter. And Almanzo Wilder knew he would have to risk his life to save the town.",
      "aboutAuthor":"Laura Elizabeth Ingalls Wilder was an American writer, mostly known for the Little House on the Prairie series of children's books, published between 1932 and 1943, which were based on her childhood in a settler and pioneer family.Ingalls wrote a series of historical fiction books for children based on her childhood growing up in a pioneer family. She also wrote a regular newspaper column and kept a diary as an adult moving from South Dakota to Missouri, the latter of which has been published as a book.",
    },
    {
      "name":"Sooley",
      "author":"John Grisham",
      "bookImage":"book38.webp",
      "bookPrize":"$ 477.00",
      "orginalBookPrize":"$ 698.00",
      "publisher":" Doubleday Books  ",
      "relesedDate":" 27 April 2021  ",
      "bookStockDetails":"Available",
      "aboutbook":"New York Times bestselling author John Grisham takes you to a different kind of court in his first basketball novel. Samuel 'Sooley' Sooleymon is a raw, young talent with big hoop dreams...and even bigger challenges off the court.In the summer of his seventeenth year, Sam­uel Sooleymon gets the chance of a lifetime: a trip to the United States with his South Sudanese teammates to play in a showcase basket­ball tournament. He has never been away from home, nor has he ever been on an airplane. The opportunity to be scouted by dozens of college coaches is a dream come true.Samuel is an amazing athlete, with speed, quick­ness, and an astonishing vertical leap. The rest of his game, though, needs work, and the American coaches are less than impressed.During the tournament, Samuel receives dev­astating news from home: A civil war is raging across South Sudan, and rebel troops have ran­sacked his village. His father is dead, his sister is missing, and his mother and two younger brothers are in a refugee camp.Samuel desperately wants to go home, but it's just not possible. Partly out of sympathy, the coach of North Carolina Central offers him a scholar­ship. Samuel moves to Durham, enrolls in classes, joins the team, and prepares to sit out his freshman season. There is plenty of more mature talent and he isn't immediately needed.Gripping and moving, Sooley showcases John Grisham's unparalleled storytelling powers in a whole new light. This is Grisham at the top of his game. ",
      "aboutAuthor":"John Grisham is the author of forty-seven consecutive #1 bestsellers, which have been translated into nearly fifty languages. His recent books include The Judge's List, Sooley, and his third Jake Brigance novel, A Time for Mercy, which is being developed by HBO as a limited series.Grisham is a two-time winner of the Harper Lee Prize for Legal Fiction and was honored with the Library of Congress Creative Achievement Award for Fiction.When he's not writing, Grisham serves on the board of directors of the Innocence Project and of Centurion Ministries, two national organizations dedicated to exonerating those who have been wrongfully convicted. Much of his fiction explores deep-seated problems in our criminal justice system.",
    },
    {
    "name":"Upgrade",
    "author":" Blake Crouch",
    "bookImage":"book43.jpg",
    "bookPrize":"$ 400.00",
    "orginalBookPrize":"$ 478.00",
    "publisher":"12 July 2022  ",
    "relesedDate":"  Ballantine Books  ",
    "bookStockDetails":"Available",
    "aboutbook":"The mind-blowing new thriller from the New York Times bestselling author of Dark Matter and Recursion.At first, Logan Ramsay isn’t sure if anything’s different. He just feels a little . . . sharper. Better able to concentrate. Better at multitasking. Reading a bit faster, memorizing better, needing less sleep.But before long, he can’t deny it: Something’s happening to his brain. To his body. He’s starting to see the world, and those around him—even those he loves most—in whole new ways.The truth is, Logan’s genome has been hacked. And there’s a reason he’s been targeted for this upgrade. A reason that goes back decades to the darkest part of his past, and a horrific family legacy.Worse still, what’s happening to him is just the first step in a much larger plan, one that will inflict the same changes on humanity at large—at a terrifying cost.Intimate in scale yet epic in scope, Upgrade is an intricately plotted, lightning-fast tale that charts one man’s thrilling transformation, even as it asks us to ponder the limits of our humanity—and our boundless potential.",
    "aboutAuthor":"Blake Crouch is a bestselling novelist and screenwriter. He is the author of the forthcoming novel, Dark Matter, for which he is writing the screenplay for Sony Pictures. His international-bestselling Wayward Pines trilogy was adapted into a television series for FOX, executive produced by M. Night Shyamalan, that was Summer 2015’s #1 show. With Chad Hodge, Crouch also created Good Behavior, the TNT television show starring Michelle Dockery based on his Letty Dobesh novellas. He has written more than a dozen novels that have been translated into over thirty languages and his short fiction has appeared in numerous publications including Ellery Queen and Alfred Hitchcock Mystery Magazine. Crouch lives in Colorado with his family.",
  },
  {
    "name":"Milk and Honey",
    "author":"Rupi Kaur ",
    "bookImage":"book36.webp",
    "bookPrize":"$ 274.00",
    "orginalBookPrize":"$ 499.00",
    "publisher":" Andrews McMeel Publishing ",
    "relesedDate":" 06 Oct 2015  ",
    "bookStockDetails":"Available",
    "aboutbook":"Milk and Honey is an Indian-Canadian collection of both abstract fiction and non-fiction poetry and prose by Rupi Kaur.Rupi Kaur is the Writer of the Decade-The New Republic,#1 New York Times bestseller milk and honey is a collection of poetry and prose about survival. About the experience of violence, abuse, love, loss, and femininity.The book is divided into four chapters, and each chapter serves a different purpose. Deals with a different pain. Heals a different heartache. milk and honey takes readers through a journey of the most bitter moments in life and finds sweetness in them because there is sweetness everywhere if you are just willing to look.",
    "aboutAuthor":"About the Author: RUPI KAUR is a poet, artist, and performer. As a 21-year-old university student Rupi wrote, illustrated, and self-published her first poetry collection, milk and honey. Next came its artistic sibling, the sun and her flowers. These collections have sold over 10 million copies and have been translated into over 40 languages. Her latest collection, home body, debuted #1 on bestseller lists across the world. As she has done in all things from the very beginning, Rupi self-produced Rupi Kaur Live, the first poetry special of its kind, which debuted on Amazon Prime Video in 2021. Rupi's work touches on love, loss, trauma, healing, femininity, and migration. She feels most at home when creating art, performing her poetry onstage, and spending time with family and friends.",
  },
  {
    "name":"You Are a Badass",
    "author":" Jen Sincero",
    "bookImage":"book37.webp",
    "bookPrize":"$ 374.00",
    "orginalBookPrize":"$ 501.00",
    "publisher":"Running Press Adult   ",
    "relesedDate":" 23 Apr 2013  ",
    "bookStockDetails":"Available",
    "aboutbook":"Packed with humor, inspiration, and advice, You Are a Badass is the #1 New York Times bestselling self-help book that teaches you how to get better without getting busted.YOU ARE A BADASS IS THE SELF-HELP BOOK FOR PEOPLE WHO DESPERATELY WANT TO IMPROVE THEIR LIVES BUT DONT WANT TO GET BUSTED DOING IT. In This Refreshingly Entertaining How-to Guide, Bestselling Author And World-traveling Success Coach, Jen Sincero, Serves Up 27 Bitesized Chapters Full Of Hilariously Inspiring Stories, Sage Advice, Easy Exercises, And The Occasional Swear Wor YOU ARE A BADASS IS THE SELF-HELP BOOK FOR PEOPLE WHO DESPERATELY WANT TO IMPROVE THEIR LIVES BUT DONT WANT TO GET BUSTED DOING IT. In This Refreshingly Entertaining How-to Guide, Bestselling Author And World-traveling Success Coach, Jen Sincero, Serves Up 27 Bitesized Chapters Full Of Hilariously Inspiring Stories, Sage Advice, Easy Exercises, And The Occasional Swear Word, Helping You To: - Identify And Change The Self-sabotaging Beliefs And Behaviours That Stop You From Getting What You Want. - Create A Life You Totally Love. And Create It NOW - Make Some Damn Money Already. The Kind Youve Never Made Before. By The End Of You Are A Badass, Youll Understand Why You Are How You Are, How To Love What You Cant Change, How To Change What You Dont Love, And How To Use The Force To Kick Some Serious Ass.",
    "aboutAuthor":"Jen Sincero is a #1 New York Times bestselling author, speaker, and success coach who has helped countless people transform their personal and professional lives via her newsletters, products, seminars, public appearances, and books. A few years ago, Jen said goodbye to her home in California in order to travel the world indefinitely and encourages as many people as possible to live lives of unbridled awesomeness. You can find out more, and sign up for her newsletter at jensincero.com.",
  },
  
]
fiction : Array<any>=[
  {
    "name":"Paths of Fear",
    "author":" Mrs Connie Kerbs ",
    "bookImage":"book26.jpg",
    "bookPrize":"$ 976.00",
    "orginalBookPrize":"$ 999.00",
    "publisher":"F.I.N.E. Reads Press  ",
    "relesedDate":"  01 Oct 2016  ",
    "bookStockDetails":"Available",
    "aboutbook":"Paths of Fear is a unique anthology which explores that universal and misunderstood experience we call fear. This enjoyable read is part psychological, part informational, and all inspirational. It is largely personal narrative with a sprinkling of poetry and all entertainment. Paths of Fear explores a broad range of fears from that which manifests in screams of sheer terror, to that immobilizing, fear-ridden freeze we all understand. This survey sheds light on that deep, dark discouragement that reminds us of how we might fall short or fail. It exposes furtive beliefs sometimes rooted in us that we, aren't enough; a destructive idea cultivated in toxic environments which erode us from the inside out. Thought-provoking narratives highlight the many faces of fear with the sensitivity and insight of real experience. A wide variety of real-life examples are offered up on how others have dealt with fearful things and fearful places in life. Some of these circumstances have called for a long endurance, with dignity and grace; others required a special kind of strength and defiance. All are examples of facing fear, on one's own terms, inspiring in their own right. This part psychological survey, part self-help, and part spiritual essay spotlights the true antidote to fear - love, of one kind or another. Secularly accessible, but decidedly faith-based, Paths of Fear de-masks the monsters of circumstance and sheds light on some of the darker recesses of life experience. It is a pleasing, poignant reveal of courage, faith, and modern knowledge balanced with age-old wisdom. Paths of Fear encourages us to rely on our best, healthy sense of true self, and a heartfelt love for others. It's a collection to inspire readers down paths of faith and hope and to encourage anyone through trials of fear they must overcome.",
    "aboutAuthor":"About the Author: Indeed... On being blessed with early spiritual experiences: these would be as a conduit between myself and a renewable fountain of faith which has utterly saved me time and again. Indeed, this source of amazing grace ever rescues, revives, and rejuvenates still my soul. On having a grandmother whose upstairs library I perused: it was here I met first the Caldecott and Newbery classics, enduring poets, composers, story-telling icons and literary giants. Indeed, I was irrevocably impressed. On having an antique, script, manual type-writer tossed my way: it defined my tender years. Indeed, it nurtured my budding muse. On being married to my childhood sweetheart for 30(plus) years: I am in awe of our incredible journey together. We have been honed and humbled even as we've been bathed in bliss. I am grateful he has been my faithful, capable - and especially good-humored companion all this time. My admiration and love for him are indescribable. Indeed, words fail to convey such a divine devotion. On being adoptive-foster parents for nearly a quarter of a century: this means bevies of babies and bus-loads of youth of all ages and stages have graced our home, profoundly altering us. With 13 adopted, and three procured the old-fashioned way, indeed, I love and appreciate beyond expression, being honed and owned all this time by these precious people. On all the above and more, my family, dear friends, Walk of Faith, and my writing journey: these have indeed, all made for the savoriest of lives and the ultimate, beautiful mess. It is to my great delight that such a crazy-wonderful menagerie has somehow chosen me! On writing: Indeed, is there anything better than ever growing, changing, and becoming? Is there anything better than that release of tremors that have rumbled inside for eons, as they built up a force to be reckoned with? When they finally find their focus to surge into a tsunami of positive energy that ripples out into the world - to leave its mark. To leave it just a little better place than they might have found it? Indeed. It is not that I found writing. For some-how, some-why, it found and claimed me. It's not even that I am a writer, per say. I am just a vessel in which a small but powerful portion of that endless stream, that fountain of renewable vigor - pours a bit of itself in me for a time. ",
   
  },
  {
    "name":"Kafka On The Shore",
    "author":" Haruki Murakami",
    "bookImage":"book27.jpg",
    "bookPrize":"$ 419.00",
    "orginalBookPrize":"$ 599.00",
    "publisher":"  Vintage Publishing ",
    "relesedDate":" 03 Oct 2005  ",
    "bookStockDetails":"Available",
    "aboutbook":"Alternate cover edition here . Kafka on the Shore , a tour de force of metaphysical reality, is powered by two remarkable characters: a teenage boy, Kafka Tamura, who runs away from home either to escape a gruesome oedipal prophecy or to search for his long-missing mother and sister; and an aging simpleton called Nakata, who never recovered from a wartime affliction and now i Alternate cover edition here . Kafka on the Shore , a tour de force of metaphysical reality, is powered by two remarkable characters: a teenage boy, Kafka Tamura, who runs away from home either to escape a gruesome oedipal prophecy or to search for his long-missing mother and sister; and an aging simpleton called Nakata, who never recovered from a wartime affliction and now is drawn toward Kafka for reasons that, like the most basic activities of daily life, he cannot fathom. Their odyssey, as mysterious to them as it is to us, is enriched throughout by vivid accomplices and mesmerizing events. Cats and people carry on conversations, a ghostlike pimp employs a Hegel-quoting prostitute, a forest harbors soldiers apparently unaged since World War II, and rainstorms of fish (and worse) fall from the sky. There is a brutal murder, with the identity of both victim and perpetrator a riddleyet this, along with everything else, is eventually answered, just as the entwined destinies of Kafka and Nakata are gradually revealed, with one escaping his fate entirely and the other given a fresh start on his own.",
    "aboutAuthor":"Haruki Murakami was born in Kyoto, Japan, in 1949. He grew up in Kobe and then moved to Tokyo, where he attended Waseda University. After college, Murakami opened a small jazz bar, which he and his wife ran for seven years.In 1978 Murakami was in the bleachers of Jingu Stadium watching a baseball game between the Yakult Swallows and the Hiroshima Carp when Dave Hilton, an American, came to bat. According to an oft-repeated story, in the instant that he hit a double, Murakami suddenly realized that he could write a novel. He went home and began writing that night.His first novel, Hear the Wind Sing, won the Gunzou Literature Prize for budding writers in 1979. He followed this success with two sequels, Pinball, 1973 and A Wild Sheep Chase, which all together form “The Trilogy of the Rat.” ",
  
  },
  {
    "name":"Wish I Could Tell You",
    "author":"Durjoy Datta ",
    "bookImage":"book77.jpg",
    "bookPrize":"$ 176.00",
    "orginalBookPrize":"$ 199.00",
    "publisher":" Penguin Metro Reads ",
    "relesedDate":" 4 October 2019  ",
    "bookStockDetails":"Available",
    "aboutbook":"Can you find yourself after you have lost that special someone? A disillusioned and heartbroken Anusha finds herself in the small world of WeD. Struggling to cope with her feelings and the job of raising money for charity, she reluctantly searches for a worthwhile cause to support.For Ananth, who has been on the opposite side, no life is less worthy, no cause too small to support. Behind them are teams for whom going to extraordinary lengths to save lives is more than a full-time occupation. In front of them is the virtual world of social media-watching, interacting, judging, making choices, and sometimes, saving lives. From the virtual to the real, their lives and that of their families, entangle in a way that moving together is the only solution. They can't escape each other. In this world of complicated relationships, should love be such a difficult ride?",
    "aboutAuthor":"Durjoy Datta was born in New Delhi, and completed a degree in engineering and business management before embarking on a writing career. His first book-Of Course I Love You . . .-was published when he was twenty-one years old and was an instant bestseller. His successive novels-Now That You're Rich . . .; She Broke Up, I Didn't! . . .; Oh Yes, I'm Single! . . .; You Were My Crush . . .; If It's Not Forever . . .; Till the Last Breath . . .; Someone Like You; Hold My Hand; When Only Love Remains; World's Best Boyfriend; The Girl of My Dreams; The Boy Who Loved; The Boy with the Broken Heart and The Perfect Us-have also found prominence on various bestseller lists, making him one of the highest-selling authors in India.Durjoy also has to his credit nine television shows and has written over a thousand episodes for television. He lives in Mumbai. For more updates, you can follow him on Facebook (www.facebook.com/durjoydatta1) or Twitter (@durjoydatta) or mail him at durjoydatta@gmail.com.",
  },
  {
    "name":"Overkill ",
    "author":"Sandra Brown",
    "bookImage":"book24.webp",
    "bookPrize":"$ 1,930.0",
    "orginalBookPrize":"$ 2,460.0",
    "publisher":"Grand Central Publishing  ",
    "relesedDate":"  16 Aug 2022 ",
    "bookStockDetails":"Available",
    "aboutbook":"Former Super Bowl MVP quarterback Zach Bridger hasn't seen his ex-wife, Rebecca Pratt, for some time--not since their volatile marriage imploded--so he's shocked to receive a life-altering call about her. Rebecca has been placed on life support after a violent assault, and he--despite their divorce--has medical power-of-attorney. Zach is asked to make an impossible choice: keep her on life support or take her off of it. Buckling under the weight of the responsibility and the glare of public scrutiny, Zach ultimately walks away, letting Rebecca's parents have the final say.Four years later, Rebecca's attacker, Eban--the scion of a wealthy family in Atlanta--gets an early release from prison. The ludicrous miscarriage of justice reeks of favoritism, and Kate Lennon, a brilliant state prosecutor, is determined to put him back behind bars. Rebecca's parents have kept her alive all these years, but if her condition were to change--if she were to die--Eban could be retried on a new charge: murder.It isn't lost on Zach that in order for Eban to be charged with Rebecca's murder, Zach must actually be the one to kill her. He rejects Kate's legal standpoint but can't resist their ill-timed attraction to each other. Eban, having realized the jeopardy he's in, plots to make certain that neither Zach nor Kate lives to see the death of Rebecca--and the end of his freedom. ",
    "aboutAuthor":" Sandra Brown is the author of seventy-three New York Times bestsellers. There are more than eighty million copies of her books in print worldwide, and her work has been translated into thirty-four languages. Four of her books have been made into films. In 2008, the International Thriller Writers named Brown its Thriller Master, the organization's highest honor. She has served as president of Mystery Writers of America and holds an honorary doctorate of humane letters from Texas Christian University. She lives in Texas.",
  },
  {
    "name":"War of Lanka",
    "author":"Amish Tripathi",
    "bookImage":"book25.jpeg",
    "bookPrize":"$ 352.00",
    "orginalBookPrize":"$ 495.00",
    "publisher":"HarperCollins India",
    "relesedDate":" 3 October 2022  ",
    "bookStockDetails":"Available",
    "aboutbook":"Greed. Rage. Grief. Love. Smouldering Tinder, Waiting To Trigger A War.But This War Is Different. This One Is For Dharma. This War Is For The Greatest Goddess Of Them All.Sita Has Been Kidnapped. Defiantly, She Dares Raavan To Kill Her - She'd Rather Die Than Allow Ram To Surrender.Ram Is Beside Himself With Grief And Rage. He Prepares For War. Fury Is His Fuel. Calm Focus, His Guide.Raavan Thought He Was Invincible. He Thought He'd Negotiate And Force A Surrender. Little Did He Know ...The First Three Books Of The Second-fastest-selling Book Series In Indian Publishing History - The Ram Chandra Series - Explore The Individual Journeys Of Ram, Sita And Raavan. In This, The Epic Fourth Book Of The Series, Their Narrative Strands Crash Into Each Other, And Explode In A Slaughterous War.Will Ram Defeat The Ruthless And Fiendish Raavan, Constrained As He Is By The Laws Of Dharma Will Lanka Burn To A Cinder Or Fight Back Like A Cornered Tiger Will The Terrible Costs Of War Be Worth The Victory. ",
    "aboutAuthor":"Amish is a 1974-born, IIM (Kolkata)-educated banker-turned-author. The success of his debut book, The Immortals of Meluha (Book 1 of the Shiva Trilogy), encouraged him to give up his career in financial services to focus on writing. Besides being an author, he is also an Indian-government diplomat, a host for TV documentaries, and a film producer. Amish is passionate about history, mythology and philosophy, finding beauty and meaning in all world religions. His books have sold more than 6 million copies and have been translated into over 20 languages. His Shiva Trilogy is the fastest selling and his Ram Chandra Series the second fastest selling book series in Indian publishing history. You can connect with Amish here: ",
  },
      {
      "name":"Something I Never Told You",
      "author":"Shravya Bhinder",
      "bookImage":"book76.webp",
      "bookPrize":"$ 167.00",
      "orginalBookPrize":"$ 280.00",
      "publisher":" Penguin ",
      "relesedDate":" 14 February 2019  ",
      "bookStockDetails":"Available",
      "aboutbook":"When in love, you tend to take each other for granted, and sometimes, that can cost you a lifetime of togetherness . . .Ronnie knew that his first crush was way out of his league, and yet he pursued and wooed Adira. Shyly and from a distance in the beginning, and more persuasively later. He couldn't believe it when the beautiful Adira actually began to reciprocate, falling in love with him for his simplicity and honesty. Slowly, as they get close and comfortable with each other, life takes on another hue. From truly magical it becomes routine. There are fights and then making-up sessions-a clash of egos and doubts.Things begin to change for the worst.It is too late.Ronnie and Adira will probably never find their forever after . . .",
      "aboutAuthor":"Shravya loves to find hidden stories around her and write novels about them. Formerly a corporate employee, she managed to flee the madness after a few years of boredom to become a full-time writer. She is a sucker for romance and strives to pen down exciting stories.When she is not reading and writing, she is out enjoying nature, playing with her dogs or cooking for her family.She lives in Melbourne with her family, in a house with a barren backyard and a lifetime's collection of books.",
    }

]
under200 : Array<any>=[
  {
    "name":"Where the Sun Never Sets",
    "author":"Stuti Changle",
    "bookImage":"book222.webp",
    "bookPrize":"$ 170.00",
    "orginalBookPrize":"$ 250.00",
    "publisher":" Penguin",
    "relesedDate":" 5 July 2022 ",
    "bookStockDetails":"Available",
    "aboutbook":"A story about finding hope in the darkest of times that will brighten your day!.Iti is forced to move back to her hometown of Mussoorie amid worldwide lockdown to work on her first movie script. Iti's chance encounter with her first love, Nishit, reunion with her estranged best friend, Shelly, and nights spent reading her well-kept diary, make her best memories and worst nightmares come to life. She has always run away from her past, but now has no choice.Set in the COVID-19 lockdown, from the national bestselling author of On the Open Road and You Only Live Once, Where the Sun Never Sets is a riveting personal account of unforgettable childhood dreams, turbulent teenage years, complicated close relationships, human resilience, and the never-ending journey of growing up.",
    "aboutAuthor":"Dale Carnegie has authored close to eleven books and multiple articles on solving everyday problems and achieving success, his books have helped millions of people feel better prepared for life.",
  },
  {
    "name":"Pieces Of Her",
    "author":" Devanshi Prabhakar ",
    "bookImage":"book217.webp",
    "bookPrize":"$ 111.00",
    "orginalBookPrize":"$ 150.00",
    "publisher":"Bluerose Publishers Pvt. Ltd. ",
    "relesedDate":" 1 January 2021",
    "bookStockDetails":"Available",
    "aboutbook":" be nice to yourself, you're trying. if its taking longer than you thought it would to achieve something or to move on from someone it's okay. try not to compare yourself to others, you're alive and smiling, and that's what matters. keep trying. find yourself again. you'll get there. ",
    "aboutAuthor":" Devanshi Prabhakar was an indian writer. born in kerala..be nice to yourself, you're trying. if its taking longer than you thought it would to achieve something or to move on from someone it's okay. try not to compare yourself to others, you're alive and smiling, and that's what matters. keep trying. find yourself again. you'll get there.",
  },
  {
    "name":"Half Girlfriend",
    "author":"CHETAN BHAGAT",
    "bookImage":"book218.jpg",
    "bookPrize":"$ 106.00",
    "orginalBookPrize":"$ 167.00",
    "publisher":" Rupa Publications India  ",
    "relesedDate":" 01 Oct 2014 ",
    "bookStockDetails":"Available",
    "aboutbook":"Once upon a time, there was a Bihari boy called Madhav. He fell in love with a rich girl from Delhi called Riya. Madhav didn't speak English well. Riya did. Madhav wanted a relationship. Riya didn't. Riya just wanted friendship. Madhav didn't. Riya suggested a compromise. She agreed to be his half-girlfriend. From the author of the blockbuster novels Five Point Someone, One Night @ the Call Center, The 3 Mistakes of My Life, 2 States and Revolution 2020 comes a simple and beautiful love story that will touch your heart and inspire you to chase your dreams.",
    "aboutAuthor":"Chetan Bhagat is an Indian author, columnist and YouTuber. He was included in Time magazine's list of World's 100 Most Influential People in 2010. Five of his novels have been adapted into films.Chetan then decided to make writing a full-time career. His third novel “The 3 Mistakes of my life” published in 2008 also became a huge success. This novel became a bestseller and Chetan also became the most successful English-Language writer in India. The Bollywood hit movie “Kai Po Che” is based on this novel.",
  },
  {
    "name":"Promise me a million times",
    "author":"Keshav Aneel ",
    "bookImage":"book219.webp",
    "bookPrize":"$ 129.00",
    "orginalBookPrize":"$ 186.00",
    "publisher":" Srishti Publishers & Distributors",
    "relesedDate":" 27 July 2016",
    "bookStockDetails":"Available",
    "aboutbook":" Believing that life always gives us all a second chance is too bookish a thought. Because sometimes, by the time we finally realize our faults and true potential, times have changed dramatically. Like a couple of migratory birds, both Charlie and Edwin leave everything back in their village and settle for a new life in the big city. For Edwin, it was where he was going to chase his dreams of becoming an actor; But for Charlie, it was just another place to be with his only friend, to help him accomplish his dreams. However, life seemed to have different plans as it throws Charlie in Aster's way, who was silently walking through instabilities of her own destiny. He could never have guessed, but he was in for an absolute unthoughtful phase of profoundness, which was going to last forever. Promise me a Million Times is a story of dreams, friendship, struggles and a will to make up for every loss with love by your side.",
    "aboutAuthor":"Keshav Aneel is a young marketing professional, who chose to take the route of his heart, ending his brief stint in corporate soon after completing his studies in Business Administration. He immersed himself in honing his creative side and now revels in it. 'A University Gold Medalist' in debate and an affluent public speaker, he is a poet at heart and an avid traveler, in love with the blue sky side of life.",
  },
  {
    "name":"When Love Came Calling",
    "author":"Preeti Shenoy ",
    "bookImage":"book220.webp",
    "bookPrize":"$ 110.00",
    "orginalBookPrize":"$ 190.00",
    "publisher":"Srishti Publishers & Distributors ",
    "relesedDate":"17 August 2020 ",
    "bookStockDetails":"Available",
    "aboutbook":"Puja, 19, chaotic, unorganized, energetic, a baffling puzzle to her family. Her philosophy? Life is just too complicated; only a small group of super achievers have it figured out. Her strict mother sends her to a remote rural location in Kerala and Puja has to spend her summer vacation doing voluntary work.Arush, 20, studious, careful, shy. Born and raised in Britain, he is elated when he gets chosen for an International program to spend twelve weeks in India. Here’s an opportunity to explore his roots.When Puja and Arush meet, all they can think of is how unbelievably different the other one is. But with choppy internet and no other distractions, they start getting to know each other and slowly fall in love. But falling in love and staying in love are not the same thing.When disaster strikes, they are embroiled in a dangerous situation that spirals out of control. Puja is forced to confront the harsh realities of life while Arush realises that India is not always the picture-perfect postcard he presumed it was.Desperately fighting to expose the truth and save themselves, what happens to their love? Is it strong enough to survive forces that threaten to destroy it? Is it deep enough to drown their own doubts? Sometimes you have to travel far to find your true self.",
    "aboutAuthor":"Preeti Shenoy is the bestselling author of Life is What You Make It and eleven other titles. Her books have been translated into several Indian and foreign languages. She is among the highest-selling authors in India. She is also a speaker, columnist, and artist. Preeti has been featured on BBC, Conde Nast, Verve, India Today and all other major media.Preeti Shenoy is the bestselling author of Life is What You Make It and twelve other titles. She is among the highest-selling authors in India. She is also a speaker, columnist, and artist.",
  },
  {
    "name":"That Kiss in the Rain",
    "author":"Novoneel Chakraborty",
    "bookImage":"book221.webp",
    "bookPrize":"$ .00",
    "orginalBookPrize":"$ .00",
    "publisher":"Srishti Publishers & Distributors ",
    "relesedDate":" 15 May 2019",
    "bookStockDetails":"Available",
    "aboutbook":" Pallavi, an air hostess by profession, is a vivacious and venomous as hell girl, who lives her life out loud and on the edge. She lives by just one rule: fuck and forget. The one side that nobody knows about her is that she still hasn't moved on from the hurt of her first love: haasil. Haasil is a successful, self-made and young entrepreneur who is both physically and emotionally recuperating from a fatal accident in which he lost the true love of his life. Swadha is a corporate girl, who is cute, unintentionally funny and head over heels in love with haasil. That kiss in the rain happens when Pallavi, haasil and swadha are touched by the sublime power of love in different ways, till their paths cross and their destinies collide, bringing them at a crossroad where each has to make a life-altering decision.",
    "aboutAuthor":"Novoneel Chakraborty is the bestselling author of ten romantic thriller novels and one short story collection. Known for his twists, dark plots and strong female protagonists, he is also popular as the Sidney Sheldon of India. His books have created newer benchmarks of success with each successive title. Having been translated into several Indian languages, one is soon to be a web series. Apart from novels, Novoneel has written several popular TV shows Like Savdhaan India and Yeh Hai Aashiqui. He lives and works in Mumbai.",
  }
]
under400 : Array <any>=[
  {
    "name":"You Only Live Once",
    "author":"Stuti Changle",
    "bookImage":"book210.jpg",
    "bookPrize":"$ 170.00",
    "orginalBookPrize":"$ 260.00",
    "publisher":"Penguin eBury Press  ",
    "relesedDate":"Stuti Changle ",
    "bookStockDetails":"Available",
    "aboutbook":"What if you ran away from your life today?Twenty years later, three people are looking for you.One is dying to meet you again.The other wishes you had never met them.The third wishes they could have met you at least once.You are one person. Aren't you? But you are not the same person to each of them.Find the answers about your own life in this story about searching for love and discovering yourself. Join a broken but rising YouTube star Alara, a struggling but hopeful stand-up comedian Aarav, and a zany but zen beach shack owner Ricky. Together, take the journey to seek the truth behind the famous singer Elisha's disappearance somewhere by the deep sea in Goa.Will you be able to find Elisha? Or will you end up finding yourself?",
    "aboutAuthor":"Stuti Changle is a bestselling author. She won notable mentions in Amazon Kindle's Pen to Publish 2018 competition. You Only Live Once is her second book.Stuti is a postgraduate in management from IMI and she quit her corporate career to inspire people by sharing life-changing stories. She is often invited by prestigious institutions for speaker engagements, where she encourages young people to follow their dreams. She made her TV debut in 2019 as a host of the TV Series Kar Ke Dikhaenge.Stuti has sailed to the Andamans, camped with Indian jawans in Arunachal Pradesh, scuba-dived in the Indian Ocean, swum with the dolphins in the Mediterranean, floated free for hours on the island of Mallorca and wishes to travel the world before she dies. Every year, she spends time in the coastal village of Palolem in Goa. She is currently based in New Delhi, where she lives with her husband, Kushal Nahata, co-founder and CEO of FarEye.",
  },
  {
    "name":"All Your Perfects",
    "author":" Colleen Hoover",
    "bookImage":"book211.jpg",
    "bookPrize":"$ 329.00",
    "orginalBookPrize":"$ 599.00",
    "publisher":" Atria Books",
    "relesedDate":"17 Jul 2018  ",
    "bookStockDetails":"Available",
    "aboutbook":"Quinn and Graham's perfect love is threatened by their imperfect marriage. The memories, mistakes, and secrets that they have built up over the years are now tearing them apart. The one thing that could save them might also be the very thing that pushes their marriage beyond the point of repair.All Your Perfects is a profound novel about a damaged couple whose potential future hinges on promises made in the past. This is a heartbreaking page-turner that asks: Can a resounding love with a perfect beginning survive a lifetime between two imperfect people?",
    "aboutAuthor":"About the Author: Colleen Hoover is the #1 New York Times bestselling author of more than twenty-three novels, including It Ends with Us, All Your Perfects, Ugly Love, and Verity. In 2015, Colleen and her family founded a nonprofit called The Bookworm Box, a bookstore and monthly book subscription service. Colleen lives in Texas with her husband and their three boys. For more information, please visit ColleenHoover.com.",
  },
  {
    "name":"The Bhagwat Gita",
    "author":"R.R. Varma ",
    "bookImage":"book213.jpg",
    "bookPrize":"$ 180.00",
    "orginalBookPrize":"$ 299.00",
    "publisher":" Prakash Books India Pvt. Ltd. ",
    "relesedDate":" 25 October 2013",
    "bookStockDetails":"Available",
    "aboutbook":"The Bhagwat Gita is the main sourcebook on yoga and is a concise summary of India’s Vedic wisdom. Yet, remarkably, the setting for this classic spiritual text is an ancient Indian battlefield. At the last moment, the great warrior, Arjuna, begins to wonder about the real meaning of his life. Lord Krishna brings His disciple from perplexity to spiritual enlightenment by sharing with him what has come to be known as the Gita. In this interpretation of the Gita, the author explains that the essence of the Gita is the equanimity of mind, which is attained by transcending it because mind consciousness is myopic and only spiritual consciousness abounds in universal love and absolute knowledge. Bhakti yoga, Gyan yoga, and Karma yoga are not the only paths that can lead a seeker to the promised land (moksha), but performance of one’s duty, rendered selflessly with dedication and devotion, too can lead a man to God as assuredly as the other spiritual paths. In fact it is a misconception that Lord Krishna prompted Arjuna to perpetrate war. Lord Krishna exhorted Arjuna only to perform his duty as a warrior in the battlefield, which would lead him to liberation. This best-selling and expanded edition of the most famous and popular of Indian scriptures, contextualizes the book culturally and historically and explains the key concepts of Hindu religious thought and the technical vocabulary of yoga. Chapter introductions, notes, and a glossary help readers understand the book’s message better. Most importantly, the translation uses simple, clear language to impart the poetry, universality, and timelessness of the Gita’s teachings.",
    "aboutAuthor":"R.R. Varma  This best-selling and expanded edition of the most famous and popular of Indian scriptures, contextualizes the book culturally and historically and explains the key concepts of Hindu religious thought and the technical vocabulary of yoga. Chapter introductions, notes, and a glossary help readers understand the book’s message better",
  },
  {
    "name":"Do Epic Shit ",
    "author":"Ankur Warikoo",
    "bookImage":"book214.webp",
    "bookPrize":"$ 260.00",
    "orginalBookPrize":"$ 450.00",
    "publisher":" Juggernaut ",
    "relesedDate":" 1 January 2021",
    "bookStockDetails":"Available",
    "aboutbook":"Ankur Warikoo is an entrepreneur and content creator whose deep, witty and brutally honest thoughts on success and failure, money and investing, self-awareness and personal relationships have made him one of India’s top personal brands. In his first book, Ankur puts together the key ideas that have fuelled his journey – one that began with him wanting to be a space engineer and ended with him creating content that has been seen and read by millions. His thoughts range from the importance of creating habits for long-term success to the foundations of money management, from embracing and accepting failure to the real truth about learning empathy. This is a book to be read, and reread, a book whose lines you will underline and think about again and again, a book you will give your family and friends and strangers. Ankur hopes for this book to become the most gifted book ever!",
    "aboutAuthor":"Ankur Warikoo is an entrepreneur, teacher, content creator and mentor. Ankur founded nearbuy.com and was its CEO from its inception in 2015 until 2019. Prior to that, Ankur was the founding CEO of Groupon’s India business. Today he spends his time creating content, teaching online and mentoring first-time founders.",
  },
  {
    "name":"A Man Called Ove ",
    "author":"Fredrik Backman",
    "bookImage":"book215.webp",
    "bookPrize":"$ 225.00",
    "orginalBookPrize":"$ 310.00",
    "publisher":" Sceptre ",
    "relesedDate":" 7 May 2015 ",
    "bookStockDetails":"Available",
    "aboutbook":"The million-copy bestselling phenomenon, Fredrik Backman's heartwarming debut is a funny, moving, uplifting tale of love and community that will leave you with a spring in your step. Perfect for fans of Rachel Joyce's The Unlikely Pilgrimage of Harold Fry, Graeme Simsion's The Rosie Project and David Nicholl's US. New York Times bestseller'Warm, funny, and almost unbearably moving' Daily Mail'Rescued all those men who constantly mean to read novels but never get round to it' Spectator Books of the YearAt first sight, Ove is almost certainly the grumpiest man you will ever meet. He thinks himself surrounded by idiots - neighbours who can't reverse a trailer properly, joggers, shop assistants who talk in code, and the perpetrators of the vicious coup d'etat that ousted him as Chairman of the Residents' Association. He will persist in making his daily inspection rounds of the local streets. But isn't it rare, these days, to find such old-fashioned clarity of belief and deed? Such unswerving conviction about what the world should be, and a lifelong dedication to making it just so?In the end, you will see, there is something about Ove that is quite irresistible. . .",
    "aboutAuthor":"Fredrik Backman is a Swedish blogger, columnist and author. His debut novel A MAN CALLED OVE was a number 1 bestseller across Scandinavia, has sold over one million copies worldwide, was a Richard & Judy summer read in the UK and an instant New York Times paperback bestseller, and has been made into an acclaimed film. Fredrik's subsequent novels, MY GRANDMOTHER SENDS HER REGARDS AND APOLOGISES and BRITT-MARIE WAS HERE, also went straight to number 1 in Sweden on publication.",
  },
  {
    "name":"Da Vinci Code",
    "author":" Dan Brown ",
    "bookImage":"book216.webp",
    "bookPrize":"$ 350.00",
    "orginalBookPrize":"$ 490.00",
    "publisher":" Transworld Publishers Ltd  ",
    "relesedDate":"28 Aug 2009 ",
    "bookStockDetails":"Available",
    "aboutbook":"Harvard professor Robert Langdon receives an urgent late-night phone call while on business in Paris: the elderly curator of the Louvre has been brutally murdered inside the museum. Alongside the body, police have found a series of baffling codes. nnAs Langdon and a gifted French cryptologist, Sophie Neveu, begin to sort through the bizarre riddles, they are stunned to find a trail that leads to the works of Leonardo Da Vinci – and suggests the answer to a mystery that stretches deep into the vault of history.nnUnless Langdon and Neveu can decipher the labyrinthine code and quickly assemble the pieces of the puzzle, a stunning historical truth will be lost forever…",
    "aboutAuthor":"Dan Brown is the bestselling author of Digital Fortress, Deception Point, Angels and Demons, The Da Vinci Code and The Lost Symbol. He is a graduate of Amherst College and Phillips Exeter Academy, where he has taught English and creative writing. He lives in New England.",
  }

]
comboOffer : Array <any>=[
  {
    "name":"It Ends With Us And It Start With Us Best 2 Books Combo",
    "author":"Colleen Hoover ",
    "bookImage":"combo13.webp",
    "bookPrize":"$ 469.00",
    "orginalBookPrize":"$ 1,089.00",
    "publisher":"Sarkar publisher of Mumbai",
    "relesedDate":"21 aug 2022 ",
    "bookStockDetails":"Available",
    "aboutbook":"Product Description Don't miss IT STARTS WITH US, the sequel to IT ENDS WITH US. Coming October 2022! Pre-order your copy now. __________________________________________________________________________________________________________________________________ “A brave and heartbreaking novel that digs its claws into you and doesn’t let go, long after you’ve finished it” Anna Todd, bestselling author From the #1 bestselling author of All Your Perfects, a workaholic with a too-good-to-be-true romance can’t stop thinking about her first love. Lily hasn’t always had it easy, but that’s never stopped her from working hard for the life she wants. She’s come a long way from the small town where she grew up—she graduated from college, moved to Boston, and started her own business. And when she feels a spark with a gorgeous neurosurgeon named Ryle Kincaid, everything in Lily’s life seems too good to be true. Ryle is assertive, stubborn, maybe even a little arrogant. He’s also sensitive, brilliant, and has a total soft spot for Lily. And the way he looks in scrubs certainly doesn’t hurt. Lily can’t get him out of her head. But Ryle’s complete aversion to relationships is disturbing. Even as Lily finds herself becoming the exception to his “no dating” rule, she can’t help but wonder what made him that way in the first place. As questions about her new relationship overwhelm her, so do thoughts of Atlas Corrigan—her first love and a link to the past she left behind. He was her kindred spirit, her protector. When Atlas suddenly reappears, everything Lily has built with Ryle is threatened. With this bold and deeply personal novel, It Ends With Us is a heart-wrenching story and an unforgettable tale of love that comes at the ultimate price. ",
    "aboutAuthor":"Colleen Hoover is the #1 New York Times bestselling author of more than twenty-three novels, including It Ends with Us, All Your Perfects, Ugly Love, and Verity. In 2015, Colleen and her family founded a nonprofit called The Bookworm Box, a bookstore and monthly book subscription service that has donated over $1,000,000 to various charities to date. Colleen lives in Texas with her husband and their three boys. For more information, please visit ColleenHoover.com.",
  },
  {
    "name":"Anna Huang Twisted Combo Pack Of 4 Books",
    "author":" Ana Huang",
    "bookImage":"combo11.webp",
    "bookPrize":"$ 1712.00",
    "orginalBookPrize":"$ 2447.00",
    "publisher":" Boba Press ",
    "relesedDate":" 1 January 2022 ",
    "bookStockDetails":"Available",
    "aboutbook":" Anna Huang Twisted Combo Pack Of 4 Books.Stoic, broody, and arrogant, elite bodyguard Rhys Larsen has two rules: 1) Protect his clients at all costs 2) Do not become emotionally involved. Ever.Bridget von Ascheberg. A princess with a stubborn streak that matches his own and a hidden fire that reduces his rules to ash. She's nothing he expected and everything he never knew he needed.",
    "aboutAuthor":"Ana Huang is an author of primarily steamy New Adult and contemporary romance. Her stories range from lighthearted to dark, but they all have HEAs with plenty of banter and swoon sprinkled in. Besides reading and writing, Ana loves traveling, is obsessed with hot chocolate, and has multiple relationships with fictional boyfriends. She lives in New York City.",
  },
  {
    "name":"Reminders Of Him + November 9 (Colleen Hoover Combo)",
    "author":"Colleen Hoover ",
    "bookImage":"combo16.webp",
    "bookPrize":"$ 312.00",
    "orginalBookPrize":"$ 1,073.00",
    "publisher":"Generic",
    "relesedDate":"1 November 2021 ",
    "bookStockDetails":"Available",
    "aboutbook":"Reminders Of Him + November 9 (Colleen Hoover Superhit Collection) (2 Books Combo Set by Colleen Hoover  (Paperback, Colleen Hoover)",
    "aboutAuthor":"SALLY ROONEY was born in the west of Ireland in 1991. Her work has appeared in The New Yorker, The New York Times, Granta and The London Review of Books. Winner of the Sunday Times Young Writer of the Year Award in 2017, she is the author of Conversations with Friends and the editor of the Irish literary journal The Stinging Fly.",
  },
  {
    "name":"Turtles All The Way Down + The Fault In Our Stars",
    "author":" John Green",
    "bookImage":"combo27.webp",
    "bookPrize":"$ 274.00",
    "orginalBookPrize":"$ 790.00",
    "publisher":" Inder book depot",
    "relesedDate":"3 February 2013  ",
    "bookStockDetails":"Available",
    "aboutbook":"I fell in love the way you fall asleep: slowly, then all at once.Despite the tumour-shrinking medical miracle that has bought her a few years, Hazel has never been anything but terminal, her final chapter inscribed upon diagnosis. But when a gorgeous plot twist named Augustus Waters suddenly appears at Cancer Kid Support Group, Hazel's story is about to be completely rewritten.Insightful, bold, irreverent, and raw, The Fault in Our Stars brilliantly explores the funny, thrilling, and tragic business of being alive and in love.Praise for The Fault in Our Stars: Sunday Times (Culture) 'A touching, often fiercely funny novel'The Sun on Sunday (Fabulous Magazine) 'So good I think it should be compulsory reading for everyone!'Daily Express 'John Green brilliantly captures the voices of a young generation while instilling it with the wisdom of a life that has lived too much yet will never live enough'The Metro - 2013 Best Fiction 'The love affair of two terminally ill teenagers could be mawkish. In fact, it's funny, clever, irreverent and life-affirming.'Grazia 'So good!'Good Housekeeping 'As funny as it is heartbreaking... we defy you not to fall in love with its main characters, Hazel and Augustus.'The Tablet 'A humourous and poignant love story... It's terrifically funny... as well as a moving exploration of loss and grief. And no, it's so much not just for teenage cancer sufferers... it's for everyone.'Bliss 'If you need inspiration when it comes to making the most of a moment, this one is for you'Mizz 'Insightful, bold, irreverent and raw, if this doesn't make you cry, it'll definitely make you think, laugh and maybe even fall in love yourself!'    The Guardian called it 'A new modern classic'. Vox said that it is 'An existential teenage scream'. The Wall Street Journal dubbed it 'Tender, wise and hopeful'And now, you can pre-order Turtles All the Way Down in paperback. 'It's quite rare to find someone who sees the same world you see. 'Sixteen-year-old Aza never intended to pursue the mystery of fugitive billionaire Russell Pickett. But there's a hundred thousand dollar reward at stake and her Best and Most Fearless Friend, Daisy, is eager to investigate. So together, they navigate the short distance and broad divides that separate them from Russell Pickett's son, Davis. Aza is trying. She is trying to be a good daughter, a good friend, a good student and maybe even a good detective, while also living within the ever-tightening spiral of her own thoughts. In his long-awaited return, John Green, the acclaimed, award-winning author of Looking for Alaska and the Fault in Our Stars, shares Aza's story with shattering, unflinching clarity in this brilliant novel of mental health, love, resilience and the power of lifelong friendship.",
    "aboutAuthor":"John Green is the award-winning, #1 bestselling author of Looking for Alaska, An Abundance of Katherines, Paper Towns, Will Grayson, Will Grayson (with David Levithan), The Fault in Our Stars and Turtles All the Way Down    ",
  },
  {
    "name":"Sally Rooney Bestselling Books Combo",
    "author":"Sally Rooney ",
    "bookImage":"combo18.webp",
    "bookPrize":"$ 275.00",
    "orginalBookPrize":"$ 799.00",
    "publisher":"Farrar, Straus and Giroux  ",
    "relesedDate":" 30 January 2021",
    "bookStockDetails":"Available",
    "aboutbook":"Sally Rooney Bestselling Books Combo + Beautiful World Where Are You + Conversation With Friends  ",
    "aboutAuthor":"",
  },
  {
    "name":"AMISH - Ram Chandra Series Combo",
    "author":" Amish",
    "bookImage":"combo29.jpg",
    "bookPrize":"$ 380.00",
    "orginalBookPrize":"$ 990.00",
    "publisher":"Westland  ",
    "relesedDate":" 1 November 2021 ",
    "bookStockDetails":"Available",
    "aboutbook":"RAM – SCION OF IKSHVAKU - He loves his country and he stands alone for the law. His band of brothers, his wife, Sita and the fight against the darkness of chaos. He is Prince Ram. Will he rise above the taint that others heap on him? Will his love for Sita sustain him through his struggle? Will he defeat the demon Raavan who destroyed his childhood? Will he fulfil the destiny of the Vishnu? Begin an epic journey with Amish’s latest: the Ram Chandra Series., SITA – WARRIOR OF MITHILA - An abandoned baby is found in a field. She is adopted by the ruler of Mithila, a powerless kingdom, ignored by all. Nobody believes this child will amount to much. But they are wrong. For she is no ordinary girl. She is Sita. Through an innovative multi-linear narrative, Amish takes you deeper into the epic world of the Ram Chandra Series.  RAAVAN – ENEMY OF ARYAVARTA  - Raavan is determined to be a giant among men, to conquer, plunder, and seize the greatness that he thinks is his right. He is a man of contrasts, of brutal violence and scholarly knowledge. A man who will love without reward and kill without remorse. In this, the third book in the Ram Chandra series, Amish sheds light on Raavan, the king of Lanka. Is he the greatest villain in history or just a man in a dark place, all the time?",
    "aboutAuthor":"AMISH is a 1974-born IIM (Kolkata)-educated, boring banker turned happy author. The success of his debut book, The Immortals of Meluha (Book 1 of the Shiva Trilogy), encouraged him to give up a fourteen-year-old career in financial services to focus on writing. He is passionate about history, mythology and philosophy, finding beauty and meaning in all world religions. Amish’s books have sold more than 5.5 million copies and have been translated into over 19 languages.",
  },
]

}
