import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-cooking',
  templateUrl: './cooking.component.html',
  styleUrls: ['./cooking.component.css']
})
export class CookingComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }
  books: Array<any>=[
    {
      "name":"Masala Dabba",
      "author":" Michael Swamy ",
      "bookImage":"book169.webp",
      "bookPrize":"$ 717.00",
      "orginalBookPrize":"$ 950.00",
      "publisher":" Om Books International ",
      "relesedDate":" 3 September 2018  ",
      "bookStockDetails":"Available",
      "aboutbook":"The Indian kitchen is incomplete without the ‘masala dabba’ or the spice box that comprises a world of flavours, colours and textures. Sometimes, a single spice does the trick, at other times several spices combine to form a robust blend. Here, we explore the ‘masala dabba’ and its contents from a not-so-obvious point of view. What would happen, for instance, if milk masala were not added to milk but meat, or chilli Flakes in desserts? Believe it or not, the answer is: spectacular food. Masala dabba presents a melange of culinary techniques and unique spice blends and Mixtures that would guarantee a delightful dining experience. This book will definitely come in handy while you cook up a storm for your dear ones with a dash of freshness and the goodness of zesty spices.",
      "aboutAuthor":"Chef Michael Swamy is a pioneer in the area of food media and is a chef, food stylist, food writer and travel photographer based in Mumbai, India. A graduate of the prestigious Le Cordon Bleu, London, he has trained under several Michelin chefs. He, with his team, has conceptualised and handled major food shows on several GEC and international niche channels. He has won numerous accolades in the culinary industry. He has authored several cookbooks and is a four-time Gourmand Award winner. As Chef Patron at NUEVA, India’s first Latin American restaurant in Delhi, he set a benchmark for global cuisines. He is currently associated with a leading hospitality university where he has designed a specialised culinary degree. ",
    },
    {
      "name":"Thai Cookery Secrets",
      "author":" Kris Dhillon ",
      "bookImage":"book152.jpg",
      "bookPrize":"$ 800.00",
      "orginalBookPrize":"$ 950.00",
      "publisher":"  Little, Brown Book Group ",
      "relesedDate":"29 Apr 2010   ",
      "bookStockDetails":"Available",
      "aboutbook":"Enjoy delicious Thai food at homeBe the first to write a review on this book Thai Cookery SecretsDiscover how to create delicious Thai dishes using easily available ingredients and with surprisingly little effort. Kris Dhillon explains the basic principles of Thai cooking - fresh, flavoursome ingredients, correctly combined and quickly cooked - so that you can achieve the wonderful flavours Thai cooking is famous for. Many Thai restaurants in the Western world barely capture the true essence of Thai food but Kris shows how you can match the best Thai food from Thailand.Recipes include perfect pad thai, easy stir fries, aromatic soups, Thai tempura, quick vegetarian side dishes like steamed bok choy and garlicky broccolini, and a large variety of curries including the classic Thai green curry.",
      "aboutAuthor":"Kris Dhillon writes with the authority of an accomplished restaurateur. With many years of experience and thousands of satisfied customers she is still flattered by the popularity of her recipes and by the volume of interest and debate they continue to provoke. Her book, The Curry Secret, is widely acknowledged as the Holy Grail of curry cook books.",
     
    },
    {
      "name":"Cooking For Crowds For Dummies",
      "author":"Dawn Simmons",
      "bookImage":"book153.webp",
      "bookPrize":"$ 143.00",
      "orginalBookPrize":"$ 198.00",
      "publisher":" For Dummies ",
      "relesedDate":"10 June 2005   ",
      "bookStockDetails":"Available",
      "aboutbook":"Over 100 recipes, plus time-saving planning tips and sanity-saving suggestions.Panicky about cooking for a casual church dinner, a posh graduation party, or a holiday feast for 50? With terrific recipes plus tips for everything from planning menus to preparation and presentation, you can serve a hungry crowd without getting all steamed up about it. You'll quickly grasp the basics you need to know to cook like an experienced pro.",
      "aboutAuthor":"Dawn is the co-founder and artistic director of the Front Porch Arts Collective, a black theater company committed to advancing racial equity in Boston through theatre. She also founded New Exhibition Room in 2008 to produce provocative, political, and affordable theater events.",
    
    },
    {
      "name":"A Indian HouseWife's Recipe Book",
      "author":"Laxmi Khurana",
      "bookImage":"book154.jpg",
      "bookPrize":"$ 430.00",
      "orginalBookPrize":"$ 527.00",
      "publisher":"Robinson  ",
      "relesedDate":"6 January 2022   ",
      "bookStockDetails":"Available",
      "aboutbook":"Laxmi Khurana is an Indian housewife living in the UK. Her recipes have been handed down to her through the generations, and admired by her family and friends. Here, in her classic curry cookbook, she makes them available to everyone, so you can re-create authentic Indian meals for all the family - from starters to raitas, chutneys and pickles to sweets, as well as the ever popular curries - all with minimum fuss and maximum satisfaction that this is the real thing.• Recipes for traditional 'family' dishes, not normally served in Indian restaurants• Uses ingredients and spices that are widely available• Simple, economical dishes that anyone can makeSome reader reviews:'The recipes are very simple and clear to follow. They produce the best curries I have ever made. The ingredients can all be found easily in any supermarket.''It doesn't require you to pre-prepare 6 basic sauces first. Just pick up the book and cook.''Good, honest and easy everyday cooking for those of us addicted to Indian food.'",
      "aboutAuthor":"Laxmi Khurana is an Indian housewife living in the UK. The recipes which she features in this book have been handed down to her through the generations. Laxmi Khurana is an Indian housewife living in the UK. The recipes which she features in this book have been handed down to her through the generations.Laxmi Khurana is an Indian housewife living in the UK. The recipes which she features in this book have been handed down to her through the generations.",
    },
    {
      "name":"Sweet and Simple Homemade Cakes",
      "author":"Rosalia Ason ",
      "bookImage":"book156.jpg",
      "bookPrize":"$ 330.00",
      "orginalBookPrize":"$ 480.00",
      "publisher":"Worldwide Spark Publish  ",
      "relesedDate":"20 October 2021 ",
      "bookStockDetails":"Available",
      "aboutbook":"BEST COOKING BOOK - 40 sweet and simple recipes!Are you bored of all cooking book and are you looking for something new and different?Sweet and Simple Homemade Cakes: 40 Easy and Delicious Cooking Recipes for a Great Cooking Book, Perfect for Every Occasion, Baking Book!",
      "aboutAuthor":"Rosalía is the singer-songwriter behind the smash hit Con Altura featuring J Balvin and El Guincho, and the Latin Grammy award-winning song, Malamente.",
    },
    {
      "name":"On Food and Cooking ",
      "author":"Harold McGee ",
      "bookImage":"book157.jpg",
      "bookPrize":"$ 1.320.0",
      "orginalBookPrize":"$ 2,093.0",
      "publisher":"Scribner Book Company ",
      "relesedDate":" 23 Nov 2004  ",
      "bookStockDetails":"Available",
      "aboutbook":"A kitchen classic for over 35 years, and hailed by Time magazine as a minor masterpiece when it first appeared in 1984, On Food and Cooking is the bible which food lovers and professional chefs worldwide turn to for an understanding of where our foods come from, what exactly they're made of, and how cooking transforms them into something new and delicious.For its twentieth anniversary, Harold McGee prepared a new, fully revised and updated edition of On Food and Cooking. He has rewritten the text almost completely, expanded it by two-thirds, and commissioned more than 100 new illustrations. As compulsively readable and engaging as ever, the new On Food and Cooking provides countless eye-opening insights into food, its preparation, and its enjoyment.On Food and Cooking pioneered the translation of technical food science into cook-friendly kitchen science and helped birth the inventive culinary movement known as molecular gastronomy. Though other books have been written about kitchen science, On Food and Cooking remains unmatched in the accuracy, clarity, and thoroughness of its explanations, and the intriguing way in which it blends science with the historical evolution of foods and cooking techniques.",
      "aboutAuthor":"Harold James McGee is an American author who writes about the chemistry and history of food science and cooking. He is best known for his seminal book On Food and Cooking: The Science and Lore of the Kitchen first published in 1984 and revised in 2004. Harold James McGee (born October 3, 1951) is an American author who writes about the chemistry and history of food science and cooking. ",
    },

    {
      "name":"The Student Cookbook",
      "author":"Bounty",
      "bookImage":"book159.jpg",
      "bookPrize":"$ 340.00",
      "orginalBookPrize":"$ 590.00",
      "publisher":" Pyramid ",
      "relesedDate":" 16 July 2015  ",
      "bookStockDetails":"Available",
      "aboutbook":"Want on-budget, easy, but delicious recipes? Need to know how to cook after flying the nest to University? Find all the kitchen tip, hints and dishes (and more!) in this super student cookbook.With thousands of young adults leaving home every year, the need to learn how to cook both economically and using limited equipment is essential! Whether it's recreating the perfect roast, whipping up a spag bol or omelette, baking a salmon or just making sure no-one gets food poisoning, the specially created recipes provide all the help required.The perfect size to slide into the suitcase as you wave goodbye.",
      "aboutAuthor":"Bounty is an American author of archeological thrillers. He attended Montclair State University, and received a graduate degree in business administration from Rutgers University. ",
    },
    {
      "name":"Soups",
      "author":" Norma Miller ",
      "bookImage":"book160.jpg",
      "bookPrize":"$ 521.00",
      "orginalBookPrize":"$ 640.00",
      "publisher":"Little, Brown Book Group  ",
      "relesedDate":"  02 Aug 2012  ",
      "bookStockDetails":"Available",
      "aboutbook":"How to make the most of your soup-making machine.More and more of us are discovering how easy it is to create a tasty homemade soup using one of these new appliances. The soups can often be ready in just 30-40 minutes. Here Norma Miller extends the range of recipes included in your instruction booklet to provide a wonderful selection of simple but delicious recipes. You'll soon realize that your soup maker is indispensable.Hints and tips to get the best from your soup makerTasty recipes, quick and easy to makeAdapt your own traditional recipes to your new soup makerThis book contains nearly 100 tasty recipes, all personally tried and tested in the latest soup makers by Norma Miller. Traditional favourites, such as Mulligatawny Soup, Creamy Tomato and Basil Soup, Pea and Ham Soup, and Corn Chowder are here, plus some exciting new contemporary recipes, including Prawn and Saffron Soup with Noodles, Thai Chicken and Red Chilli Soup, and even Chilled Cherry and Almond Soup.",
      "aboutAuthor":"Norma Miller is a successful food writer and author of The Juicing Secret and co-author with Annette Yates of Slow Cooking: Best New Recipes, and the Fresh & Fast series: Meals from the Hob, Meals from the Oven and Meals from the Microwave. She also runs the TasteTalk food consultancy with Annette Yates.",
    },
    {
      "name":"Curries",
      "author":"Rani Alexander ,Kuruvila Chacko, Beena",
      "bookImage":"book166.jpg",
      "bookPrize":"$ 595.00",
      "orginalBookPrize":"$ 970.00",
      "publisher":"DEE BEE INFO PUBLICATIONS  ",
      "relesedDate":"  1 January 2015 ",
      "bookStockDetails":"Available",
      "aboutbook":"Cook just like the housewives of Kerala do, with this collection of 32 recipes of Kerala’s most authentic curries. Handpicked from the recipe books of housewives across the State, the list includes both vegetarian and non-vegetarian curries, with a detailed procedure to help you cook it right in your very first attempt. If you are a connoisseur of Kerala cuisine or a newlywed woman out to surprise your spouse with curries that are full on memories, CURRIES-WHAT KERALA’s HOUSEWIVES COOK, is the cookbook you need in your kitchen.",
      "aboutAuthor":" Rani Alexander (Author), Kuruvila Chacko (Author), Beena (Author), & 1 MorePerfect Recipes has been an important member of my personal kitchen. Its one of the very few comprehensive classic Marathi cookery books which are trendy and relatable The recipes are easy to comprehend and follow with a touch of modern sensibilities.",
    },
    
    {
      "name":"Quick And Easy 30-minute Recipes",
      "author":"Slavka Bodic",
      "bookImage":"book161.jpg",
      "bookPrize":"$ 290.00",
      "orginalBookPrize":"$ 320.00",
      "publisher":"  Kindle Unlimited ",
      "relesedDate":"  6 November 2021 ",
      "bookStockDetails":"Available",
      "aboutbook":"Quick And Easy 30-minute Recipes Everyone Will Love 2 is a the second cookbook with recipes sure to appeal to everyone. No matter your sensibilities, you will find something of interest in the pages of this book! All recipes are very quick and easy - perfect for busy people on our planet of time limitations.There are many wonderful cookbooks out there with recipes that take hours and hours to prepare. We all lead such busy lives these days; we don't have time to spend all day in the kitchen. This book is for everyone who likes their food tasty and fast! ",
      "aboutAuthor":"by Slavka Bodic There are many wonderful cookbooks out there with recipes that take hours and hours to prepare. We all lead such busy lives these days; we don't have time to spend all day in the kitchen. This book is for everyone who likes their food tasty and fast.",
    },
    {
      "name":"AMA ",
      "author":"Betty Hallock ,Josef Centeno",
      "bookImage":"book162.jpg",
      "bookPrize":"$ 1,520.0",
      "orginalBookPrize":"$ 1,690.0",
      "publisher":" Chronicle Books ",
      "relesedDate":"01 Oct 2019   ",
      "bookStockDetails":"Available",
      "aboutbook":"Ama finds inspiration from regional Mexican cuisine and beyond with influences from the American South, Germany, Poland, and Morocco to help you bring more diverse and delicious flavors into your kitchen.Bring big and bold Tex-Mex flavor to the table: Tex-Mex is a delicious, irreverent cuisine that combines the deep traditions of Texan and Mexican cooking. Think meaty stews, breakfast tacos, tres leches cake, crunchy salads, slow-cooked meats, and fresh cocktails--home cooks will learn how to make them all.Bring big and bold Tex-Mex flavor to the table: Tex-Mex is a delicious, irreverent cuisine that combines the deep traditions of Texan and Mexican cooking. Think meaty stews, breakfast tacos, tres leches cake, crunchy salads, slow-cooked meats, and fresh cocktails--home cooks will learn how to make them all.- Organized into chapters by type of food--including breakfast, vegetables, main courses, desserts, and a super nacho party--so it's easy to find your go-to recipe for any occasion.- Presented in a colorful package with more than 100 food and atmospheric photos that are bright, mouthwatering, and truly inspiring.Ama offers a collection of recipes that represents down-home cooking and grilling at its most inspiring. Fans of Taqueria, Tartine, and American Sfoglino will also enjoy the cultural delights found in this Tex-Mex cookbook. ",
      "aboutAuthor":"Josef Centeno is the chef-owner of the Centeno Group, which includes the award-winning restaurants Bäco Mercat, Bar Amá, and more. He is the co-author of the cookbook Bäco. Betty Hallock is a journalist, food writer, and former deputy food editor of the Los Angeles Times. She is the co-author of Bäco. Ren Fuller is a Los Angeles-based food and lifestyle photographer.About the Author: Josef Centeno is the chef-owner of the Centeno Group, which includes the award-winning restaurants Bäco Mercat, Bar Amá, and more. He is the coauthor of the cookbook Bäco and lives in Los Angeles.Betty Hallock is a journalist and food writer, and former deputy food editor of the Los Angeles Times. She is the coauthor of Bäco and lives in Los Angeles. ",
    },
    {
      "name":"The Complete Book of Salt Block Cooking",
      "author":"Ryan Childs ",
      "bookImage":"book163.jpg",
      "bookPrize":"$ 970.00",
      "orginalBookPrize":"$ 1,440.0",
      "publisher":" Sonoma Press ",
      "relesedDate":"12 Apr 2016   ",
      "bookStockDetails":"Available",
      "aboutbook":"Former Chez Panisse Chef Ryan Childs Shows You How To Make The Most of Salt Block Cooking With More Than 100 Simple Recipes.The Complete Book of Salt Block Cooking is your ultimate guide to using your Himalayan salt block to prepare the foods you love in a new way. Perfect as a gift or as an addition to your own kitchen shelf, this accessible cookbook arms you with essential tips and techniques for using the latest must-have kitchen tool.You'll explore a range of recipes to sear, roast, bake, grill, cure, and take your salt block cooking to a whole new level. Start off each chapter with a techniques overview and quick tips before moving on to the variety of versatile recipes, from reinvented classics like burgers and fried eggs to impress-your-guests dishes like Teriyaki-Glazed Salmon. ",
      "aboutAuthor":" Ryan Childs,Take that Himalayan salt block off the shelf and get ready to season, cure and serve like a pro with The Complete Book of Salt Block Cooking. ",
    },
    {
      "name":"The Andhra Cookbook ",
      "author":" Komala Sista Rao",
      "bookImage":"book164.webp",
      "bookPrize":"$ 460.00",
      "orginalBookPrize":"$ 560.00",
      "publisher":"Jaico Publishing House  ",
      "relesedDate":" 2 January 2019  ",
      "bookStockDetails":"Available",
      "aboutbook":"Foreword by Suneeta RaoTraditional Vegetarian Recipes from My Mother’s KitchenKomala Sista Rao, a former singer and mother of pop singer and stage actress Suneeta Rao, presents a compilation of her family’s culinary legacy – well-chosen, delectable vegetarian Andhra home recipes. The Andhra Cookbook breaks stereotypes of Andhra food being all about chillies or too spicy for most palates. Offering recipes with a depth of flavours and several ideas for novices and experts alike, this cookbook will encourage you to relish and experiment with Andhra cooking.With a wide selection of vegetable curries, dals, stews and chutneys, this book provides a keen insight into the region’s cuisine. It can also serve as a well-organised guide that includes detailed explanations about preparation methods and suggested menus to understand how to combine dishes.These recipes carry with them the creativity, labour and love of generations of women in the author’s family, finely crafted and perfected over the years. The excellent food photography inside will help you instantly connect with the rich and delicious world of Andhra cuisines.",
      "aboutAuthor":"Komala Sista Rao was a professional singer in the early 1960’s – a respected name in Hindustani light classical, Bollywood music and an All-India Radio artiste. She married at the age of 23 and moved to Germany, where she lived for ten years, cooking traditional Andhra recipes to preserve the essence of her home, away from home. When she returned to India, her kitchen was always open to friends and family, for whom she cooked just as her mother had done for years. Always serving up the best of meals, she earned a reputation of being a sublime and original cook.",
    },
    {
      "name":"The Essential Kerala Cookbook",
      "author":"Vijayan Kannampilly",
      "bookImage":"book165.jpg",
      "bookPrize":"$ 238.00",
      "orginalBookPrize":"$ 360.00",
      "publisher":"Penguin India  ",
      "relesedDate":" 28 April 2003  ",
      "bookStockDetails":"Available",
      "aboutbook":"India is fortunate to have brilliant culinary traditions within each of its states, with each region providing its own take and twist on popular dishes. The Essential Kerala Cookbook is the a handbook for anyone looking to dwell in the culinary art form from Kerala.The cooking style is traditionally coconut-based, with a healthy dose of spices thrown into the cauldron. This volume includes dishes prepared using vegetable, meats, making pickles, seafood, sweets, and snacks. Specific popular dishes such as tapioca potage, stir-fried banana flower with coconut, deep-fried meat, spicy chicken curry, duck curry, prawns with potato and coconut, and stir-fried crab with coconut have been included.The Essential Kerala Cookbook offers a comprehensive guide to preparing all your favorite Malayali foods. This books was published by Penguin India in 2003 and is available in paperback. Key Features: This books is categorised into specific sections such as vegetarian, meat based dishes, sweets, snacks etc. for easy accessibility.",
      "aboutAuthor":"Vijayan Kannampilly is a renowned journalist from India who has over three decades in the field. He is also an artist and an author who is highly respected for his work thus far. Born in Cochin in 1949, he brings his love for his motherland and his interest in the culinary field to his first book, The Essential Kerala Cookbook. ",

    },

    {
      "name":"The Complete OPOS Cookbook",
      "author":" B Ramakrishnan",
      "bookImage":"book167.webp",
      "bookPrize":"$ 257.00",
      "orginalBookPrize":"$ 410.00",
      "publisher":"HarperCollins India  ",
      "relesedDate":"21 January 2021   ",
      "bookStockDetails":"Available",
      "aboutbook":"Butter chicken in under 6 minutes!Mutton biryani in 12 minutes!Aviyal in 5 minutes!The One Pot One Shot (OPOS) cooking technique is causing a revolution in the kitchen and has garnered a cult following of its own across the globe. OPOS simplifies cooking by deconstructing recipes, doesn't require any fancy equipment or massive prep and is both quick and healthy. Ingredients are layered in a pressure cooker, and the food cooks in its own juices at the highest possible heat in the shortest possible time. The Complete OPOS Cookbook, by culinary pioneer and OPOS inventor B. Ramakrishnan, features entire meal plans spanning regional and international cuisines and includes his bestselling recipes along with new ones.",
      "aboutAuthor":"An MBA from XLRI in Jamshedpur, B. Ramakrishnan is a restless entrepreneur. After eight years of experimentation, the Chennai-based chef and restaurateur believes he has unlocked the pressure cooker's secret to cooking flavourful food. The OPOS technique is the greenest, healthiest, tastiest and fastest way to cook just about anything.The Complete OPOS Cookbook, by culinary pioneer and OPOS inventor B. Ramakrishnan, features entire meal plans spanning regional and international cuisines and includes his bestselling recipes along with new ones.",
    },
    {
      "name":"Macrobiotic Food Cooking",
      "author":"Sylvester Acken ",
      "bookImage":"book158.jpg",
      "bookPrize":"$ 607.00",
      "orginalBookPrize":"$ 745.00",
      "publisher":"  Amazon Digital Services LLC - KDP Print US ",
      "relesedDate":"10 Sep 2021  ",
      "bookStockDetails":"Available",
      "aboutbook":"This book is an appetizing selection of healthy dishes that will bring balance to your diet. From Kelp Noodle Salad to Poached Pears in Apple Cider, there’s plenty included so you can whip up satisfying and energy-boosting snacks and meals. Enjoy! The word macrobiotic derives from the Greek words macros, meaning long, and bios, meaning life. Simply put, macrobiotics refers to foods that are believed to promote health by balancing a person's life energy or Qi over time.This book is an appetizing selection of healthy dishes that will bring balance to your diet. From Kelp Noodle Salad to Poached Pears in Apple Cider, there's plenty included so you can whip up satisfying and energy-boosting snacks and meals. Enjoy! ",
      "aboutAuthor":"by Sylvester Acken,The word macrobiotic derives from the Greek words “macros,” meaning “long,” and “bios,” meaning “life.” Simply put, macrobiotics refers to foods that are believed to promote health by balancing a person’s life energy or Qi over time.",
    },
    {
      "name":"Conquer the Kitchen",
      "author":"Jared Kent",
      "bookImage":"book168.jpg",
      "bookPrize":"$ 648.000",
      "orginalBookPrize":"$ 815.00",
      "publisher":"  ",
      "relesedDate":" 23 May 2022 ",
      "bookStockDetails":"Available",
      "aboutbook":"Written by chef Jared Kent, the book features a comprehensive reference guide that includes measurement conversion charts, a set of basic recipes (pickled vegetables, aioli, vegetable stock, etc), cooking substitutions, a glossary of cooking terms, cooking and baking tips - your go to resource in the kitchen!Much more than just a recipe journal for you to store your favorite recipes, Conquer the Kitchen is your trusted companion as you grill, sauté, fry, and bake up a storm! Neatly file your recipes by using the Table of Recipes at the beginning of the book. With large, 8.5 x 11 inch pages you can also use this blank cookbook as a scrapbook so you can paste in your favorite recipes.BONUS - Get lifetime access to our cooking course, 10 Days to Becoming a Better Cook, hosted by Jared Kent, with the purchase of the book. Every day you'll get a video lesson that will show you how to master a particular cooking technique paired with a healthy and delicious recipe that you can add to your recipe book.",
      "aboutAuthor":"Jared Kent is a professional chef and food writer for Table Matters. Jared started working in restaurants in 2012, and since then, he's been fortunate enough to travel the world and cook in many settings, from Michelin star restaurants to food trucks to sporting events like the Australian Open. A graduate of the esteemed culinary program at Johnson & Wales University, Jared is passionate about creating delicious vegan and vegetarian food to help people, animals, and the planet live better.",
    },
    {
      "name":"Modern Asian Baking at Home ",
      "author":"Kat Lieu",
      "bookImage":"book45.jpg",
      "bookPrize":"$ 1,353.0",
      "orginalBookPrize":"$ 1680.0",
      "publisher":" Quarry Books ",
      "relesedDate":" 21 Jun 2022  ",
      "bookStockDetails":"Available",
      "aboutbook":"From the Subtle Asian Baking community comes Modern Asian Baking at Home, must-have recipes for beloved sweet and savory treats found across Asia.Explore new ingredients, surprising techniques, and interesting textures through lush photography and rewarding recipes that include exciting yet familiar contemporary bakes with innovative Asian twists. The results are unforgettable delights like miso-mochi brownies and spicy gojuchang flourless chocolate cake. There's even a recipe for homemade boba!,This is the perfect cookbook for anyone nostalgic for Asian desserts as well as hobbyist and avid home bakers interested in using vibrant ingredients like miso, matcha, pandan, and soy sauce to expand their repertoires. No passport is needed when you can easily create and experience popular Asian sweets and one-of-a-kind Asian-influenced drinks, custards, cakes, and frozen treats at home.",
      "aboutAuthor":"Kat Lieu is a doctor of physical therapy by day and an avid home baker by night. Originally from New York, she now calls Washington state her home. Lieu is the founder of a popular online baking group called Subtle Asian Baking (SAB). She is known for the Japanese and Basque cheesecake recipes published on her blog, philandmama.com, and Instagram, @subtleasian.baking.",
    },
  ]

}
