import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-rent-section',
  templateUrl: './rent-section.component.html',
  styleUrls: ['./rent-section.component.css']
})
export class RentSectionComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }
  books: Array<any>=[
    {
      "name":"How to Stop Worrying and Start Living ",
      "author":" Dale Carnagie",
      "bookImage":"book82.webp",
      "bookPrize":"$ 133.00",
      "orginalBookPrize":"$ 175.00",
      "publisher":" Gallery Books ",
      "relesedDate":"1 January 1944  ",
      "bookStockDetails":"Available",
      "aboutbook":"Through Dale Carnegie’s six-million-copy bestseller recently revised, millions of people have been helped to overcome the worry habit. Dale Carnegie offers a set of practical formulas you can put to work today. In our fast-paced world—formulas that will last a lifetime.How to Stop Worrying and Start Living is a self-help book by Dale Carnegie. It was first printed in Great Britain in 1948 by Richard Clay, Ltd., Bungay Suffolk. It is currently published as a Mass Market Paperback of 352 pages by Pocket,",
      "aboutAuthor":" Dale Breckenridge Carnegie (originally Carnagey until 1922 and possibly somewhat later) (November 24, 1888 – November 1, 1955) was an American writer and lecturer and the developer of famous courses in self-improvement, salesmanship, corporate training, public speaking and interpersonal skills. Born in poverty on a farm in Missouri, he was the author of How to Win Friends and Influence People, first published in 1936, a massive bestseller that remains popular today. He also wrote a biography of Abraham Lincoln, titled Lincoln the Unknown, as well as several other books.Born in 1888 in Maryville, Missouri, Carnegie was a poor farmer's boy, the second son of James William Carnagey and wife Amanda Elizabeth Harbison (b. Missouri, February 1858 – living 1910.",

    },
    {
      "name":"The Perfect Us ",
      "author":"Durjoy Datta",
      "bookImage":"book81.webp",
      "bookPrize":"$199.00 ",
      "orginalBookPrize":"$230.09 ",
      "publisher":"Penguin Metro Reads  ",
      "relesedDate":"  31 August 2018 ",
      "bookStockDetails":"Available",
      "aboutbook":" Avantika is an investment banker, an ambitious go-getter and the exact opposite of Deb-a corporate professional turned failed writer, turned scripter of saas-bahu serials.They've been together for ten years, surviving everything from college to rave parties to annoying best friends, including Shrey, who has no respect for personal boundaries, and Vernita and Tanmay-the annoying yet enviable 'it' couple who seem to have it all.Now Avantika wants to take the next step. But will Deb be able to catch up? Or will it rip them apart? No matter how hard he tries, Deb can't convince Avantika that he's the one for her. Not as long as she is broken and her past looms in the background-pushing her, troubling her, goading her to question if their love is enough.",
      "aboutAuthor":" Durjoy Datta is an Indian novelist, screenwriter and entrepreneur. He has four shows, Sadda Haq – My Life, My Choice, Million Dollar Girl – From Banaras to Paris on Channel V India, Kuch Rang Pyar Ke Aise Bhi on Sony TV and Ek Veer Ki Ardaas…Veera on Star Plus to his credit.Durjoy Datta is an Indian novelist, screenwriter and entrepreneur. He has four shows, Sadda Haq – My Life, My Choice, Million Dollar Girl – From Banaras to Paris on Channel V India, Kuch Rang Pyar Ke Aise Bhi on Sony TV and Ek Veer Ki Ardaas…Veera on Star Plus to his credit. ",
     
    },
    {
      "name":"Romeo and Juliet ",
      "author":"  William Shakespeare ",
      "bookImage":"book79.jpg",
      "bookPrize":"$ 450.00",
      "orginalBookPrize":"$ 541.00",
      "publisher":"  ",
      "relesedDate":" Jan 1968  ",
      "bookStockDetails":"Available",
      "aboutbook":" Romeo and Juliet is a tragedy written early in the career of playwright William Shakespeare about two young star-cross'd lovers whose deaths ultimately unite their feuding families. It was among Shakespeare s most popular plays during his lifetime and, along with Hamlet and Macbeth, is one of his most frequently performed plays. Today, the title characters are regarded as archetypal young lovers.Romeo and Juliet is a tragedy written by William Shakespeare early in his career about the romance between two Italian youths from feuding families. It was among Shakespeare's most popular plays during his lifetime and, along with Hamlet, is one of his most frequently performed plays. ",
      "aboutAuthor":"William Shakespeare was a renowned English poet, playwright, and actor born in 1564 in Stratford-upon-Avon. His birthday is most commonly celebrated on 23 April (see When was Shakespeare born), which is also believed to be the date he died in 1616.William Shakespeare was a renowned English poet, playwright, and actor born in 1564 in Stratford-upon-Avon. His birthday is most commonly celebrated on 23 April (see When was Shakespeare born), which is also believed to be the date he died in 1616.Shakespeare was a prolific writer during the Elizabethan and Jacobean ages of British theatre (sometimes called the English Renaissance or the Early Modern Period). Shakespeare’s plays are perhaps his most enduring legacy, but they are not all he wrote. "
    
    },
    {
      "name":"Paths of Fear",
      "author":"  Connie Kerbs",
      "bookImage":"book84.webp",
      "bookPrize":"$ 1236.00 ",
      "orginalBookPrize":"$ 1780.00 ",
      "publisher":" F.I.N.E. Reads Press ",
      "relesedDate":" 17 November 2015  ",
      "bookStockDetails":"Available",
      "aboutbook":" Connie Kerbs and Pebbled Lane Books presents this collection of stories, poems, and essays, on a universal theme. Most of all, Paths of Fear is a deeper look at all that fear can teach us and our triumph over it as we find the fortitude to replace it with hope, and determination.Paths of Fear is an inspirational reflection on facing, enduring and overcoming one of the most basic human emotions. Fear. It is an experience we all have at one time or another, to varying degrees. Understanding that the lasting aftershocks can be as devastating as the original traumatic event or fearful season in our life is paramount. Fear is our most primal emotion. It manifests as a scream of sheer terror, an alarm of mortal danger, or a simple cry for help. Sometimes it is silent, imagined, a recipe for our nightmares.      ",
      "aboutAuthor":" Connie Kerbs, aka The Fostering Mom, was an early and ardent student of Language Arts - and still is. She is a prolific writer and intense lover of great poetry. Along with the poetry, she writes fiction, non-fiction, inspirational tales, memoirs, children's stories, ...and everything in between! Her stories and poems have been published several places, and Paths of Fear is the debut title of her Pebbled Lane Books Series, (www.pebbledlanebooks.com). She has several other projects in the works at various stages of publishing progress.Author Connie Kerbs, has been writing stories and poems since gripping that first, wonderful, fat pencil! When she is not writing, she is taking care of her unique family",
    },
    {
      "name":"Believe in yourself ",
      "author":" Joseph Murphy ",
      "bookImage":"book83.webp",
      "bookPrize":"$ 90.00",
      "orginalBookPrize":"$ 126.00",
      "publisher":" Manjul India ",
      "relesedDate":" 1 January 2014  ",
      "bookStockDetails":"Available",
      "aboutbook":"Do you have talents and capabilities that you may not be using to their greatest potential? Do you have dreams you wish to realize? All great accomplishments start with a dream, an idea in the mind of the achiever. In this book, Dr. Murphy shows you how you can make those dreams come true. It starts with developing the right mental attitude—the conviction that you have what it takes. This faith in yourself will enable you to program your subconscious mind to convert your dreams and hopes into achievements. God has given you talents. By developing and using them, you stimulate your conscious mind, which is the motor that energizes the subconscious mind—the engine that will do the work. Within these pages, you will read how poets, artists, inventors, and entrepreneurs implemented their dreams and ideas to become rewarding and profitable accomplishments, and how you can apply the same techniques to enrich your life. ",
      "aboutAuthor":"Murphy was born in Ireland, the son of a private boy's school headmaster and raised a Roman Catholic. He studied for the priesthood and joined the Jesuits. In his twenties, an experience with healing prayer led him to leave the Jesuits and move to the United States, where he became a pharmacist in New York (having a degree in chemistry by that time). Here he attended the Church of the Healing Christ (part of the Church of Divine Science), where Emmet Fox had become minister in 1931. ",
    },
    {
      "name":"Angels Looking Through",
      "author":" Paul Lambillion ",
      "bookImage":"book85webp.webp",
      "bookPrize":"$ 300",
      "orginalBookPrize":"$ 451.00",
      "publisher":" Kindle Edition ",
      "relesedDate":"7 October 2016  ",
      "bookStockDetails":"Available",
      "aboutbook":" People want to believe that when a loved one dies we remain connected through a universal system of love, knowledge and guidance. Paul Lambillion gives us evidence of such connections in his new book, Angels Looking Through.The most remarkable messages in Angels Looking Through come from the many cases of ordinary people Paul shares with us in which he uses the mediumistic abilities he was born with to facilitate conversations that bring greater understanding to the unfinished business left by death—the child who died, the marriage that was never happy but perhaps could have been, or to talk once more with someone much-loved sharing the personal details of what made their relationship precious. Such conversations start a process of healing, alleviation of guilt, or simply bring joy to the heart and confirmation that there is life after death.",
      "aboutAuthor":" Paul Lambillion is a healer and teacher who runs workshops in spiritual awareness in the UK, Switzerland, Austria, Germany and the USA. He also works as an intuitive management consultant and runs a busy private practice in the UK where he lives with his wife and family. Paul Lambillion is a healer, clairvoyant, teacher and lecturer who has worked in a broad range of spiritual and metaphysical fields for over 30 year",
    },
    {
      "name":"The Secret Garden",
      "author":" Frances Hodgson Burnett",
      "bookImage":"book80.webp",
      "bookPrize":"$ 139.00",
      "orginalBookPrize":"$ 175.00",
      "publisher":" Children's Classics ",
      "relesedDate":" 1 September 1998  ",
      "bookStockDetails":"Available",
      "aboutbook":" When orphaned Mary Lennox comes to live at her uncle's great house on the Yorkshire Moors, she finds it full of secrets. The mansion has nearly one hundred rooms, and her uncle keeps himself locked up. And at night, she hears the sound of crying down one of the long corridors. The gardens surrounding the large property are Mary's only escape. Then, Mary discovers a secret garden, surrounded by walls and locked with a missing key. One day, with the help of two unexpected companions, she discovers a way in. Is everything in the garden dead, or can Mary bring it back to life.One of the most delightful and enduring classics of children's literature, The Secret Garden has remained a firm favorite with children the world over ever since it made its first appearance. Initially published as a serial story in 1910 in The American Magazine, it was brought out in novel form in 1911.",
      "aboutAuthor":" Frances Eliza Hodgson was the daughter of ironmonger Edwin Hodgson, who died three years after her birth, and his wife Eliza Boond. She was educated at The Select Seminary for Young Ladies and Gentleman until the age of fifteen, at which point the family ironmongery, then being run by her mother, failed, and the family emigrated to Knoxville, Tennessee. Here Hodgson began to write, in order to supplement the family income, assuming full responsibility for the family upon the death of her mother, in 1870. In 1872 she married Dr. Swan Burnett, with whom she had two sons, Lionel and Vivian. The marriage was dissolved in 1898. In 1900 Burnett married actor Stephen Townsend until 1902 when they got divorced. Following her great success as a novelist, playwright, and children's author, Burnett maintained homes in both England and America, traveling back and forth quite frequently. She died in her Long Island, New York home, in 1924.",
    },
    {
      "name":"Messed Up! But All for Love ",
      "author":"  Arvind Parashar",
      "bookImage":"book88.webp",
      "bookPrize":"$ 175.00",
      "orginalBookPrize":"$ 213.00",
      "publisher":"  ",
      "relesedDate":"  1 May 2017  ",
      "bookStockDetails":"Available",
      "aboutbook": " Neil is a senior executive working with a leading brand name and his wife Gauri is a dentist running her own clinic. They are a loving anddoting young married couple, living a life of comfort in posh suburban Gurgaon. Neil's fitness consultant Srinya seems to be stirring sometrouble in their lives, though.Neil is a senior executive working with a leading brand name and his wife Gauri is a dentist running her own clinic. They are a loving and doting young married couple, living a life of comfort in posh suburban Gurgaon. Neil's fitness consultant Srinya seems to be stirring some trouble in their lives, though. Drishti is a TV news anchor and journalist and her husband Somesh, a top cop. They are bored of their mundane busy lives, until a chance meeting with Neil and his friends in Cuba that changes everything. To add sanity and madness to their lives are the funny and mysterious set of friends - Tom, Jerry, James, Mehr and Antriksha. The havoc ensues when Drishti gets abducted and Neil is framed for it. Gauri finds out some bitter truths and leaves Neil. But what really is the truth? When facts finally surface, we will know how much these lives are Messed Up! But All for Love. ",
      "aboutAuthor":"Arvind Parashar is a corporate-leader-turned-author who hails from the hill station of Dehradun. Having spent his childhood at the foothills of the Himalayas, Arvind always had a creative inclination in life; he used to write and publish songs, poems, stories, etc. during his schooldays.Arvind Parashar hails from a beautiful valley in Northern India, Dehradun, capital of Uttarakhand. He completed his education there and moved places. His corporate stint took him to the U.S several times. Presently, He lives with his family in Mumbai and finds it the best place on earth to live. Apart from writing",
    },
    {
      "name":"Two Indian Girls",
      "author":" Kumar Kinshuk ",
      "bookImage":"book87.webp",
      "bookPrize":"$ 180",
      "orginalBookPrize":"$ 300",
      "publisher":" Kindle Edition ",
      "relesedDate":"15 August 2021 ",
      "bookStockDetails":"Available",
      "aboutbook":"we have two women who are polar opposites in terms of their respective personalities. Yet, Khushboo and Amrita are best friends who always look out for each other. The starting point of the main storyline sees the aftermath of Khushboo’s suicide, and how Amrita’s disbelief and Inspector Rajiv’s suspicion eventually lead them to the haunting truth. Two Indian Girls explores the dynamics of the political situation of Bihar in the recent years,A National Bestseller. Two girls. One crime. A battle for truth ... and survival. Khushbu and Amrita are best friends forever. Khushbu is a simple girl, while Amrita is an upwardly mobile corporate marketing whiz-kid from Mumbai. Khushbu gets engaged. ... ",
      "aboutAuthor":" Kinshuk has written four novels and he has released his latest work in the form of a novella. He has recently published Bariatu Tales, a tale full of anecdotes and vignettes. He has published his series of The Kanke Killings. It is a compendium of 4 novels in the Police Procedurals genral.Kinshuk has written four novels and he has released his latest work in the form of a novella. He has recently published Bariatu Tales, a tale full of anecdotes and vignettes. He has published his series of The Kanke Killings. It is a compendium of 4 novels in the Police Procedurals genre.",
    },
    {
      "name":"Mercy of Gods & Men",
      "author":"Aditya Mathur",
      "bookImage":"book90.webp",
      "bookPrize":"$ 144.00",
      "orginalBookPrize":"$225.00 ",
      "publisher":"pblshng  ",
      "relesedDate":"  30 November 2016 ",
      "bookStockDetails":"Out Of Stock",
      "aboutbook":"down around William when his village is burnt by the prince of the kingdom, he must gather himself to oppose the tyranny of the King. William will have to stand strong in order to avenge all the wrongs that the king and his family have done. Rigolous, on the other hand, has been forced to be crowned the king of his kingdom at the tender age of fourteen. He has also been married to a woman ten years older to him according to the wishes of his dying father. The power in his kingdom truly belongs to the council. As the power of the crown diminishes, he must, along with his wife, struggle to regain control over his kingdom. Oskar is the prince to the kingdom in the north. Having a frail body in a country where strength is everything, Oskar must find a place in this military intensive kingdom and prove his worth to his father with his wits and conviction.Mercy is the story of multiple complex characters that face dire circumstances. Set in three kingdoms, the stories revolves around rebellions, wars and political agendas. Explore the story of these foreign lands as the destiny of the characters unfold over the span of the series.",
      "aboutAuthor":" ",
    },
    {
      "name":"Whispers of Heartache ",
      "author":"Kavya",
      "bookImage":"book91.webp",
      "bookPrize":"$ 161.00",
      "orginalBookPrize":"$ 250.00",
      "publisher":" Writer's Pocket ",
      "relesedDate":"  15 January 2022 ",
      "bookStockDetails":"Available",
      "aboutbook":"A great poetry book for all those who want to experience the beautifully sad emotions that come along with a heartbreak. What letting go feels like, how broken a person can get, how it feels to fall in love with someone, and a lot more. Get this relatable poetry book for gift and the person will surely fall in love with the poems in it. Words are just whispers of the heartache we suffer from, we scream but our screams don't seem to reach others. So maybe, just maybe, if we whisper our holding, our letting go, our falling and our loving, some who listen to silence will hear what we are going through.",
      "aboutAuthor":"A great poetry book for all those who want to experience the beautifully sad emotions that come along with a heartbreak. What letting go feels like, how broken a person can get, how it feels to fall in love with someone, and a lot more. Get this relatable poetry book for gift and the person will surely fall in love with the poems in it.",
    },
    {
      "name":"Wuthering Heights ",
      "author":"  Emily Bronte",
      "bookImage":"book92.webp",
      "bookPrize":"$ 299.00",
      "orginalBookPrize":"$ 361.00",
      "publisher":" S.Chand (G/L) & Company ",
      "relesedDate":"  1 March 2015  ",
      "bookStockDetails":"Available",
      "aboutbook":"At the centre of this novel is the passionate love between Catherine Earnshaw and Heathcliff - recounted with such emotional intensity that a plain tale of the Yorkshire moors acquires the depth and simplicity of ancient tragedy.New to the fourth Edition are twelve of Emily Bronte's letters regarding the publication of the 1847 edition of Wuthering Heights as well as the evolution of the 1850 edition, prose and poetry selections by the author, four reviews of the novel, and poetry selections by the author, four reviews of the novel, and Edward Chitham's insightful and informative chronology of the creative process behind the beloved work.Five major critical interpretations of Wuthering Heights are included, three of them new to the Fourth Edition. A Stuart Daley considers the importance of chronology in the novel. J. Hillis Miller examines Wuthering Heights's problems of genre and critical reputation. Sandra M. Gilbert assesses the role of Victorian Christianity plays in the novel, while Martha Nussbaum traces the novel's romanticism. Finally, Lin Haire-Sargeant scrutinizes the role of Heathcliff in film adaptations of Wuthering Heights. ",
      "aboutAuthor":"Emily Jane Brontë was a British novelist and poet, now best remembered for her only novel Wuthering Heights, a classic of English literature. Emily was the second eldest of the three surviving Brontë sisters, being younger than Charlotte Brontë and older than Anne Brontë. She published under the masculine pen name Ellis Bell.Emily was born in Thornton, near Bradford in Yorkshire to Patrick Brontë and Maria Branwell. She was the younger sister of Charlotte Brontë and the fifth of six children. In 1824, the family moved to Haworth, where Emily's father was perpetual curate, and it was in these surroundings that their literary oddities flourished. In childhood, after the death of their mother, the three sisters and their brother Patrick Branwell Brontë created imaginary lands (Angria, Gondal, Gaaldine, Oceania), which were featured in stories they wrote. Little of Emily's work from this period survived, except for poems spoken by characters (The Brontës' Web of Childhood, Fannie Ratchford, 1941).",
    },
    {
      "name":" One Arranged Murder",
      "author":"Chetan Bhagat",
      "bookImage":"book101.webp",
      "bookPrize":"$ 170.00",
      "orginalBookPrize":"$ 222.00",
      "publisher":"Westland  ",
      "relesedDate":" 28 September 2020  ",
      "bookStockDetails":"Available",
      "aboutbook":" One Arranged Murder is the ninth novel and the twelfth book overall written by the Indian author Chetan Bhagat. The novel is the sequel to Bhagat's 2018 novel The Girl in Room 105.[1] A sequel to the book named 400 Days was released in 2021.Saurabh Maheshwari is engaged to Prerna Malhotra. His wedding is three months away. On the night of Karva Chauth, however, Prerna is murdered after being pushed from her terrace. With Inspector Vijender Singh and aided by ACP Rana, the case is investigated by Saurabh and Keshav Rajpurohit. They interrogate all the people in the family. Prerna has a cousin sister called Anjali, and Keshav falls in love with her. Anjali is revealed to be the killer and is arrested.  ",
      "aboutAuthor":"Chetan Bhagat grew up in a traditional Punjabi Hindu family. His father served as a lieutenant colonel in the Indian Army and his mother worked as a scientist in Indian Agricultural Research Institute, New Delhi. He was schooled at the Army Public School, Dhaula Kuan.[3] He claims to have been an average student at 15.[4][5] His love for writing began during his school years. He used to write articles for the literary magazine of his school and seeing his name printed on the magazine as a writer gave him intense pleasure. This encouraged him to write more in the coming years.Chetan Bhagat is the author of seven novels and two nonfiction books. The New York Times called him the the biggest selling English language novelist in India's history and Time magazine named him among the 100 most influential people in the world. ",
    },
    {
      "name":"The Adventures of Tom Sawyer",
      "author":"Mark Twain",
      "bookImage":"book93.webp",
      "bookPrize":"$ 432.00 ",
      "orginalBookPrize":"$ 498.00",
      "publisher":"  Fingerprint Publishing  ",
      "relesedDate":"1 May 2015 ",
      "bookStockDetails":"Available",
      "aboutbook":" Satirical and nostalgic, Mark Twain’s epic masterpiece, the Adventures of Tom Sawyer, brings out the inequities of adult reality from beneath the innocence of childhood. In the fictional town of St. Petersburg, Missouri, along the Mississippi River, Tom Sawyer lives with his Aunt Polly and half-brother Sid. As the novel begins, we catch him stealing from the jam jar and narrowly escaping being hit. But his life is full of adventurous episodes. What happens as he moves from one escapade to another—accompanying Huckleberry Finn to the graveyard at night where they witness a trio of grave robbers; falling in love with Becky Thatcher and being shunned; enjoying the new found freedom and then being struck by the idea of appearing at his own funeral; hunting for buried treasure in a haunted house with Huck and so on..?The Adventures of Tom Sawyer has been widely adapted into feature films and television series. it is followed by Adventures of Huckleberry Finn.",
      "aboutAuthor":" Lauded as the ‘greatest American humorist of his age’ and called ‘the father of American literature’ by William Faulkner, Samuel Langhorne Clemens, better known by his pen name Mark Twain, was born in Florida, Missouri, in 1835. He authored 28 books and numerous sketches and short stories. in 1839, his family shifted to Hannibal, a developing port city along the banks of river Mississippi, which later provided the setting for the Adventures of Tom Sawyer and its sequel, Adventures of Huckleberry Finn, two of his most remarkable books. the Adventures of Tom Sawyer (1876) features one of the best-loved characters in American fiction. it is suggestive of the life in the towns by the Mississippi river.Mark Twain was awarded an honorary doctorate in letters by the Oxford University in 1907. He died on April 21, 1910 in Redding, Connecticut, after suffering a heart attack.",
    },
    {
      "name":"Color BTS! The Most Beautiful BTS Coloring Book For ARMY",
      "author":" Kpop-Ftw Print",
      "bookImage":"book95.webp",
      "bookPrize":"$ 242.00",
      "orginalBookPrize":"$ 278.00",
      "publisher":" Tee Books ",
      "relesedDate":"  14 June 2021 ",
      "bookStockDetails":"Available",
      "aboutbook":"From the creators of Color BTS! comes a brand new coloring book, Color BTS 2! The Most Beautiful BTS Coloring Book For ARMY. Just like the first, this coloring book is another feast for the eyes and makes a wonderful gift for any BTS fan.Color your favorite KPOP idols, BTS in this book full of beautifully hand-drawn pictures of the boys on every page with their iconic looks from multiple comebacks and eras, all with gorgeous backgrounds surrounding them! This one includes pictures from a brand new era of the boys, from dark angel concepts to the boys at a beautiful banquet. The book is 8.5 x 11 inches, so the pictures are very large and fun to color.",
      "aboutAuthor":"From the creators of Color BTS! comes a brand new coloring book, Color BTS 2! The Most Beautiful BTS Coloring Book For ARMY. Just like the first, this coloring book is another feast for the eyes and makes a wonderful gift for any BTS fan.Color your favorite KPOP idols, BTS in this book full of beautifully hand-drawn pictures of the boys on every page with their iconic looks from multiple comebacks and eras, all with gorgeous backgrounds surrounding them! This one includes pictures from a brand new era of the boys, from dark angel concepts to the boys at a beautiful banquet. The book is 8.5 x 11 inches, so the pictures are very large and fun to color.",

    },
    {
      "name":"November 9 ",
      "author":" Colleen Hoover",
      "bookImage":"book97.jpg",
      "bookPrize":"$ 154.00",
      "orginalBookPrize":"$ 211.00",
      "publisher":" Atria Books ",
      "relesedDate":" 10 November 2015  ",
      "bookStockDetails":"Available",
      "aboutbook":"Fallon meets Ben, an aspiring novelist, the day before her scheduled cross-country move. Their untimely attraction leads them to spend Fallon’s last day in L.A. together, and her eventful life becomes the creative inspiration Ben has always sought for his novel. Over time and amidst the various relationships and tribulations of their own separate lives, they continue to meet on the same date every year. Until one day Fallon becomes unsure if Ben has been telling her the truth or fabricating a perfect reality for the sake of the ultimate plot twist. Beloved #1 New York Times bestselling author Colleen Hoover returns with an unforgettable love story between a writer and his unexpected muse.",
      "aboutAuthor":"Colleen Hoover is an American author who primarily writes novels in the romance and young adult fiction genres. She is best known for her 2016 romance novel It Ends with Us. Many of her works were self-published before being picked up by a publishing house. Hoover sold about 20 million books as of October 2022.",
    },
    {
      "name":"Girl in Room 105",
      "author":" Chetan Bhagat",
      "bookImage":"book98.webp",
      "bookPrize":"$ 128.00",
      "orginalBookPrize":"$ 194.00",
      "publisher":"HarperCollins India  ",
      "relesedDate":" 20 July 2022  ",
      "bookStockDetails":"Available",
      "aboutbook":" The Girl in Room 105 is the eighth novel and the tenth book overall written by the Indian author Chetan Bhagat. The book became a bestseller based on prearranged sales alone. It tells about an IIT coaching class tutor who goes to wish his ex-girlfriend on her birthday and finds her murdered. I’m Keshav, and my life is screwed. I hate my job and my girlfriend left me. Ah, the beautiful Zara. Zara is from Kashmir. She is a Muslim. And did I tell you my family is a bit, well, traditional? Anyway, leave that. Zara and I broke up four years ago. She moved on in life. I didn’t. I drank every night to forget her. I called, messaged, and stalked her on social media. She just ignored me. However, that night, on the eve of her birthday, Zara messaged me. She called me over, like old times, to her hostel room 105. I shouldn’t have gone, but I did… and my life changed forever. This is not a love story. It is an unlove story. From the author of Five Point Someone and 2 States, comes a fast-paced, funny and unputdownable thriller about obsessive love and finding purpose in life against the backdrop of contemporary India.",
      "aboutAuthor":"Chetan Bhagat is the author of seven novels and two nonfiction books. The New York Times called him the the biggest selling English language novelist in India's history and Time magazine named him among the 100 most influential people in the world.Chetan Baghat, a rising star in the contemporary modern Indian literature, is a multitalented personality. He is a novelist, columnist, public speaker and a screenplay writer. His notable works include Five Point Someone, The 3 Mistakes of My Life and 2 States.Most of his literary works address the issues related to Indian youth and their aspirations which earned Baghat status of the youth icon. ",
    },
    {
      "name":"Animal Farm",
      "author":"George Orwell",
      "bookImage":"book94.webp",
      "bookPrize":"$ 331.00",
      "orginalBookPrize":"$ 437.00",
      "publisher":"Signet Classics  ",
      "relesedDate":" 17 August 1945 ",
      "bookStockDetails":"Available",
      "aboutbook":" A farm is taken over by its overworked, mistreated animals. With flaming idealism and stirring slogans, they set out to create a paradise of progress, justice, and equality. Thus the stage is set for one of the most telling satiric fables ever penned –a razor-edged fairy tale for grown-ups that records the evolution from revolution against tyranny to a totalitarianism just as terrible.When Animal Farm was first published, Stalinist Russia was seen as its target. Today it is devastatingly clear that wherever and whenever freedom is attacked, under whatever banner, the cutting clarity and savage comedy of George Orwell’s masterpiece have a meaning and message still ferociously fresh. ",
      "aboutAuthor":" Eric Arthur Blair, better known by his pen name George Orwell, was an English author and journalist. His work is marked by keen intelligence and wit, a profound awareness of social injustice, an intense opposition to totalitarianism, a passion for clarity in language, and a belief in democratic socialism.Orwell produced literary criticism, poetry, fiction and polemical journalism. He is known for the allegorical novella Animal Farm (1945) and the dystopian novel Nineteen Eighty-Four (1949). His non-fiction works, including The Road to Wigan Pier (1937), documenting his experience of working-class life in the industrial north of England, and Homage to Catalonia (1938), an account of his experiences soldiering for the Republican faction of the Spanish Civil War (1936–1939), are as critically respected as his essays on politics, literature, language and culture.",
    }
    
  ]

}
