import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-love-story',
  templateUrl: './love-story.component.html',
  styleUrls: ['./love-story.component.css']
})
export class LoveStoryComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }
  books: Array<any> = [
    {
      "name":"You Can Heal Your Life",
      "author":"Louise Hay",
      "bookImage":"book116.webp",
      "bookPrize":"$ 111.49 ",
      "orginalBookPrize":"$ 176.00",
      "publisher":" Hay House Inc. ",
      "relesedDate":"13 July 2020 ",
      "bookStockDetails":"Available",
      "aboutbook":"You Can Heal Your Life is a 1984 self-help and new thought book by Louise Hay. It was the second book by the author, after Heal Your Body which she wrote at age 60. After Hay appeared on The Oprah Winfrey Show and Donahue in the same week in March 1988, the book appeared on the New York Times Best Seller list, and by 2008, over 35 million copies worldwide had been sold in over 30 languages, becoming the best-selling non-fiction book of all time. The book was also instrumental in the success of her publishing company, Hay House Inc. Due to the book, she is one of the best-selling authors in history, and one of largest selling women authors, after J. K. Rowling, Danielle Steel and Barbara Cartland. Louise’s key message in this powerful work is: If we are willing to do the mental work, almost anything can be healed. Louise explains how limiting beliefs and ideas are often the cause of illness, and how you can change your thinking…and improve the quality of your life.",
      "aboutAuthor":" Louise Hay was born to a poor mother who married Hay's violent stepfather. When she was about five, she was raped by a neighbor. At fifteen she dropped out of high school without a diploma, became pregnant, and on her sixteenth birthday gave up her newborn baby girl for adoption.She moved to Chicago, where she worked in menial jobs, before moving in 1950 to New York. At this point she changed her name and began a career as a fashion model. She was successful at this, working for Bill Blass, Oleg Cassini, and Pauline Trigere.",
     
    },
    {
      "name":"I Too Had A Love Story ",
      "author":"Ravinder Singh",
      "bookImage":"book137.jpg",
      "bookPrize":"$ 128,00",
      "orginalBookPrize":"$ 182.00",
      "publisher":"Penguin Random House  ",
      "relesedDate":"6 November 2013   ",
      "bookStockDetails":"Available",
      "aboutbook":"Debut novel of well-known Indian English writer Ravinder Singh 'I too had a love story was published in 2008 by Shrishti publishers and republished in 2012 by Penguin India. This book has remained in the bestsellers list, even after 6 years of publication. This novel is based on a real life event that happened with Ravinder Singh, the author. This story is about two people Ravin and khushi who are looking forward to get married. Their parents have been pushing them towards getting into an engagement or wedding soon. They sign up on a web matrimonial site and as fate would have it; they meet and fall in love. They decide to get married. Ravin goes to Delhi to meet Khushi and they are very happy. Both the families are very pleased with the relationship and they are about to be engaged. But destiny had other plans. A day before their engagement, something bad happens. Their lives are not the same anymore. Destiny is something we can never change, what we can do is make better choices. After that tragic incident, how do their lives turn out to be? Do they stay together? Are they safe? You will find out all once you finish this captivating tale of love, loss and destiny. In the world we live today, love has got much complicated. This story unravels the concept of love for us in the simplest of manner. Author manages to keep the readers on their toes by maintaining a full arc of narration throughout the book. In the end, readers are left wondering how it feels to lose your love or find one. In the digital world, finding love has changed its ways and maybe keeping them is different as well, but the question remains- Is love the same thing or the concept of us has changed with these ever-evolving generations. What was that incident and how their fate unfolded is a tale which won the hearts of thousands of people across India, making it a bestseller for six years.Former Infosys chief Narayan Murathy had reviewed the book as a sweet, simple and honest tale of modern day love. Buy it at Amazon.in now.",
      "aboutAuthor":"Ravinder Singh is a young Indian author who has written five books of fiction. The first one 'I too had a love story was an adaptation of his real life story. He has a B.Tech and an MBA degree. He worked in Infosys for five years, but later quit becoming a full-time writer. Some of his other works include 'Can Love Happen Twice, ' Your Dreams are Mine Now and 'tell me a story among others.",
    
    },
    {
      "name":"You are the Best Wife",
      "author":"Ajay K Pandey ",
      "bookImage":"book134.jpg",
      "bookPrize":"$ 104.00",
      "orginalBookPrize":"$ 198.00",
      "publisher":" Srishti Publishers & Distributors ",
      "relesedDate":" 23 November 2015  ",
      "bookStockDetails":"Available",
      "aboutbook": " 'You Are The Best Wife: A True Love Story’ is a story about how people find true love and comfort in dissimilarities; about how two people with absolutely different ideologies meet and fall in love. The story revolves around Bhavna and Ajay. Bhavna loves living life for others while Ajay loves living for himself; Bhavna is more spontaneous, never planning the next move and living life with the flow. On the other hand, living life without planning a single move is almost blasphemous to Ajay. Yet, they fall in love; they get married and love changes both of them for good. However, destiny had some other plans for this couple in love; and, midway through their happiness, Bhavna had to resign from life. But does this halt mean the end of love? Written in frank and clear words with generous dosage of humour, 'You Are the Best Wife’ is hailed as a true love story amidst all adversities. It is an inspiring and bittersweet tale of a youth that metamorphoses into a whole new being after being touched by love. ",
      "aboutAuthor":"Ajay K Pandey is currently working with Cognizant, Pune. He grew up aspiring to be a teacher, but destiny landed him in the IT field. Travelling, trekking and reading novels take much of his leisure time. Travelling and meeting new people has taught him about different cultures and people, and makes him wonder how despite all the differences, there is a bond that unites them. Trekking taught him to deal with challenges like a sport. Reading is perhaps what makes him feel alive. Apart from writing, he wants to follow his role model Mother Teresa and make some contribution to the society. His second book is slated to hit the stands early next year.His debut work, You are the Best Wife is based on his life events and lessons. ",
    },
    {
      "name":"Gift Me A New Beginning",
      "author":"Arpit Vageria ",
      "bookImage":"book138.png",
      "bookPrize":"$ 135.00",
      "orginalBookPrize":"$ 268.00",
      "publisher":" Srishti Publishers & Distributors ",
      "relesedDate":" 12 December 2022  ",
      "bookStockDetails":"Available",
      "aboutbook":"Shaurya is a charming eligible bachelor who lives in a luxurious house in Mumbai. Having lost his parents a few years back, he loves his grandfather to bits. He shares a unique fate with his grandfather, though. They both didn’t get the love they deserved.Roshan, a fun-loving old man, breathes in the present, but lives in his past. He treasures his past so much that he has a hard time moving on. ",
      "aboutAuthor":" Arpit Vageria is one of India’s most loved storytellers. He has penned several bestsellers, including You Are My Reason to Smile, Be My Perfect Ending and I Still Think About You.Roshan, a fun-loving old man, breathes in the present, but lives in his past. He treasures his past so much that he has a hard time moving on. ",
    },
    {
      "name":"All I Ever Want Is You",
      "author":"Nikhil Raj ",
      "bookImage":"book139.jpg",
      "bookPrize":"$ 199.00",
      "orginalBookPrize":"$ 241.00",
      "publisher":" Kindle Edition ",
      "relesedDate":" 11 March 2020  ",
      "bookStockDetails":"Available",
      "aboutbook":"Raj and Alisha meet at a family party and fall for each other, later they realise they love each other, but until then, they have drifted apart due to some family drama. ‘All I Ever Want Is You’ is the story of finding love, finding passion, and separation. This is a story that defines love, a journey that leads you to love your loved ones and yourself.Sister is not what I wanted her to be, friendship was not enough, and I couldn't afford to lose her. So, the only way to live with her was by loving her.Love is one of the most stupid things living organisms ever do, and what makes it more stupid is the journey of finding love. This is a new age journey inspired by some real stupidity. This is the story of Raj and Alisha, who travel through the wrecked roads of stupidity, called love. Raj and Alisha meet at a family party and fall for each other, later they realise they love each other, but until then, they have drifted apart due to some family drama. 'All I Ever Want Is You' is the story of finding love, finding passion, and separation. This is a story that defines love, a journey that leads you to love your loved ones and yourself.",
      "aboutAuthor":"Nikhil Raj, the author has always dreamed of a career as a writer and a filmmaker. The 24-year-old aspiring writer and filmmaker is currently working with the esteemed Dainik Bhaskar Group.Nikhil has made various short films. A recent release of his is “The Smiling Rickshawala”. Nikhil happens to be the writer and director of the short film.He has also been the leading man in the short film, ‘Ajeeb Dastaan Hai Yeh’, which secured the seventh rank at an esteemed filmmaking challenge in Delhi. Nikhil had also written the story, screenplay, and dialogues of the film. Other than that, Nikhil also happens to be the Associate Director of the film.Another, big film Nikhil did was ‘8 din ki Farwary’. This was a commercial short film, and Nikhil was appointed as an assistant director in the film. There are many more films, that Nikhil has worked in.Nikhil belongs to a small town in Bihar, called Saran. This is a place where the first president of India belonged to. Nikhil is currently residing in Noida and is expected to graduate by 2021 from the Asian Academy of Film and Television.Nikhil is an excellent writer and his power of imagination has an unparalleled vogue.",
    },
    {
      "name":"It Starts With Us",
      "author":"Colleen Hoover",
      "bookImage":"book140.webp",
      "bookPrize":"$ 110.00",
      "orginalBookPrize":"$199.00 ",
      "publisher":"Simon & Schuster  ",
      "relesedDate":"  18 October 2022 ",
      "bookStockDetails":"Available",
      "aboutbook":"Before It Ends with Us, it started with Atlas. Colleen Hoover tells fan favorite Atlas’s side of the story and shares what comes next in this long-anticipated sequel to the “glorious and touching” (USA TODAY) #1 New York Times bestseller It Ends with Us.Lily and her ex-husband, Ryle, have just settled into a civil coparenting rhythm when she suddenly bumps into her first love, Atlas, again. After nearly two years separated, she is elated that for once, time is on their side, and she immediately says yes when Atlas asks her on a date.Switching between the perspectives of Lily and Atlas, It Starts with Us picks up right where the epilogue for the “gripping, pulse-pounding” (Sarah Pekkanen, author of Perfect Neighbors) bestselling phenomenon It Ends with Us left off. Revealing more about Atlas’s past and following Lily as she embraces a second chance at true love while navigating a jealous ex-husband, it proves that “no one delivers an emotional read like Colleen Hoover” (Anna Todd, New York Times bestselling author).",
      "aboutAuthor":"Colleen Hoover is an American author who primarily writes novels in the romance and young adult fiction genres. She is best known for her 2016 romance novel It Ends with Us. Many of her works were self-published before being picked up by a publishing house. Hoover sold about 20 million books as of October 2022Colleen Hoover is the #1 New York Times and International bestselling author of multiple novels and novellas. She lives in Texas with her husband and their three boys. She is the founder of The Bookworm Box, a non-profit book subscription service and bookstore in Sulphur Springs, Texas.",
    },
    {
      "name":"You Only Live Once:",
      "author":"Stuti Changle",
      "bookImage":"book132.jpg",
      "bookPrize":"$ 128.00",
      "orginalBookPrize":"$ 250.00 ",
      "publisher":" Penguin eBury Press ",
      "relesedDate":" 31 January 2021  ",
      "bookStockDetails":"Available",
      "aboutbook":"You are one person. Aren’t you? But you are not the same for each one of them.Find answers about your own life in this inspiring story reflective of the youth in India. You will join a broken but rising YouTube star Alara, a struggling but hopeful stand-up comedian Aarav, and a psycho but zen beach-shack owner Ricky. Together, take the journey to seek the truth behind the famous singer Elisha’s disappearance somewhere by the deep sea in Goa.What if you ran away from your life today?Twenty years later, three people are looking for you.One is dying to meet you again.The other wishes you had never met them.The third wishes they could have met you at least once.You are one person. Aren't you?What if you ran away from your life today?Twenty years later, three people are looking for you.One is dying to meet you again.The other wishes you had never met them.The third wishes they could have met you at least once.You are one person. Aren't you?",
      "aboutAuthor":"Stuti Changle is a national bestselling author. Her books You Only Live Once and On the Open Road have inspired readers across the country to make a move. Where the Sun Never Sets is her third book.Stuti has a master's degree in management from IMI New Delhi. Stuti quit her job to inspire people by sharing life-changing stories. She made her TV debut in 2019 as a host of the TV series Kar Ke Dikhaenge.Stuti has sailed to the Andamans, camped with Indian jawans in Arunachal Pradesh, scuba-dived in the Indian Ocean, swum with the dolphins in the Mediterranean, floated free for hours in the Atlantic, and wishes to travel the world before she dies. Every year, she spends time in the coastal village of Palolem in Goa. She currently divides her time between India and the US, where she lives with her husband, Kushal Nahata, co-founder and CEO of FarEye.",
    },
    {
      "name":"Falling In Love Again",
      "author":"Ruskin Bond",
      "bookImage":"book141.jpg",
      "bookPrize":"$ 131.00",
      "orginalBookPrize":"$ 202.00",
      "publisher":" Rupa Publications India ",
      "relesedDate":" 1 May 2013  ",
      "bookStockDetails":"Available",
      "aboutbook":"Falling in love is probably the best thing that can happen to a young writer; it gives a certain spontaneity and intensity to his writing. Stories such as ‘The Night Train at Deoli’,Eyes Have It’ and ‘Time Stops at Shamli’, were written when I was in my early twenties, and have stood the test of time quite well. Fifty years after they were written they still turn up in anthologies aimed at both the young and the old.In my thirties I came to live in the hills, and my love stories were now greatly influenced by the world of nature. Thus, ‘Binya Passes By’ and ‘On Fairy Hill’ have a magical, other-worldly feeling about them.",
      "aboutAuthor":"Ruskin Bond's first novel, The Room on the Roof, written when he was seventeen, won the John Llewellyn Rhys Memorial Prize in 1957. Since then he has written several novels (including Vagrants in the Valley, A Flight of Pigeons and Delhi Is Not Far), essays, poems and children's books, many of which have been published by Penguin India. He has also written over 500 short stories and articles that have appeared in a number of magazines and anthologies. He received the Sahitya Akademi Award in 1993 and the Padma Shri in 1999.",
    },
    {
      "name":"Ugly Love",
      "author":"Colleen Hoover",
      "bookImage":"book34.jpg",
      "bookPrize":"$ 135.00",
      "orginalBookPrize":"$ 255.00",
      "publisher":" WMK Store ",
      "relesedDate":" 1 January 2018  ",
      "bookStockDetails":"Available",
      "aboutbook":"From Colleen Hoover, the #1 New York Times bestselling author of It Ends with Us, a heart-wrenching love story that proves attraction at first sight can be messy. When Tate Collins meets airline pilot Miles Archer, she doesn't think it's love at first sight. They wouldn’t even go so far as to consider themselves friends. The only thing Tate and Miles have in common is an undeniable mutual attraction. Once their desires are out in the open, they realize they have the perfect set-up. He doesn’t want love, she doesn’t have time for love, so that just leaves the sex. Their arrangement could be surprisingly seamless, as long as Tate can stick to the only two rules Miles has for her. Never ask about the past. Don’t expect a future. They think they can handle it, but realize almost immediately they can’t handle it at all. Hearts get infiltrated. Promises get broken. Rules get shattered. Love gets ugly.",
      "aboutAuthor":"Colleen Hoover is the #1 New York Times bestselling author of more than twenty-three novels, including It Ends with Us, All Your Perfects, Ugly Love, and Verity. In 2015, Colleen and her family founded a nonprofit called The Bookworm Box, a bookstore and monthly book subscription service that has donated over $1,000,000 to various charities to date. Colleen lives in Texas with her husband and their three boys. For more information, please visit ColleenHoover.com.",
    },
    {
      "name":"Wish I Could Tell You",
      "author":"Durjoy Datta",
      "bookImage":"book142.webp",
      "bookPrize":"$ 135",
      "orginalBookPrize":"$ 250.00",
      "publisher":"Penguin Metro Reads",
      "relesedDate":" 4 October 2019  ",
      "bookStockDetails":"Available",
      "aboutbook":"Can you find yourself after you have lost that special someone? A disillusioned and heartbroken Anusha finds herself in the small world of WeD. Struggling to cope with her feelings and the job of raising money for charity, she reluctantly searches for a worthwhile cause to support.For Ananth, who has been on the opposite side, no life is less worthy, no cause too small to support. Behind them are teams for whom going to extraordinary lengths to save lives is more than a full-time occupation. In front of them is the virtual world of social media-watching, interacting, judging, making choices, and sometimes, saving lives. From the virtual to the real, their lives and that of their families, entangle in a way that moving together is the only solution. They can't escape each other. In this world of complicated relationships, should love be such a difficult ride?",
      "aboutAuthor":"Durjoy Datta was born in New Delhi, and completed a degree in engineering and business management before embarking on a writing career. His first book-Of Course I Love You . . .-was published when he was twenty-one years old and was an instant bestseller. His successive novels-Now That You're Rich . . .; She Broke Up, I Didn't! . . .; Oh Yes, I'm Single! . . .; You Were My Crush . . .; If It's Not Forever . . .; Till the Last Breath . . .; Someone Like You; Hold My Hand; When Only Love Remains; World's Best Boyfriend; The Girl of My Dreams; The Boy Who Loved; The Boy with the Broken Heart and The Perfect Us-have also found prominence on various bestseller lists, making him one of the highest-selling authors in India.",
    },
    {
      "name":"Touch of Eternity",
      "author":"Datta Durjoy",
      "bookImage":"book142.jpg",
      "bookPrize":"$ 119.00",
      "orginalBookPrize":"$ 199.00 ",
      "publisher":"India Penguin Metro Reads  ",
      "relesedDate":"  01 May 2021  ",
      "bookStockDetails":"Available",
      "aboutbook":"Born on the same day and at the same time, Druvan and Anvesha know they are soulmates in every sense of the word. Their parents, however, refuse to accept their 'togetherness' at first and try to tear them apart. Druvan and Anvesha try their best to explain why that cannot happen.In the same timeline, the world has made huge progress in science and some of the first experiments to combine the body and the soul have begun. This is an opportunity for them to prove their love and tell the world that it is love that can make the impossible, possible.Druvan and Anvesha participate in the experiment as if their life depends on it, because it does. The only thing that remains to be seen is, will the dream of a man to control love and life come true? And when the time comes, can one stay true to their soulmate? ",
      "aboutAuthor":"Durjoy Datta was born in New Delhi, and completed a degree in engineering and business management before embarking on a writing career. His first book, Of Course I Love You . . ., was published when he was twenty-one years old and was an instant bestseller. His successive novels have also found prominence on various bestseller lists, making him one of the highest-selling authors in India. Durjoy also has to his credit nine television shows and has written over a thousand episodes for television. He lives in Mumbai.",
    },
    {
      "name":"boThe Girl in the Glass Casek82",
      "author":"Devashish Sardana",
      "bookImage":"book143.jpg",
      "bookPrize":"$ 150.00",
      "orginalBookPrize":"$ 250.00",
      "publisher":" Ebury Press,Random House India Pvt. Ltd ",
      "relesedDate":"  01 May 2022 ",
      "bookStockDetails":"Available",
      "aboutbook":"Simone Singh, assistant superintendent of police, would rather spend her days locking up criminals than apologizing for her lack of social skills. And she refuses to let anyone stand in the way of her pursuit of the Doll Maker, a ruthless serial killer who dresses up little kids as Barbie dolls and displays their bodies in glass cases. But Simone knows that time is running out to piece together the clues as the Doll Maker has made it clear that the killings have only just begun ...Another serial killer, the Clipper, who enjoyed nine years of infamy as India's most notorious butcher, erupts into an all-consuming rage when he is cast aside by the media in favour of the sick new slayer-the Doll Maker. The Clipper turns his fury into blood-soaked revenge to capture the top spot. As corpses start to pile up, Simone fights to maneuver the Doll Maker into a clever trap. But the Clipper is hell-bent on striking first and regaining the crown with his most grisly murder yet.The Girl in the Glass Case is a jaw-dropping psychological crime thriller. If you like determined heroines, nail-biting twists and chilling serial murderers, then you'll love this rollercoaster ride.",
      "aboutAuthor":"Devashish Sardana is the author of the bestselling The Apple, which won the second prize among 5000 entries at the Amazon India Pen-to-Publish Literary Award 2019. He also writes 100-word thrillers on 10x10 Thrills, a blog on both Facebook and Instagram with 1.6 lakh followers. The blog reached over 1.2 crore readers in 2020.Devashish is a small-town boy from India, who grew up with big dreams and an even bigger imagination. After graduating from IIM Ahmedabad, he sharpened his storytelling skills as a brand builder in a Fortune 100 company for over ten years. Devashish lives in Singapore with his wife and college sweetheart, Megha. He flits across the globe selling hope in a jar (beauty creams).",
    },
    {
      "name":"Where the Crawdads Sing",
      "author":"Delia Owens",
      "bookImage":"book144.jpg",
      "bookPrize":"$ 344.00",
      "orginalBookPrize":"$ 499.00",
      "publisher":"  Little, Brown Book Group ",
      "relesedDate":" 12 Dec 2019  ",
      "bookStockDetails":"Available",
      "aboutbook":"Perfect for fans of Barbara Kingsolver and Celeste Ng, Where the Crawdads Sing is at once an exquisite ode to the natural world, a heartbreaking coming-of-age story, and a surprising tale of possible murder.For years, rumors of the “Marsh Girl” haunted Barkley Cove, a quiet fishing village. Kya Clark is barefoot and wild; unfit for polite society. So in late 1969, when the popular Chase Andrews is found dead, locals immediately suspect her.But Kya is not what they say. A born naturalist with just one day of school, she takes life's lessons from the land, learning the real ways of the world from the dishonest signals of fireflies. But while she has the skills to live in solitude forever, the time comes when she yearns to be touched and loved. Drawn to two young men from town, who are each intrigued by her wild beauty, Kya opens herself to a new and startling world—until the unthinkable happens.In Where the Crawdads Sing, Owens juxtaposes an exquisite ode to the natural world against a profound coming of age story and haunting mystery. Thought-provoking, wise, and deeply moving, Owens’s debut novel reminds us that we are forever shaped by the child within us, while also subject to the beautiful and violent secrets that nature keeps.The story asks how isolation influences the behavior of a young woman, who like all of us, has the genetic propensity to belong to a group. The clues to the mystery are brushed into the lush habitat and natural histories of its wild creatures.",
      "aboutAuthor":"Delia Owens is the co-author of three internationally bestselling nonfiction books about her life as a wildlife scientist in Africa—Cry of the Kalahari, The Eye of the Elephant, and Secrets of the Savanna. She has won the John Burroughs Award for Nature Writing and has been published in Nature, The African Journal of Ecology, and International Wildlife, among many others. She currently lives in Idaho, where she continues her support for the people and wildlife of Zambia. Where the Crawdads Sing is her first novel.",
    },
    {
      "name":"Something I Never Told You",
      "author":"Shravya Bhinder",
      "bookImage":"book145.jpg",
      "bookPrize":"$ 150.00",
      "orginalBookPrize":"$ 250.00",
      "publisher":"Penguin ",
      "relesedDate":" 01 Feb 2019",
      "bookStockDetails":"Available",
      "aboutbook":"Ronnie knew that his first crush was way out of his league, and yet he pursued and wooed Adira. Shyly and from a distance in the beginning, and more persuasively later. He couldn't believe it when the beautiful Adira actually began to reciprocate, falling in love with him for his simplicity and honesty.Slowly, as they get close and comfortable with each other, life takes on another hue. From truly magical it becomes routine. There are fights and then making-up sessions-a clash of egos and doubts.",
      "aboutAuthor":"Shravya loves to find hidden stories around her and write novels about them. Formerly a corporate employee, she managed to flee the madness after a few years of boredom to become a full-time writer. She is a sucker for romance and strives to pen down exciting stories.When she is not reading and writing, she is out enjoying nature, playing with her dogs or cooking for her family.She lives in Melbourne with her family, in a house with a barren backyard and a lifetime's collection of books.",

    },
    {
      "name":"A Girl to Remember",
      "author":"Ajay.K. Pandey",
      "bookImage":"book146.jpg",
      "bookPrize":"$ 117.00",
      "orginalBookPrize":"$ 189.00",
      "publisher":" Repro Knowledgcast Ltd ",
      "relesedDate":"  01 Jan 2019  ",
      "bookStockDetails":"Available",
      "aboutbook":"In every angel a demon hides, And in every demon, an angel strides. Neel is a self-proclaimed demon, a slave to his desires, putting at stake even the purest of relationships for it. He lives for himself, takes life as it comes, and considers people who love as emotional fools. When he first sets his eyes on his new landlady, a widow who is eleven years older to him, all he can see is an opportunity. He has a plan to get rich and is working hard to achieve it, until he bumps into Pihu. She is an immature teenager who likes Neel for no apparent reason, and blindly believes that he is the angel who will take away all her life's troubles. Neel hates Pihu for her unexplained obsession, and her being a hindrance in his plan, but her firm resolve to see a good person in him shakes Neel to the core. Will Pihu make a difference? Does inner transformation come to a man who has gone to a point of no return? A Girl to Remember is an emotional roller coaster which will make you believe that confession is the best punishment.",
      "aboutAuthor":"Ajay Pandey, also known as Ajay K. Pandey, is an Indian author of romance novels. His books include You are the Best Wife, You are the Best Friend, A Girl to Remember. His first book was You are the Best Wife.Pandey was born in Uttar Pradesh. He is an engineer of a Pune-based company, Cognizant. His first book as an author was You are the Best Wife which was released in 2015. After the success of this book, he wrote Her Last Wish",
    },
    {
      "name":"Maybe Someday",
      "author":"Colleen Hoover",
      "bookImage":"book147.jpg",
      "bookPrize":"$ 329.00",
      "orginalBookPrize":"$ 521.00",
      "publisher":" Atria Books ",
      "relesedDate":"18 Mar 2014   ",
      "bookStockDetails":"Available",
      "aboutbook":"At twenty-two years old, Sydney is enjoying a great life: She's in college, working a steady job, in love with her wonderful boyfriend, Hunter, and rooming with her best friend, Tori. But everything changes when she discovers that Hunter is cheating on her--and she's forced to decide what her next move should be.Soon, Sydney finds herself captivated by her mysterious and attractive neighbor, Ridge. She can't take her eyes off him or stop listening to the passionate way he plays his guitar every evening out on his balcony. And there's something about Sydney that Ridge can't ignore, either. They soon find themselves needing each other in more ways than one.",
      "aboutAuthor":" Colleen Hoover is the #1 New York Times bestselling author of more than twenty-three novels, including It Ends with Us, All Your Perfects, Ugly Love, and Verity. In 2015, Colleen and her family founded a nonprofit called The Bookworm Box, a bookstore and monthly book subscription service. Colleen lives in Texas with her husband and their three boys. For more information, please visit ColleenHoover.com.",
    },
    {
      "name":"Jaya",
      "author":"Dr. Devdutt Pattanaik ",
      "bookImage":"book148.jpg",
      "bookPrize":"$ 359.00",
      "orginalBookPrize":"$ 468.00",
      "publisher":" Penguin Books India Pvt Ltd  ",
      "relesedDate":" 14 Aug 2010",
      "bookStockDetails":"Available",
      "aboutbook":"High above the sky stands Swarga, paradise, abode of the gods. Still above is Vaikuntha, heaven, abode of God. The doorkeepers of Vaikuntha are the twins, Jaya and Vijaya, both whose names mean ‘victory’. One keeps you in Swarga; the other raises you into Vaikuntha. In Vaikuntha there is bliss forever, in Swarga there is pleasure for only as long as you deserve. What is the difference between Jaya and Vijaya? Solve this puzzle and you will solve the mystery of the Mahabharata. In this enthralling retelling of India’s greatest epic, the Mahabharata, originally known as Jaya, Devdutt Pattanaik seamlessly weaves into a single narrative plots from the Sanskrit classic as well as its many folk and regional variants, including the Pandavani of Chattisgarh, Gondhal of Maharashtra, Terukkuttu of Tamil Nadu, and Yakshagana of Karnataka.Richly illustrated with over 250 line drawings by the author, the 108 chapters abound with little-known details such as the names of the hundred Kauravas, the worship of Draupadi as a goddess in Tamil Nadu, the stories of Astika, Madhavi, Jaimini, Aravan and Barbareek, the Mahabharata version of the Shakuntalam and the Ramayana, and the dating of the war based on astronomical data. With clarity and simplicity, the tales in this elegant volume reveal the eternal relevance of the Mahabharata, the complex and disturbing meditation on the human condition that has shaped Indian thought for over 3000 years.",
      "aboutAuthor":"Devdutt Pattanaik is a doctor who worked in the pharmaceutical and healthcare industry for fifteen years, before turning his passion for mythology into his profession. He has authored over 600 articles and 30 books on the relevance of sacred stories, symbols and rituals in modern times. His books include:",
    },
    {
      "name":"Harry Potter and the Prisoner of Azkaban",
      "author":"J. K. Rowling",
      "bookImage":"book150.jpg",
      "bookPrize":"$341.00",
      "orginalBookPrize":"$ 499.00",
      "publisher":" Bloomsbury Publishing PLC ",
      "relesedDate":" 01 Sep 2014  ",
      "bookStockDetails":"Available",
      "aboutbook":"Harry Potter is lucky to reach the age of thirteen, since he has survived the murderous attacks of the feared Dark Lord on more than one occasion. His hopes for a quiet school term concentrating on Quidditch are dashed, though, when a maniacal mass-murderer escapes from Azkaban, pursued by the soul-sucking Dementors who guard the prison. It’s assumed that Hogwarts is the safest place for Harry to be. But is it his imagination that is making him feel eyes watching him in the dark, and should he be taking Professor Trelawney’s ghoulish predictions seriously?These new editions of the classic and internationally bestselling, multi-award-winning series feature instantly pick-up-able new jackets by Jonny Duddle, with huge child appeal, to bring Harry Potter to the next generation of readers. It’s time to PASS THE MAGIC ON …",
      "aboutAuthor":"Joanne Rowling is an English writer. She achieved cult-status with seven Harry Potter books, The Tales of Beedle The Bard, Fantastic Beasts and Where To Find Them and Quidditch Through The Ages. She has also written two murder mystery novels under the pseudonym of Robert Galbraith.Jo completed her B.A. in French and Classics at the University of Exeter. She was awarded the title of Officer of the Most Excellent Order of the British Empire for her contributions to charity and literature. ",
    }
  ]

}
