import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-fiction',
  templateUrl: './fiction.component.html',
  styleUrls: ['./fiction.component.css']
})
export class FictionComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }
  books: Array<any>=[
    {
      "name":"Paths of Fear",
      "author":" Mrs Connie Kerbs ",
      "bookImage":"book26.jpg",
      "bookPrize":"$ 976.00",
      "orginalBookPrize":"$ 999.00",
      "publisher":"F.I.N.E. Reads Press  ",
      "relesedDate":"  01 Oct 2016  ",
      "bookStockDetails":"Available",
      "aboutbook":"Paths of Fear is a unique anthology which explores that universal and misunderstood experience we call fear. This enjoyable read is part psychological, part informational, and all inspirational. It is largely personal narrative with a sprinkling of poetry and all entertainment. Paths of Fear explores a broad range of fears from that which manifests in screams of sheer terror, to that immobilizing, fear-ridden freeze we all understand. This survey sheds light on that deep, dark discouragement that reminds us of how we might fall short or fail. It exposes furtive beliefs sometimes rooted in us that we, aren't enough; a destructive idea cultivated in toxic environments which erode us from the inside out. Thought-provoking narratives highlight the many faces of fear with the sensitivity and insight of real experience. A wide variety of real-life examples are offered up on how others have dealt with fearful things and fearful places in life. Some of these circumstances have called for a long endurance, with dignity and grace; others required a special kind of strength and defiance. All are examples of facing fear, on one's own terms, inspiring in their own right. This part psychological survey, part self-help, and part spiritual essay spotlights the true antidote to fear - love, of one kind or another. Secularly accessible, but decidedly faith-based, Paths of Fear de-masks the monsters of circumstance and sheds light on some of the darker recesses of life experience. It is a pleasing, poignant reveal of courage, faith, and modern knowledge balanced with age-old wisdom. Paths of Fear encourages us to rely on our best, healthy sense of true self, and a heartfelt love for others. It's a collection to inspire readers down paths of faith and hope and to encourage anyone through trials of fear they must overcome.",
      "aboutAuthor":"About the Author: Indeed... On being blessed with early spiritual experiences: these would be as a conduit between myself and a renewable fountain of faith which has utterly saved me time and again. Indeed, this source of amazing grace ever rescues, revives, and rejuvenates still my soul. On having a grandmother whose upstairs library I perused: it was here I met first the Caldecott and Newbery classics, enduring poets, composers, story-telling icons and literary giants. Indeed, I was irrevocably impressed. On having an antique, script, manual type-writer tossed my way: it defined my tender years. Indeed, it nurtured my budding muse. On being married to my childhood sweetheart for 30(plus) years: I am in awe of our incredible journey together. We have been honed and humbled even as we've been bathed in bliss. I am grateful he has been my faithful, capable - and especially good-humored companion all this time. My admiration and love for him are indescribable. Indeed, words fail to convey such a divine devotion. On being adoptive-foster parents for nearly a quarter of a century: this means bevies of babies and bus-loads of youth of all ages and stages have graced our home, profoundly altering us. With 13 adopted, and three procured the old-fashioned way, indeed, I love and appreciate beyond expression, being honed and owned all this time by these precious people. On all the above and more, my family, dear friends, Walk of Faith, and my writing journey: these have indeed, all made for the savoriest of lives and the ultimate, beautiful mess. It is to my great delight that such a crazy-wonderful menagerie has somehow chosen me! On writing: Indeed, is there anything better than ever growing, changing, and becoming? Is there anything better than that release of tremors that have rumbled inside for eons, as they built up a force to be reckoned with? When they finally find their focus to surge into a tsunami of positive energy that ripples out into the world - to leave its mark. To leave it just a little better place than they might have found it? Indeed. It is not that I found writing. For some-how, some-why, it found and claimed me. It's not even that I am a writer, per say. I am just a vessel in which a small but powerful portion of that endless stream, that fountain of renewable vigor - pours a bit of itself in me for a time. ",
     
    },
    {
      "name":"Kafka On The Shore",
      "author":" Haruki Murakami",
      "bookImage":"book27.jpg",
      "bookPrize":"$ 419.00",
      "orginalBookPrize":"$ 599.00",
      "publisher":"  Vintage Publishing ",
      "relesedDate":" 03 Oct 2005  ",
      "bookStockDetails":"Available",
      "aboutbook":"Alternate cover edition here . Kafka on the Shore , a tour de force of metaphysical reality, is powered by two remarkable characters: a teenage boy, Kafka Tamura, who runs away from home either to escape a gruesome oedipal prophecy or to search for his long-missing mother and sister; and an aging simpleton called Nakata, who never recovered from a wartime affliction and now i Alternate cover edition here . Kafka on the Shore , a tour de force of metaphysical reality, is powered by two remarkable characters: a teenage boy, Kafka Tamura, who runs away from home either to escape a gruesome oedipal prophecy or to search for his long-missing mother and sister; and an aging simpleton called Nakata, who never recovered from a wartime affliction and now is drawn toward Kafka for reasons that, like the most basic activities of daily life, he cannot fathom. Their odyssey, as mysterious to them as it is to us, is enriched throughout by vivid accomplices and mesmerizing events. Cats and people carry on conversations, a ghostlike pimp employs a Hegel-quoting prostitute, a forest harbors soldiers apparently unaged since World War II, and rainstorms of fish (and worse) fall from the sky. There is a brutal murder, with the identity of both victim and perpetrator a riddleyet this, along with everything else, is eventually answered, just as the entwined destinies of Kafka and Nakata are gradually revealed, with one escaping his fate entirely and the other given a fresh start on his own.",
      "aboutAuthor":"Haruki Murakami was born in Kyoto, Japan, in 1949. He grew up in Kobe and then moved to Tokyo, where he attended Waseda University. After college, Murakami opened a small jazz bar, which he and his wife ran for seven years.In 1978 Murakami was in the bleachers of Jingu Stadium watching a baseball game between the Yakult Swallows and the Hiroshima Carp when Dave Hilton, an American, came to bat. According to an oft-repeated story, in the instant that he hit a double, Murakami suddenly realized that he could write a novel. He went home and began writing that night.His first novel, Hear the Wind Sing, won the Gunzou Literature Prize for budding writers in 1979. He followed this success with two sequels, Pinball, 1973 and A Wild Sheep Chase, which all together form “The Trilogy of the Rat.” ",
    
    },
    {
      "name":"Ikigai ",
      "author":" Francesc Miralles,Hector Garcia, Héctor Fracesc García Miralles",
      "bookImage":"book28.jpg",
      "bookPrize":"$ 391.00",
      "orginalBookPrize":"$ 550.00",
      "publisher":"  Cornerstone ",
      "relesedDate":" 07 Sep 2017   ",
      "bookStockDetails":"Available",
      "aboutbook":"Bring Meaning And Joy To All Your Days With The Internationally Bestselling Guide To Ikigai.According To The Japanese, Everyone Has An Ikigai – A Reason For Living. And According To The Residents Of The Japanese Island Of Okinawa – The World’s Longest-living People – Finding It Is The Key To A Happier And Longer Life.Inspiring And Soothing, This Book Will Bring You Closer Bring Meaning And Joy To All Your Days With The Internationally Bestselling Guide To Ikigai.According To The Japanese, Everyone Has An Ikigai – A Reason For Living. And According To The Residents Of The Japanese Island Of Okinawa – The World’s Longest-living People – Finding It Is The Key To A Happier And Longer Life.Inspiring And Soothing, This Book Will Bring You Closer To These Centenarians’ Secrets: How They Leave Urgency Behind Keep Doing What They Love For As Long As Possible Nurture Friendships Live In The Moment Participate In Their Communities And Throw Themselves Into Their Passions. And It Provides Practical Tools To Help You Discover Your Own Personal Ikigai. Because Who Doesn’t Want To Find The Joy In Every Day",
      "aboutAuthor":"I'm the author of several Japanese culture books: The Magic of Japan, Ikigai the Japanese Secret for a Long and Happy Life, The Book of Ichigo Ichie, Shinrinyoku, The Ikigai Journey and A Geek in Japan.I'm the author of several Japanese culture books: The Magic of Japan, Ikigai the Japanese Secret for a Long and Happy Life, The Book of Ichigo Ichie, Shinrinyoku, The Ikigai Journey and A Geek in Japan.I’m the bestselling author of IKIGAI the Japanese Secret to a Long and Happy Life (with Francesc Miralles), The Magic of Japan, Ichigo Ichie, A geek in Japan, and other books. I write about Japanese culture and how its wisdom can help us to lead better lives. I’m truly grateful to all the millions of people who have read my words. For us, writers, our art becomes meaningful when we are read.      ",
    },
    {
      "name":"Overkill ",
      "author":"Sandra Brown",
      "bookImage":"book24.webp",
      "bookPrize":"$ 1,930.0",
      "orginalBookPrize":"$ 2,460.0",
      "publisher":"Grand Central Publishing  ",
      "relesedDate":"  16 Aug 2022 ",
      "bookStockDetails":"Available",
      "aboutbook":"Former Super Bowl MVP quarterback Zach Bridger hasn't seen his ex-wife, Rebecca Pratt, for some time--not since their volatile marriage imploded--so he's shocked to receive a life-altering call about her. Rebecca has been placed on life support after a violent assault, and he--despite their divorce--has medical power-of-attorney. Zach is asked to make an impossible choice: keep her on life support or take her off of it. Buckling under the weight of the responsibility and the glare of public scrutiny, Zach ultimately walks away, letting Rebecca's parents have the final say.Four years later, Rebecca's attacker, Eban--the scion of a wealthy family in Atlanta--gets an early release from prison. The ludicrous miscarriage of justice reeks of favoritism, and Kate Lennon, a brilliant state prosecutor, is determined to put him back behind bars. Rebecca's parents have kept her alive all these years, but if her condition were to change--if she were to die--Eban could be retried on a new charge: murder.It isn't lost on Zach that in order for Eban to be charged with Rebecca's murder, Zach must actually be the one to kill her. He rejects Kate's legal standpoint but can't resist their ill-timed attraction to each other. Eban, having realized the jeopardy he's in, plots to make certain that neither Zach nor Kate lives to see the death of Rebecca--and the end of his freedom. ",
      "aboutAuthor":" Sandra Brown is the author of seventy-three New York Times bestsellers. There are more than eighty million copies of her books in print worldwide, and her work has been translated into thirty-four languages. Four of her books have been made into films. In 2008, the International Thriller Writers named Brown its Thriller Master, the organization's highest honor. She has served as president of Mystery Writers of America and holds an honorary doctorate of humane letters from Texas Christian University. She lives in Texas.",
    },
    {
      "name":"War of Lanka",
      "author":"Amish Tripathi",
      "bookImage":"book25.jpeg",
      "bookPrize":"$ 352.00",
      "orginalBookPrize":"$ 495.00",
      "publisher":"HarperCollins India",
      "relesedDate":" 3 October 2022  ",
      "bookStockDetails":"Available",
      "aboutbook":"Greed. Rage. Grief. Love. Smouldering Tinder, Waiting To Trigger A War.But This War Is Different. This One Is For Dharma. This War Is For The Greatest Goddess Of Them All.Sita Has Been Kidnapped. Defiantly, She Dares Raavan To Kill Her - She'd Rather Die Than Allow Ram To Surrender.Ram Is Beside Himself With Grief And Rage. He Prepares For War. Fury Is His Fuel. Calm Focus, His Guide.Raavan Thought He Was Invincible. He Thought He'd Negotiate And Force A Surrender. Little Did He Know ...The First Three Books Of The Second-fastest-selling Book Series In Indian Publishing History - The Ram Chandra Series - Explore The Individual Journeys Of Ram, Sita And Raavan. In This, The Epic Fourth Book Of The Series, Their Narrative Strands Crash Into Each Other, And Explode In A Slaughterous War.Will Ram Defeat The Ruthless And Fiendish Raavan, Constrained As He Is By The Laws Of Dharma Will Lanka Burn To A Cinder Or Fight Back Like A Cornered Tiger Will The Terrible Costs Of War Be Worth The Victory. ",
      "aboutAuthor":"Amish is a 1974-born, IIM (Kolkata)-educated banker-turned-author. The success of his debut book, The Immortals of Meluha (Book 1 of the Shiva Trilogy), encouraged him to give up his career in financial services to focus on writing. Besides being an author, he is also an Indian-government diplomat, a host for TV documentaries, and a film producer. Amish is passionate about history, mythology and philosophy, finding beauty and meaning in all world religions. His books have sold more than 6 million copies and have been translated into over 20 languages. His Shiva Trilogy is the fastest selling and his Ram Chandra Series the second fastest selling book series in Indian publishing history. You can connect with Amish here: ",
    },
    {
      "name":"The Last Thing He Told Me",
      "author":"Laura Dave",
      "bookImage":"book22.jpg",
      "bookPrize":"$ 1,430.0",
      "orginalBookPrize":"$ 2,350.0",
      "publisher":" Simon & Schuster ",
      "relesedDate":" 04 May 2021  ",
      "bookStockDetails":"Available",
      "aboutbook":"The instant #1 New York Times bestselling mystery and Reese Witherspoon Book Club pick that's captivated more than a million readers about a woman searching for the truth about her husband's disappearance...at any cost.Before Owen Michaels disappears, he smuggles a note to his beloved wife of one year: Protect her. Despite her confusion and fear, Hannah Hall knows exactly to whom the note refers--Owen's sixteen-year-old daughter, Bailey. Bailey, who lost her mother tragically as a child. Bailey, who wants absolutely nothing to do with her new stepmother.As Hannah's increasingly desperate calls to Owen go unanswered, as the FBI arrests Owen's boss, as a US marshal and federal agents arrive at her Sausalito home unannounced, Hannah quickly realizes her husband isn't who he said he was. And that Bailey just may hold the key to figuring out Owen's true identity--and why he really disappeared.Hannah and Bailey set out to discover the truth. But as they start putting together the pieces of Owen's past, they soon realize they're also building a new future--one neither of them could have anticipated.With its breakneck pacing, dizzying plot twists, and evocative family drama, The Last Thing He Told Me is a riveting mystery, certain to shock you with its final, heartbreaking turn. ",
      "aboutAuthor":" Laura Dave is the author of the #1 New York Times bestseller The Last Thing He Told Me, as well as The First Husband, Eight Hundred Grapes, and other novels. She resides in Los Angeles with her family.",
    },
    {
      "name":"The Candy House",
      "author":" Jennifer Egan",
      "bookImage":"book29.jpg",
      "bookPrize":"$ 1,639.0",
      "orginalBookPrize":"$ 2,030.0",
      "publisher":" Scribner Book Company ",
      "relesedDate":"  05 Apr 2022  ",
      "bookStockDetails":"Available",
      "aboutbook":"Named a Most Anticipated Book of the Year by Time, Entertainment Weekly, Vogue, Good Housekeeping, Oprah Daily, Glamour, USA TODAY, Parade, Bustle, San Francisco Chronicle, The Seattle Times, The Boston Globe, Tampa Bay Times, BuzzFeed, Vulture, and many more!From one of the most celebrated writers of our time, a literary figure with cult status, a sibling novel to her Pulitzer Prize- and NBCC Award-winning A Visit from the Goon Squad--an electrifying, deeply moving novel about the quest for authenticity and meaning in a world where memories and identities are no longer private.The Candy House opens with the staggeringly brilliant Bix Bouton, whose company, Mandala, is so successful that he is one of those tech demi-gods with whom we're all on a first name basis. Bix is 40, with four kids, restless, desperate for a new idea, when he stumbles into a conversation group, mostly Columbia professors, one of whom is experimenting with downloading or externalizing memory. It's 2010. Within a decade, Bix's new technology, Own Your Unconscious--that allows you access to every memory you've ever had, and to share every memory in exchange for access to the memories of others--has seduced multitudes. But not everyone.In spellbinding interlocking narratives, Egan spins out the consequences of Own Your Unconscious through the lives of multiple characters whose paths intersect over several decades. Intellectually dazzling, The Candy House is also extraordinarily moving, a testament to the tenacity and transcendence of human longing for real connection, love, family, privacy and redemption. In the world of Egan's spectacular imagination, there are counters who track and exploit desires and there are eluders, those who understand the price of taking a bite of the Candy House. Egan introduces these characters in an astonishing array of narrative styles--from omniscient to first person plural to a duet of voices, an epistolary chapter and a chapter of tweets.If Goon Squad was organized like a concept album, The Candy House incorporates Electronic Dance Music's more disjunctive approach. The parts are titled: Build, Break, Drop. With an emphasis on gaming, portals, and alternate worlds, its structure also suggests the experience of moving among dimensions in a role-playing game. ",
      "aboutAuthor":" Jennifer Egan is the author of six previous books of fiction: Manhattan Beach, winner of the Andrew Carnegie Medal for Excellence in Fiction; A Visit from the Goon Squad, which won the Pulitzer Prize and the National Book Critics Circle Award; The Keep; the story collection Emerald City; Look at Me, a National Book Award Finalist; and The Invisible Circus. Her work has appeared in The New Yorker, Harper's Magazine, Granta, McSweeney's, and The New York Times Magazine. The Candy House is a bold, brilliant imagining of a world that is moments away. Egan takes to stunning new heights her deeply intuitive forays into the darker aspects of our technology-driven, image-saturated culture (Vogue). The Candy House delivers an absolutely extraordinary combination of fierce, exhilarating intelligence and heart.Her website is JenniferEgan.com.",
    },
    {
      "name":"In Five Years",
      "author":"Rebecca Serle",
      "bookImage":"book20.jpg",
      "bookPrize":"$ 669.00",
      "orginalBookPrize":"$ 917.00",
      "publisher":"  Quercus Publishing",
      "relesedDate":" 01 Oct 2020  ",
      "bookStockDetails":"Available",
      "aboutbook":"When Type-A Manhattan lawyer Dannie Kohan is asked this question at the most important interview of her career, she has a meticulously crafted answer at the ready. Later, after nailing her interview and accepting her boyfriend's marriage proposal, Dannie goes to sleep knowing she is right on track to achieve her five-year plan.But when she wakes up, she’s suddenly in a different apartment, with a different ring on her finger, and beside a very different man. The television news is on in the background, and she can just make out the scrolling date. It’s the same night—December 15—but 2025, five years in the future.After a very intense, shocking hour, Dannie wakes again, at the brink of midnight, back in 2020. She can’t shake what has happened. It certainly felt much more than merely a dream, but she isn’t the kind of person who believes in visions. That nonsense is only charming coming from free-spirited types, like her lifelong best friend, Bella. Determined to ignore the odd experience, she files it away in the back of her mind.Brimming with joy and heartbreak, In Five Years is an unforgettable love story that reminds us of the power of loyalty, friendship, and the unpredictable nature of destiny.",
      "aboutAuthor":"Rebecca Serle is the New York Times bestselling author of In Five Years, The Dinner List, and the young adult novels The Edge of Falling and When You Were Mine. Serle also developed the hit TV adaptation Famous in Love, based on her YA series of the same name. She is a graduate of USC and The New School and lives in Los Angeles. Find out more at RebeccaSerle.com.",
    },
    {
      "name":"The Tools ",
      "author":"Phil Stutz,Barry Michels ",
      "bookImage":"book30.jpg",
      "bookPrize":"$ 911.00",
      "orginalBookPrize":"$ 1,430.0",
      "publisher":" Spiegel & Grau ",
      "relesedDate":"21 May 2013   ",
      "bookStockDetails":"Available",
      "aboutbook":"The Tools is a dynamic, results-oriented practice that defies the traditional approach to therapy. Instead of focusing on the past, this groundbreaking method aims to deliver relief from persistent problems and restore control--and hope--to users right away. Every day presents challenges--big and small--that the tools transform into opportunities to bring about bold and dramatic change in your life. These transformative techniques will teach you how to.For years, Phil Stutz and Barry Michels taught these tools to an exclusive patient base of high-powered executives and creative types. Now their revolutionary practice is available to anyone interested in realizing the full range of their potential. Stutz and Michels want to make your life exceptional--in its resiliency, its productivity, and its experience of real happiness.",
      "aboutAuthor":"Phil Stutz graduated from City College in New York and received his MD from New York University. He worked as a prison psychiatrist on Rikers Island and then in private practice in New York before moving his practice to Los Angeles in 1982.Barry Michels has a BA from Harvard, a law degree from University of California, Berkeley, and an MSW from the University of Southern California. He has been in private practice as a psychotherapist in Los Angeles since 1986.  ",
    },
    {
      "name":"Untamed",
      "author":"Glennon Doyle",
      "bookImage":"book21.jpg",
      "bookPrize":"$ 1,930.0",
      "orginalBookPrize":"$ 2,010.0",
      "publisher":"The Dial Press  ",
      "relesedDate":" 10 March 2020  ",
      "bookStockDetails":"Available",
      "aboutbook":"#1 NEW YORK TIMES BESTSELLER • Over two million copies sold! Packed with incredible insight about what it means to be a woman today.”—Reese Witherspoon (Reese’s Book Club Pick)In her most revealing and powerful memoir yet, the activist, speaker, bestselling author, and “patron saint of female empowerment” (People) explores the joy and peace we discover when we stop striving to meet others’ expectations and start trusting the voice deep within us.NAMED ONE OF THE BEST BOOKS OF THE YEAR BY O: The Oprah Magazine • The Washington Post • Cosmopolitan • Marie Claire • Bloomberg • Parade • “Untamed will liberate women—emotionally, spiritually, and physically. It is phenomenal.”—Elizabeth Gilbert, author of City of Girls and Eat Pray LoveThis is how you find yourself.There is a voice of longing inside each woman. We strive so mightily to be good: good partners, daughters, mothers, employees, and friends. We hope all this striving will make us feel alive. Instead, it leaves us feeling weary, stuck, overwhelmed, and underwhelmed. We look at our lives and wonder: Wasn’t it all supposed to be more beautiful than this? We quickly silence that question, telling ourselves to be grateful, hiding our discontent—even from ourselves. For many years, Glennon Doyle denied her own discontent. Then, while speaking at a conference, she looked at a woman across the room and fell instantly in love. Three words flooded her mind: There She Is. At first, Glennon assumed these words came to her from on high. But she soon realized they had come to her from within. This was her own voice—the one she had buried beneath decades of numbing addictions, cultural conditioning, and institutional allegiances. This was the voice of the girl she had been before the world told her who to be. Glennon decided to quit abandoning herself and to instead abandon the world’s expectations of her. She quit being good so she could be free. She quit pleasing and started living. Soulful and uproarious, forceful and tender, Untamed is both an intimate memoir and a galvanizing wake-up call. It is the story of how one woman learned that a responsible mother is not one who slowly dies for her children, but one who shows them how to fully live. It is the story of navigating divorce, forming a new blended family, and discovering that the brokenness or wholeness of a family depends not on its structure but on each member’s ability to bring her full self to the table. And it is the story of how each of us can begin to trust ourselves enough to set boundaries, make peace with our bodies, honor our anger and heartbreak, and unleash our truest, wildest instincts so that we become women who can finally look at ourselves and say: There She Is. Untamed shows us how to be brave. As Glennon insists: The braver we are, the luckier we get.",
      "aboutAuthor":"Author, activist, founder of Together Rising, and host of the We Can Do Hard Things podcast Glennon Doyle is the author of the #1 New York Times bestseller Untamed, a Reese’s Book Club selection, which has sold over two million copies. She is also the author of the #1 New York Times bestseller Love Warrior, an Oprah’s Book Club selection, and Carry On, Warrior. An activist and “patron saint of female empowerment” (People), Glennon hosts the We Can Do Hard Things podcast. She is the founder and president of Together Rising, an all-women-led nonprofit organization that has revolutionized grassroots philanthropy—raising over $30 million for women, families, and children in crisis. Glennon lives in Florida with her wife and three children.“She is a terrific storyteller. . . . Whether discussing her children or the world outside, challenging conformity, confronting misogyny, or standing up to religious bigotry, her goal as a memoirist (and as a person) is to defy expectations and to help others break out of their cultural cages so that everyone can find their own version of humanity. A bracing jolt of honesty from someone who knows what she wants to say and isn’t afraid to say it.”—Booklist (starred review)",
    },
    {
      "name":"HORSE",
      "author":"Geraldine Brooks",
      "bookImage":"book31.jpg",
      "bookPrize":"$ 764.00",
      "orginalBookPrize":"$ 819.00",
      "publisher":" Little, Brown ",
      "relesedDate":"  16 June 2022 ",
      "bookStockDetails":"Available",
      "aboutbook":"Horse is an extraordinary novel of race, war and idealism. It is set partly in pre-Civil War Kentucky, partly in the New York of the 1950s. The story of Lexington, the fastest horse in nineteenth-century America, his black groom, and the white abolitionist who painted him is counterpointed with that of the woman who went on to own the horse's famous painting. Martha Jackson is at the centre of post World War 2's New York art scene, and the social and sexual turbulence of the 1950s. The collision of these two stories takes Geraldine Brooks's fans back to the brilliance of her Pulitzer-Prize winning March, and is her finest novel yet.",
      "aboutAuthor":"Geraldine Brooks is the author of the Pulitzer Prize-winning novel March and the international bestsellers The Secret Chord, Caleb's Crossing, People of the Book, and Year of Wonders. She has also written the acclaimed nonfiction works Nine Parts of Desire and Foreign Correspondence. Born and raised in Australia, Brooks lives in Massachusetts.There's something bordering on the supernatural about Geraldine Brooks. She seems able to transport herself back to earlier time periods, to time travel. Sometimes, reading her work, she draws you so thoroughly into another era that you swear she's actually lived in it. -- Matthew Gilbert ― The Boston Globe",
    },
    {
      "name":"If It's Not Forever It's Not Love",
      "author":"Durjoy Datta",
      "bookImage":"book74.jpg",
      "bookPrize":"$ 170.00",
      "orginalBookPrize":"$ 199.00",
      "publisher":" Penguin Random House India ",
      "relesedDate":" 6 October 2013  ",
      "bookStockDetails":"Available",
      "aboutbook":"When Deb, an author and publisher, survives the bomb blasts at Chandni Chowk, he knows his life is nothing short of a miracle. And though he escapes with minor injuries, he is haunted by that unfortunate day.His feet take him to where the blasts took place. From the burnt remains he discovers a diary. It seems to belong to a dead man who was deeply in love with a girl. As he reads the heartbreaking narrative, he knows that this story must never be left incomplete. Thus begins Deb’s journey with his girlfriend, Avantika and his best friend, Shrey, to hand over the diary to the man’s beloved.",
      "aboutAuthor":"Durjoy Datta’s first book—Of Course I Love You!—was published when he was twenty-one years old and was an instant bestseller. His successive novels—Now That You’re Rich!; She Broke Up, I Didn’t!; Ohh Yes, I Am Single!; You Were My Crush; If It’s Not Forever; Till the Last Breath; Someone Like You; Hold My Hand; When Only Love Remains; World’s Best Boyfriend; Our Impossible Love; and The Girl of My Dreams—have also found prominence on various bestseller lists, making him one of the highest-selling authors in India.",
    },
    {
      "name":"Wish I Could Tell You",
      "author":"Durjoy Datta ",
      "bookImage":"book77.jpg",
      "bookPrize":"$ 176.00",
      "orginalBookPrize":"$ 199.00",
      "publisher":" Penguin Metro Reads ",
      "relesedDate":" 4 October 2019  ",
      "bookStockDetails":"Available",
      "aboutbook":"Can you find yourself after you have lost that special someone? A disillusioned and heartbroken Anusha finds herself in the small world of WeD. Struggling to cope with her feelings and the job of raising money for charity, she reluctantly searches for a worthwhile cause to support.For Ananth, who has been on the opposite side, no life is less worthy, no cause too small to support. Behind them are teams for whom going to extraordinary lengths to save lives is more than a full-time occupation. In front of them is the virtual world of social media-watching, interacting, judging, making choices, and sometimes, saving lives. From the virtual to the real, their lives and that of their families, entangle in a way that moving together is the only solution. They can't escape each other. In this world of complicated relationships, should love be such a difficult ride?",
      "aboutAuthor":"Durjoy Datta was born in New Delhi, and completed a degree in engineering and business management before embarking on a writing career. His first book-Of Course I Love You . . .-was published when he was twenty-one years old and was an instant bestseller. His successive novels-Now That You're Rich . . .; She Broke Up, I Didn't! . . .; Oh Yes, I'm Single! . . .; You Were My Crush . . .; If It's Not Forever . . .; Till the Last Breath . . .; Someone Like You; Hold My Hand; When Only Love Remains; World's Best Boyfriend; The Girl of My Dreams; The Boy Who Loved; The Boy with the Broken Heart and The Perfect Us-have also found prominence on various bestseller lists, making him one of the highest-selling authors in India.Durjoy also has to his credit nine television shows and has written over a thousand episodes for television. He lives in Mumbai. For more updates, you can follow him on Facebook (www.facebook.com/durjoydatta1) or Twitter (@durjoydatta) or mail him at durjoydatta@gmail.com.",
    },
    {
      "name":"A Son of Destiny",
      "author":" Mary Cornelia Francis",
      "bookImage":"book78.jpg",
      "bookPrize":"$ 1,282.0",
      "orginalBookPrize":"$ 1,350.0",
      "publisher":" Forgotten Books ",
      "relesedDate":" 19 October 2018  ",
      "bookStockDetails":"Available",
      "aboutbook":"Excerpt from A Son of Destiny: The Story of Andrew Jackson With the evils of an insufficiently restricted suffrage and our alarming tide of immigration, it is not likely that we shall ever be more than heterogeneous. But, even 50, three great men have welded our history into something like a coherent whole - Washington, Jackson and Lincoln. The second one of this historic trio represents an era but imperfectly known, and that the man and the times may be better understood is the object of this story, in which fiction plays only a necessary part. About the Publisher Forgotten Books publishes hundreds of thousands of rare and classic books. Find more at This book is a reproduction of an important historical work. Forgotten Books uses state-of-the-art technology to digitally reconstruct the work, preserving the original format whilst repairing imperfections present in the aged copy. In rare cases, an imperfection in the original, such as a blemish or missing page, may be replicated in our edition. We do, however, repair the vast majority of imperfections successfully; any imperfections that remain are intentionally left to preserve the state of such historical works.",
      "aboutAuthor":"Cornelia Frances was born on 7 April 1941 in Liverpool, England, UK. She was an actress, known for Home and Away (1988), The Young Doctors (1976) and Sons and Daughters (1982). She was previously married to Michael Eastland. She died on 28 May 2018 in Sydney, New South Wales, Australia.Trained as an actress in England before moving to Australia in 1965. Returned to England to get married before emigrating to Australia permanently in 1970.",

    },
    {
      "name":"All I Ever Want Is You",
      "author":"Nikhil Raj",
      "bookImage":"book73.jpg",
      "bookPrize":"$ 229.00",
      "orginalBookPrize":"$ 280.00",
      "publisher":" Notion Press ",
      "relesedDate":" 8 March 2020  ",
      "bookStockDetails":"Available",
      "aboutbook":"Raj and Alisha meet at a family party and fall for each other, later they realise they love each other, but until then, they have drifted apart due to some family drama. ‘All I Ever Want Is You’ is the story of finding love, finding passion, and separation. This is a story that defines love, a journey that leads you to love your loved ones and yourself.",
      "aboutAuthor":"Nikhil Raj, the author has always dreamed of a career as a writer and a filmmaker. The 22 year old aspiring writer and filmmaker is currently pursuing his graduation in Cinema at the esteemed Asian Academy of Film and Television.Nikhil has made various short films. A Recent release of his is “The Smiling Rickshawala”. Nikhil happens to be the writer and director of the short film.He has also been the leading man in the short film, ‘Ajeeb Dastaan Hai Yeh’, which secured the seventh rank at an esteemed filmmaking challenge in Delhi. Nikhil had also written the story, screenplay and the dialogues of the film. Other than that, Nikhil also happens to be the Associate Director of the film. ",
    },
    {
      "name":"THE MAID",
      "author":"Nita Prose ",
      "bookImage":"book69.jpg",
      "bookPrize":"$ 295.00",
      "orginalBookPrize":"$ 450.00",
      "publisher":" HarperCollins ",
      "relesedDate":"  20 January 2022 ",
      "bookStockDetails":"Available",
      "aboutbook":"‘A smart, riveting, and deliciously refreshing debut’ LISA JEWELL I am your maid. I know about your secrets. Your dirty laundry. But what do you know about me? Molly the maid is all alone in the world. A nobody. She’s used to being invisible in her job at the Regency Grand Hotel, plumping pillows and wiping away the grime, dust and secrets of the guests passing through. She’s just a maid – why should anyone take notice? But Molly is thrown into the spotlight when she discovers an infamous guest, Mr Black, very dead in his bed. This isn’t a mess that can be easily cleaned up. And as Molly becomes embroiled in the hunt for the truth, following the clues whispering in the hallways of the Regency Grand, she discovers a power she never knew was there. She’s just a maid – but what can she see that others overlook?‘Excellent and totally entertaining… the most interesting (and endearing) main character in a long time’ Stephen King ‘A smart, riveting, and deliciously refreshing debut. Prose knows how to pen a murder mystery with tremendous heart’ Lisa Jewell.‘The book’s endearing central character and atmospheric hotel setting make it an escapist pleasure ― a mini-break between the pages’ Sunday Times ",
      "aboutAuthor":"NITA PROSE is a long-time editor, serving many bestselling authors and their books.She lives in Toronto, Canada, in a house that is only moderately clean.Nita Prose is a longtime editor, serving many bestselling authors and their books. She lives in Toronto, Canada, in a house that is only moderately clean. Visit her at nitaprose.com or on Twitter: @NitaProse.",
    },
    {
      "name":"Something I Never Told You",
      "author":"Shravya Bhinder",
      "bookImage":"book76.webp",
      "bookPrize":"$ 167.00",
      "orginalBookPrize":"$ 280.00",
      "publisher":" Penguin ",
      "relesedDate":" 14 February 2019  ",
      "bookStockDetails":"Available",
      "aboutbook":"When in love, you tend to take each other for granted, and sometimes, that can cost you a lifetime of togetherness . . .Ronnie knew that his first crush was way out of his league, and yet he pursued and wooed Adira. Shyly and from a distance in the beginning, and more persuasively later. He couldn't believe it when the beautiful Adira actually began to reciprocate, falling in love with him for his simplicity and honesty. Slowly, as they get close and comfortable with each other, life takes on another hue. From truly magical it becomes routine. There are fights and then making-up sessions-a clash of egos and doubts.Things begin to change for the worst.It is too late.Ronnie and Adira will probably never find their forever after . . .",
      "aboutAuthor":"Shravya loves to find hidden stories around her and write novels about them. Formerly a corporate employee, she managed to flee the madness after a few years of boredom to become a full-time writer. She is a sucker for romance and strives to pen down exciting stories.When she is not reading and writing, she is out enjoying nature, playing with her dogs or cooking for her family.She lives in Melbourne with her family, in a house with a barren backyard and a lifetime's collection of books.",
    }
  ]

}
