import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-favorite',
  templateUrl: './favorite.component.html',
  styleUrls: ['./favorite.component.css']
})
export class FavoriteComponent implements OnInit {
  constructor() { }

  ngOnInit(): void {
  }
  books: Array<any>=[
    {
      "name":"The Value of a Whale",
      "author":"Adrienne Buller ",
      "bookImage":"book41.jpg",
      "bookPrize":"$ 321.00",
      "orginalBookPrize":"$ 389.00",
      "publisher":"Manchester University Press  ",
      "relesedDate":"  19 July 2022 ",
      "bookStockDetails":"Available",
      "aboutbook":"Public understanding of, and outcry over, the dire state of the climate and environment is greater than ever before. Parties across the political spectrum claim to be climate leaders, and overt denial is on the way out. Yet when it comes to slowing the course of the climate and nature crises, despite a growing number of pledges, policies and summits, little ever seems to change. Nature is being destroyed at an unprecedented rate. We remain on course for a catastrophic 3°C of warming. What's holding us back?In this searing and insightful critique, Adrienne Buller examines the fatal biases that have shaped the response of our governing institutions to climate and environmental breakdown, and asks: are the ‘solutions’ being proposed really solutions? Tracing the intricate connections between financial power, economic injustice and ecological crisis, she exposes the myopic economism and market-centric thinking presently undermining a future where all life can flourish. The book examines what is wrong with mainstream climate and environmental governance, from carbon pricing and offset markets to 'green growth', the commodification of nature and the growing influence of the finance industry on environmental policy. In doing so, it exposes the self-defeating logic of a response to these challenges based on creating new opportunities for profit, and a refusal to grapple with the inequalities and injustices that have created them. Both honest and optimistic, The Value of a Whale asks us ― in the face of crisis ― what we really value.",
      "aboutAuthor":"Adrienne Buller is a Senior Fellow at Common Wealth, a progressive think tank focused on building a democratic economy. Her research and writing have featured in The Guardian, The Financial Times, Bloomberg, and The New Statesman, among others. She is the co-author of Owning the Future (Verso, 2022).",
     
    },
    {
      "name":"The Little Book of Hermès",
      "author":" Karen Homer",
      "bookImage":"book42.jpg",
      "bookPrize":"$ 849.00",
      "orginalBookPrize":"$ 936.00",
      "publisher":"Welbeck Pub Group Ltd  ",
      "relesedDate":" 12 Jul 2022  ",
      "bookStockDetails":"Available",
      "aboutbook":"Little Book of Hermès tells the story of the evolution of the House of Hermès, through beautiful illustrations of the most coveted items and authoritative text by fashion historian Karen Homer.The iconic bags, the instantly recognizable packaging, the celebrity fans – Hèrmes is the last word in luxurious accessories.Through the generations, Hermès have created innovative and exquisite accessories for the most glamorous customers. From their nineteenth-century saddlery workshop to 1960s Paris and beyond, Hermès has graced the arms and wardrobes of style icons from Grace Kelly and Jane Birkin to Victoria Beckham and Kim Kardashian. Little Book of Hermès tells the story of the evolution of the House of Hermès, through beautiful illustrations of the most coveted items and authoritative text by fashion historian Karen Homer.",
      "aboutAuthor":"Karen Homer is an established fashion journalist who worked as a fashion columnist for The Times and has contributed to the Telegraph, Harpers & Queen, Elle, World of Interiors and Vogue. She is the author of the Little Book of Dior and Things a Woman Should Know About Style. She lives in London.",
    
    },
    {
      "name":"Looking for Alaska",
      "author":"Jhon Green",
      "bookImage":"book40.jpg",
      "bookPrize":"$ 669.00",
      "orginalBookPrize":"$ 917.00",
      "publisher":"  Harper Collins India Ltd  ",
      "relesedDate":" 28 Feb 2013  ",
      "bookStockDetails":"Available",
      "aboutbook":"“If people were rain, I was drizzle and she was a hurricane.Gorgeous, clever and undoubtedly screwed-up, Alaska draws Miles into her reckless world and irrevocably steals his heart. For Miles, nothing can ever be the same again.‘Looking for Alaska’ brilliantly captures the exquisite painful joy of living and loving. Poignant, funny, heartbreaking and compelling, this novel will stay with you forever.The unmissable first novel from bestselling and award-winning author of THE FAULT IN OUR STARS and TURTLES ALL THE WAY DOWN.",
      "aboutAuthor":"John Green is an award-winning, New York Times bestselling author who has received numerous accolades including the Printz Medal, a Printz Honor and the Edgar Award. John is also one half of the Vlogbrothers; co-creator, with his brother, Hank, of the popular video blog Brotherhood 2.0, which has been watched more than 30 million times by Nerdfighter fans all over the globe (youtube.com/vlogbrothers).",
    },
    {
      "name":"Long Winter",
      "author":"Laura Ingalls Wilder ",
      "bookImage":"book39.jpg",
      "bookPrize":"$ 339.00",
      "orginalBookPrize":"$ 513.00",
      "publisher":" Egmont UK Ltd ",
      "relesedDate":"  30 Jul 2015 ",
      "bookStockDetails":"Available",
      "aboutbook":"When a blizzard cuts the town of De Smet off from the railroad, the community is left for weeks without food or fuel deliveries and the Ingalls family are forced to eke out the last of their supplies. As the terrible winter drags on, things begin to look desperate, until Almanzo Wilder and his friend brave the icy storms in search of help.The Long Winter is an autobiographical children's novel written by Laura Ingalls Wilder and published in 1940, the sixth of nine books in her Little House series. It is set in southeastern Dakota Territory during the severe winter of 1880–1881, when she turned 14 years old.On the empty winter prairie, gray clouds to the northwest meant only one thing: a blizzard was seconds away. The first blizzard came in October. It snowed almost without stopping until April. The temperature dropped to forty below. Snow reached the roof-tops. And no trains could get through with food and coal. The townspeople began to starve. The Ingalls family barely lived through that winter. And Almanzo Wilder knew he would have to risk his life to save the town.",
      "aboutAuthor":"Laura Elizabeth Ingalls Wilder was an American writer, mostly known for the Little House on the Prairie series of children's books, published between 1932 and 1943, which were based on her childhood in a settler and pioneer family.Ingalls wrote a series of historical fiction books for children based on her childhood growing up in a pioneer family. She also wrote a regular newspaper column and kept a diary as an adult moving from South Dakota to Missouri, the latter of which has been published as a book.",
    },
    {
      "name":"Sooley",
      "author":"John Grisham",
      "bookImage":"book38.webp",
      "bookPrize":"$ 477.00",
      "orginalBookPrize":"$ 698.00",
      "publisher":" Doubleday Books  ",
      "relesedDate":" 27 April 2021  ",
      "bookStockDetails":"Available",
      "aboutbook":"New York Times bestselling author John Grisham takes you to a different kind of court in his first basketball novel. Samuel 'Sooley' Sooleymon is a raw, young talent with big hoop dreams...and even bigger challenges off the court.In the summer of his seventeenth year, Sam­uel Sooleymon gets the chance of a lifetime: a trip to the United States with his South Sudanese teammates to play in a showcase basket­ball tournament. He has never been away from home, nor has he ever been on an airplane. The opportunity to be scouted by dozens of college coaches is a dream come true.Samuel is an amazing athlete, with speed, quick­ness, and an astonishing vertical leap. The rest of his game, though, needs work, and the American coaches are less than impressed.During the tournament, Samuel receives dev­astating news from home: A civil war is raging across South Sudan, and rebel troops have ran­sacked his village. His father is dead, his sister is missing, and his mother and two younger brothers are in a refugee camp.Samuel desperately wants to go home, but it's just not possible. Partly out of sympathy, the coach of North Carolina Central offers him a scholar­ship. Samuel moves to Durham, enrolls in classes, joins the team, and prepares to sit out his freshman season. There is plenty of more mature talent and he isn't immediately needed.Gripping and moving, Sooley showcases John Grisham's unparalleled storytelling powers in a whole new light. This is Grisham at the top of his game. ",
      "aboutAuthor":"John Grisham is the author of forty-seven consecutive #1 bestsellers, which have been translated into nearly fifty languages. His recent books include The Judge's List, Sooley, and his third Jake Brigance novel, A Time for Mercy, which is being developed by HBO as a limited series.Grisham is a two-time winner of the Harper Lee Prize for Legal Fiction and was honored with the Library of Congress Creative Achievement Award for Fiction.When he's not writing, Grisham serves on the board of directors of the Innocence Project and of Centurion Ministries, two national organizations dedicated to exonerating those who have been wrongfully convicted. Much of his fiction explores deep-seated problems in our criminal justice system.",
    },
    {
      "name":"Twisted Love",
      "author":" Ana Huang ",
      "bookImage":"book35.jpg",
      "bookPrize":"$ 349.00",
      "orginalBookPrize":"$ 454.00",
      "publisher":"Indy Pub   ",
      "relesedDate":" 22 Apr 2021  ",
      "bookStockDetails":"Available",
      "aboutbook":"Twisted Love is a brother's best friend/opposites attract romance with a hint of suspense. It's book one in the Twisted series but can be read as a standalone.He Has A Heart Of Ice...But For Her, He'D Burn The World.Alex Volkov Is A Devil Blessed With The Face Of An Angel And Cursed With A Past He Can'T Escape.Driven By A Tragedy That Has Haunted Him For Most Of His Life, His Ruthless Pursuits For Success And Vengeance Leave Little Room For Matters Of The Heart.But When He'S Forced To Look After His Best Friend'S Sister, He Starts To Feel Something In His Chest: A Crack.A Melt.A Fire That Could End His World As He Knew It.Ava Chen Is A Free Spirit Trapped By Nightmares Of A Childhood She Can'T Remember.But Despite Her Broken Past, She'S Never Stopped Seeing The Beauty In The World...Twisted Love Is A Brother'S Best Friend/Opposites Attract Romance With A Hint Of Suspense. It'S Book One In The Twisted Series But Can Be Read As A Standalone.Warning: This Book Contains A Jealous/Possessive Antihero, Explicit Sexual Content, And Profanity. Recommended For 18+.",
      "aboutAuthor":"Ana Huang is an author of primarily steamy New Adult and contemporary romance. Her stories range from lighthearted to dark, but they all have HEAs with plenty of banter and swoon sprinkledAna Huang is a 24-year-old Florida native who is currently based in Washington, D.C. As the daughter of Chinese-American immigrants, she had to take ESOL (English for Speakers of Other Languages) classes in kindergarten.",
    },
    {
      "name":"You Are a Badass",
      "author":" Jen Sincero",
      "bookImage":"book37.webp",
      "bookPrize":"$ 374.00",
      "orginalBookPrize":"$ 501.00",
      "publisher":"Running Press Adult   ",
      "relesedDate":" 23 Apr 2013  ",
      "bookStockDetails":"Available",
      "aboutbook":"Packed with humor, inspiration, and advice, You Are a Badass is the #1 New York Times bestselling self-help book that teaches you how to get better without getting busted.YOU ARE A BADASS IS THE SELF-HELP BOOK FOR PEOPLE WHO DESPERATELY WANT TO IMPROVE THEIR LIVES BUT DONT WANT TO GET BUSTED DOING IT. In This Refreshingly Entertaining How-to Guide, Bestselling Author And World-traveling Success Coach, Jen Sincero, Serves Up 27 Bitesized Chapters Full Of Hilariously Inspiring Stories, Sage Advice, Easy Exercises, And The Occasional Swear Wor YOU ARE A BADASS IS THE SELF-HELP BOOK FOR PEOPLE WHO DESPERATELY WANT TO IMPROVE THEIR LIVES BUT DONT WANT TO GET BUSTED DOING IT. In This Refreshingly Entertaining How-to Guide, Bestselling Author And World-traveling Success Coach, Jen Sincero, Serves Up 27 Bitesized Chapters Full Of Hilariously Inspiring Stories, Sage Advice, Easy Exercises, And The Occasional Swear Word, Helping You To: - Identify And Change The Self-sabotaging Beliefs And Behaviours That Stop You From Getting What You Want. - Create A Life You Totally Love. And Create It NOW - Make Some Damn Money Already. The Kind Youve Never Made Before. By The End Of You Are A Badass, Youll Understand Why You Are How You Are, How To Love What You Cant Change, How To Change What You Dont Love, And How To Use The Force To Kick Some Serious Ass.",
      "aboutAuthor":"Jen Sincero is a #1 New York Times bestselling author, speaker, and success coach who has helped countless people transform their personal and professional lives via her newsletters, products, seminars, public appearances, and books. A few years ago, Jen said goodbye to her home in California in order to travel the world indefinitely and encourages as many people as possible to live lives of unbridled awesomeness. You can find out more, and sign up for her newsletter at jensincero.com.",
    },
    {
      "name":"Upgrade",
      "author":" Blake Crouch",
      "bookImage":"book43.jpg",
      "bookPrize":"$ 400.00",
      "orginalBookPrize":"$ 478.00",
      "publisher":"12 July 2022  ",
      "relesedDate":"  Ballantine Books  ",
      "bookStockDetails":"Available",
      "aboutbook":"The mind-blowing new thriller from the New York Times bestselling author of Dark Matter and Recursion.At first, Logan Ramsay isn’t sure if anything’s different. He just feels a little . . . sharper. Better able to concentrate. Better at multitasking. Reading a bit faster, memorizing better, needing less sleep.But before long, he can’t deny it: Something’s happening to his brain. To his body. He’s starting to see the world, and those around him—even those he loves most—in whole new ways.The truth is, Logan’s genome has been hacked. And there’s a reason he’s been targeted for this upgrade. A reason that goes back decades to the darkest part of his past, and a horrific family legacy.Worse still, what’s happening to him is just the first step in a much larger plan, one that will inflict the same changes on humanity at large—at a terrifying cost.Intimate in scale yet epic in scope, Upgrade is an intricately plotted, lightning-fast tale that charts one man’s thrilling transformation, even as it asks us to ponder the limits of our humanity—and our boundless potential.",
      "aboutAuthor":"Blake Crouch is a bestselling novelist and screenwriter. He is the author of the forthcoming novel, Dark Matter, for which he is writing the screenplay for Sony Pictures. His international-bestselling Wayward Pines trilogy was adapted into a television series for FOX, executive produced by M. Night Shyamalan, that was Summer 2015’s #1 show. With Chad Hodge, Crouch also created Good Behavior, the TNT television show starring Michelle Dockery based on his Letty Dobesh novellas. He has written more than a dozen novels that have been translated into over thirty languages and his short fiction has appeared in numerous publications including Ellery Queen and Alfred Hitchcock Mystery Magazine. Crouch lives in Colorado with his family.",
    },
    {
      "name":"Milk and Honey",
      "author":"Rupi Kaur ",
      "bookImage":"book36.webp",
      "bookPrize":"$ 274.00",
      "orginalBookPrize":"$ 499.00",
      "publisher":" Andrews McMeel Publishing ",
      "relesedDate":" 06 Oct 2015  ",
      "bookStockDetails":"Available",
      "aboutbook":"Milk and Honey is an Indian-Canadian collection of both abstract fiction and non-fiction poetry and prose by Rupi Kaur.Rupi Kaur is the Writer of the Decade-The New Republic,#1 New York Times bestseller milk and honey is a collection of poetry and prose about survival. About the experience of violence, abuse, love, loss, and femininity.The book is divided into four chapters, and each chapter serves a different purpose. Deals with a different pain. Heals a different heartache. milk and honey takes readers through a journey of the most bitter moments in life and finds sweetness in them because there is sweetness everywhere if you are just willing to look.",
      "aboutAuthor":"About the Author: RUPI KAUR is a poet, artist, and performer. As a 21-year-old university student Rupi wrote, illustrated, and self-published her first poetry collection, milk and honey. Next came its artistic sibling, the sun and her flowers. These collections have sold over 10 million copies and have been translated into over 40 languages. Her latest collection, home body, debuted #1 on bestseller lists across the world. As she has done in all things from the very beginning, Rupi self-produced Rupi Kaur Live, the first poetry special of its kind, which debuted on Amazon Prime Video in 2021. Rupi's work touches on love, loss, trauma, healing, femininity, and migration. She feels most at home when creating art, performing her poetry onstage, and spending time with family and friends.",
    },
    {
      "name":"Protect Your Light",
      "author":"George Lizos ",
      "bookImage":"book44.jpg",
      "bookPrize":"$ 1225.0",
      "orginalBookPrize":"$ 1450.0",
      "publisher":"Hampton Roads Publishing Company ",
      "relesedDate":"  01 Jul 2022  ",
      "bookStockDetails":"Available",
      "aboutbook":"A powerful guide to managing your energy in these changing modern times. Covering everything from clearing your energy field to protecting your energy online, this book is a powerful guide to energy protection that you will return to again and again. --Rebecca Campbell, bestselling author of Light Is the New Black.Protect Your Light introduces a modern, comprehensive, step-by-step system of clearing, shielding, and strengthening your energy. It's the first book to address energy attack on social media, empowering readers with practical methods for protecting their energy online.Energy protection is the art of being energetically authentic. It is about managing your energy interactions with the surrounding world to ensure that your thoughts, emotions, and behavior are aligned with your purpose and authenticity, rather than being influenced by external energy sources. Essentially, energy protection ensures that what's ours is ours and what's theirs is theirs.Protect Your Light empowers readers with a toolkit of tried-and-tested energy protection processes for identifying and clearing energy attachments from their energy field, along with shielding processes that repel and transmute energy attacks, while also strengthening the natural energetic defenses. ",
      "aboutAuthor": "George Lizos is a spiritual teacher and intuitive healer, passionate about helping lightworkers to follow their purpose of creating positive change in the world. He’s the #1 bestselling author of Lightworkers Gotta Work and Be The Guru, creator of Intuition Mastery School®, and host of The Lit Up Lightworker Podcast.George has been named one of the top-50 health and wellness influencers by Health Blog Awards, and his work has been featured in Soul & Spirit, Watkin’s Mind Body Spirit, and Kindred Spirit magazines. He holds bachelor’s and master’s degrees in Metaphysical Sciences, a BSc in Human Geography with a focus on sacred geographies, an MSc in Psychology, and is a priest of Greek Paganism.Based in Cyprus, George runs a thriving, online international community of empaths, lightworkers, and spiritual leaders within the Your Spiritual Toolkit Facebook group. There, he provides daily guidance and holds transformational workshops aimed at overcoming the blocks that keep us stuck and prevent us from fearlessly following our purpose. ",
    },
    {
      "name":"God's Road to Financial Freedom",
      "author":" Billy Epperhart ",
      "bookImage":"book46.jpg",
      "bookPrize":"$ 745.00",
      "orginalBookPrize":"$ 1023.00",
      "publisher":" Harrison House ",
      "relesedDate":"  21 Jun 2022  ",
      "bookStockDetails":"Available",
      "aboutbook":"Many Christians are aware that God wants them blessed, but they do not understand how to walk in that blessing. For example, the average American household earns $79,000 but faces a staggering $145,000 in debt!.Jesus warns us about becoming a slave to money. However, most people only think about the danger that presents to the wealthy. On the contrary, Jesus knew that worrying about money is a major way people become slaves to it (Matthew 6:24-27).Financial freedom gives you the time, resources, and headspace to fully devote yourself to God's calling for your life. MBA and serial entrepreneur Billy Epperhart lays out easy-to-implement, God-given power tools to help you make your money work for you, such as:7 steps to financial freedom,7 attitudes you need to excel in building wealth,How to live on 80% and invest 20% to build wealth.",
      "aboutAuthor":"About the Author: Billy Epperhart is a successful entrepreneur, investor, and a nationally known speaker and author. He is the CEO of Andrew Wommack Ministries and Charis Bible College, as well as the co-founder of the Charis Business School. In addition, he oversees the strategic direction of his nonprofit, WealthBuilders, which provides financial and spiritual education to help people make sense of making money for making a difference. The missional arm of WealthBuilders, Tricord Global, provides microfinance loans and business training in developing nations.",
    },
    {
      "name":"Rizzoli & Isles: Listen to Me",
      "author":"Tess Gerritsen ",
      "bookImage":"book47.jpg",
      "bookPrize":"$ 590.00",
      "orginalBookPrize":"$ 850.00",
      "publisher":"Random House Publishing Group  ",
      "relesedDate":"05 Jul 2022  ",
      "bookStockDetails":"Available",
      "aboutbook":"NATIONAL BESTSELLER - Rizzoli & Isles are back! From New York Times bestselling author Tess Gerritsen, this 'shocking and fast-paced' (Karin Slaughter) thriller has Jane and Maura investigating a brutal murder with dire implications, and this time, with Jane's intrepid mother, Angela, looking into a mystery of her own.Boston homicide detective Jane Rizzoli and medical examiner Maura Isles are newly plagued by what seems like a completely senseless murder. Sofia Suarez, a widow and nurse who was universally liked by her neighbors, lies bludgeoned to death in her own home. But anything can happen behind closed doors, and Sofia seemed to have plenty of secrets in her last days, making covert phone calls to traceless burner phones. When Jane finally makes a connection between Sofia and the victim of a hit-and-run from months earlier, the case only grows more blurry. What exactly was Sofia involved in? One thing is clear: The killer will do anything it takes to keep their secret safe.Meanwhile, Angela Rizzoli hasn't had a decent night's sleep in all the years since her daughter became a homicide detective. Maybe the apple didn't fall too far from the tree: Nothing in Angela's neighborhood gets by her--not the gossip about a runaway teenager down the block and definitely not the strange neighbors who have just moved in across the street. Angela's sure there's no such thing as coincidence in her sleepy suburb. If only Jane would listen--instead she writes off Angela's concerns as the result of an overactive imagination. But Angela's convinced there's a real wolf in her vicinity, and her cries might now fall on deaf ears.With so much happening on the Sofia case, Jane and Maura already struggle to see the forest for the trees, but will they lose sight of something sinister happening much closer to home?",
      "aboutAuthor":"Bestselling author Tess Gerritsen is also a physician, and she brings to her novels her first-hand knowledge of emergency and autopsy rooms. Her thrillers featuring homicide detective Jane Rizzoli and medical examiner Maura Isles inspired the hit TV series Rizzoli & Isles. But Gerritsen's interests span far more than medicine and crime. As an anthropology student at Stanford University, she catalogued centuries-old human remains, and she continues to travel the world, driven by her fascination with ancient cultures and bizarre natural phenomena.",
    },
    {
      "name":"The Secret of the Science of Getting Rich",
      "author":"Sandy Gallagher, Bob Proctor",
      "bookImage":"book48.jpg",
      "bookPrize":"$ 1,110.0",
      "orginalBookPrize":"$ 1,530.00",
      "publisher":"G&D Media  ",
      "relesedDate":"21 Jun 2022   ",
      "bookStockDetails":"Available",
      "aboutbook":"So often we make the mistake of committing our lives and our time to empty activities - with only small glimpses of satisfaction and fulfillment.Getting rich is an exact science. There are certain laws that govern it, and once you learn and comply with those laws, getting rich is a mathematical certainty.Bob Proctor has been studying the mind, paradigms, and the universal laws of money for over 57 years. There is no one better than Bob to teach you the secret behind the Wallace Wattles book, The Science of Getting Rich. He is able to reduce the most complicated concepts from that classic into its simplest form. And better yet, Bob will give you many practical ways you can apply the concepts to your life--starting today. But first, you must believe that you can attract anything you want in life.Discover your purpose and then apply the actual science behind The Science of Getting Rich. Bob Proctor will share the secret to wealth so you can get unstuck and achieve continual forward momentum towards your dreams. ",
      "aboutAuthor":"Sandy Gallagher As an esteemed attorney with a successful career in banking law, Sandy regularly handled billions of dollars in mergers and acquisitions, IPOs, and other big-ticket transactions, and was an advisor to boards and top executives of Fortune 500 firms. She epitomized success in the classic corporate mold.Bob Proctor was a Canadian self-help author and lecturer. He was best known for his New York Times best-selling book You Were Born Rich and being a contributor to the film The Secret.",
    },
    {
      "name":"The Science of Getting Rich with The Science of Being Great",
      "author":" Wallace D. Wattles Edited, Modernized, and Updated for the 21st Century by Arthur R. Pell, Ph.D.",
      "bookImage":"book49.jpg",
      "bookPrize":"$ 90.00",
      "orginalBookPrize":"$ 150.00",
      "publisher":"Fingerprint! Publishing  ",
      "relesedDate":" 01 Sep 2019  ",
      "bookStockDetails":"Available",
      "aboutbook":"The Science of Getting Rich is a book written by the New Thought Movement writer Wallace D. Wattles and published in 1910 by the Elizabeth Towne Company. The book is still in print. According to USA Today, the text is divided into 17 short, straight-to-the-point chapters that explain how to overcome mental barriers, and how creation, rather than competition, is the hidden key to wealth attraction.This book is based on the Hindu philosophies that One is All, and that All is One (Page one of Preface). The Science of Getting Rich is based upon what Wattles called the Certain Way of Thinking.According to Mitch Horowitz,",
      "aboutAuthor":"“YOU CAN BECOME WHAT YOU WANT TO BE.” A combined, modernized, and updated edition of Wallace D. Wattles’ two bestselling works, The Science of Getting Rich and The Science of Being Great, this book is considered a philosophy of Mind Science. With time-tested New Thought principles and practices, including the technique of creative visualization, which Wattles himself practiced, it explains how riches come to us and how by simply using our will, acting in a certain way, and thinking the right thoughts, we can become rich and great. A compelling self-help classic, this book will help you understand the secrets to attaining what you truly desire. ",

    },
    {
      "name":"Sea of Tranquility ",
      "author":" Emily St John Mandel",
      "bookImage":"book32.jpg",
      "bookPrize":"$ 1,210.0",
      "orginalBookPrize":"$ 2,250",
      "publisher":"  Diversified Publishing ",
      "relesedDate":" 17 May 2022  ",
      "bookStockDetails":"Available",
      "aboutbook":"NEW YORK TIMES BEST SELLER - WINNER OF THE GOODREADS CHOICE AWARD - The award-winning, best-selling author of Station Eleven and The Glass Hotel returns with a novel of art, time travel, love, and plague that takes the reader from Vancouver Island in 1912 to a dark colony on the moon five hundred years later, unfurling a story of humanity across centuries and space.One of the Best Books of the Year: The New York Times, NPR, GoodReads.Edwin St. Andrew is eighteen years old when he crosses the Atlantic by steamship, exiled from polite society following an ill-conceived diatribe at a dinner party. He enters the forest, spellbound by the beauty of the Canadian wilderness, and suddenly hears the notes of a violin echoing in an airship terminal--an experience that shocks him to his core. When Gaspery-Jacques Roberts, a detective in the black-skied Night City, is hired to investigate an anomaly in the North American wilderness, he uncovers a series of lives upended: The exiled son of an earl driven to madness, a writer trapped far from home as a pandemic ravages Earth, and a childhood friend from the Night City who, like Gaspery himself, has glimpsed the chance to do something extraordinary that will disrupt the timeline of the universe.  ",
      "aboutAuthor":"EMILY ST. JOHN MANDEL's five previous novels include The Glass Hotel and Station Eleven, which was a finalist for a National Book Award and the PEN/Faulkner Award for Fiction, has been translated into thirty-two languages, and is the basis for the HBO Max series by the same name. She lives in New York City with her husband and daughter.",
    },
    {
      "name":"The Cartographers",
      "author":"Peng Shepherd ",
      "bookImage":"book33.jpg",
      "bookPrize":"$ 610.00",
      "orginalBookPrize":"$ 875.00",
      "publisher":" HarperCollins ",
      "relesedDate":" 15 Mar 2022  ",
      "bookStockDetails":"Available",
      "aboutbook":"The Cartographers is one of those brilliant books you have to read twice.-- Washington PostFrom the critically acclaimed author of The Book of M, a highly imaginative thriller about a young woman who discovers that a strange map in her deceased father's belongings holds an incredible, deadly secret--one that will lead her on an extraordinary adventure and to the truth about her family's dark history.Nell Young's whole life and greatest passion is cartography. Her father, Dr. Daniel Young, is a legend in the field and Nell's personal hero. But she hasn't seen or spoken to him ever since he cruelly fired her and destroyed her reputation after an argument over an old, cheap gas station highway map.But when Dr. Young is found dead in his office at the New York Public Library, with the very same seemingly worthless map hidden in his desk, Nell can't resist investigating. To her surprise, she soon discovers that the map is incredibly valuable and exceedingly rare. In fact, she may now have the only copy left in existence...because a mysterious collector has been hunting down and destroying every last one--along with anyone who gets in the way. ",
      "aboutAuthor":"Peng Shepherd is the nationally bestselling author of The Cartographers, The Book of M, and The Future Library.Her second novel, The Cartographers, was a USA Today bestseller, a national Independent Bookstores bestseller, and was named a Best Book of March by The Washington Post, as well as a Pick of the Month by Good Morning America, Amazon, Apple, Real Simple, Buzzfeed, Bustle, and Goodreads, and was featured on NPR’s Weekend Edition.Her first novel, The Book of M, won the 2019 Neukom Institute for Literary Arts Award for Debut Speculative Fiction, and was chosen as a Best Book of the Year by Amazon, Elle, Refinery29, and The Verge, a Best Book of the Summer by the Today Show and NPR On Point, and has been optioned for television.She was born and raised in Phoenix, Arizona, where she rode horses and trained in classical ballet, and has lived in Beijing, Kuala Lumpur, London, Los Angeles, Washington, D.C., New York, and Mexico City.",
    },
    {
      "name":"Ugly Love",
      "author":"Colleen Hoover",
      "bookImage":"book34.jpg",
      "bookPrize":"$ 135.00",
      "orginalBookPrize":"$ 255.00",
      "publisher":" WMK Store ",
      "relesedDate":" 1 January 2018  ",
      "bookStockDetails":"Available",
      "aboutbook":"From Colleen Hoover, the #1 New York Times bestselling author of It Ends with Us, a heart-wrenching love story that proves attraction at first sight can be messy. When Tate Collins meets airline pilot Miles Archer, she doesn't think it's love at first sight. They wouldn’t even go so far as to consider themselves friends. The only thing Tate and Miles have in common is an undeniable mutual attraction. Once their desires are out in the open, they realize they have the perfect set-up. He doesn’t want love, she doesn’t have time for love, so that just leaves the sex. Their arrangement could be surprisingly seamless, as long as Tate can stick to the only two rules Miles has for her. Never ask about the past. Don’t expect a future. They think they can handle it, but realize almost immediately they can’t handle it at all. Hearts get infiltrated. Promises get broken. Rules get shattered. Love gets ugly.",
      "aboutAuthor":"Colleen Hoover is the #1 New York Times bestselling author of more than twenty-three novels, including It Ends with Us, All Your Perfects, Ugly Love, and Verity. In 2015, Colleen and her family founded a nonprofit called The Bookworm Box, a bookstore and monthly book subscription service that has donated over $1,000,000 to various charities to date. Colleen lives in Texas with her husband and their three boys. For more information, please visit ColleenHoover.com.",
    }
  ]

}
