import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-poetry',
  templateUrl: './poetry.component.html',
  styleUrls: ['./poetry.component.css']
})
export class PoetryComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }
  books: Array<any> = [
    {
      "name":"Moonrise and Memories",
      "author":"Navaneel Kar ",
      "bookImage":"book170.jpg",
      "bookPrize":"$ 263.00",
      "orginalBookPrize":"$ 340.00",
      "publisher":"  Paperback  ",
      "relesedDate":" 22 November 2021  ",
      "bookStockDetails":"Available",
      "aboutbook":"Moonrise and Memories is an eclectic collection of modern poems on diverse themes like Life, Friendship, Love, Mindfulness, Nature, and Inspiration. The poems are an expression of my inner journey through life and its magical moments. The poems have a theme of mindfulness and meditativeness running through the compositions. The book wishes to inspire readers to take a stop in their busy lives and reflect on smaller things around us, which seem insignificant and yet, are so meaningful. To live every moment with higher consciousness and awareness. The poems speak of love & nostalgia on one hand and deriving inspiration from life on the other hand. The longer poems tell stories from imaginary days past. The poems on nature are reflections on the wonder of this beautiful world.  Moonrise and Memories is your ideal companion to reflect and ruminate on, on a beautiful morning with your chai, or during the monsoon as you watch the rain fall, or on moonlit nights when you watch the full moon and fall in love once again. The poems are nothing special, just outpourings of our own heart put into words by me.",
      "aboutAuthor":"Navaneel Kar is a Indian poem writer The poems speak of love & nostalgia on one hand and deriving inspiration from life on the other hand. The longer poems tell stories from imaginary days past. The poems on nature are reflections on the wonder of this beautiful world.  Moonrise and Memories is your ideal companion to reflect and ruminate on, on a beautiful morning with your chai, or during the monsoon as you watch the rain fal",
     
    },
    {
      "name":"The Book of Nature",
      "author":"William Wordsworth",
      "bookImage":"book171.jpg",
      "bookPrize":"$ 445.00",
      "orginalBookPrize":"$ 530.00",
      "publisher":"Read Books  ",
      "relesedDate":"20 February 2020   ",
      "bookStockDetails":"Available",
      "aboutbook":"Along with many other Romantic poets of the time, the theme of nature features heavily in the work of Wordsworth - to him, it represented a living thing, a sublime teacher-god that contained all beauty and divine truth. Wordsworth expresses his view on the natural world through the poetry in this charming collection while articulating his relationship with nature and its essential connection with human beings.Carefully curated by Read & Co. Books, this collection of twenty-one poems also features an introductory excerpt on William Wordsworth by Thomas Carlyle from his 1881 work Reminiscences. The perfect gift for poetry readers and nature lovers alike, this beautiful pocket edition is a wonderful book of posey for those who love reading on the go.      ",
      "aboutAuthor":"William Wordsworth (1770 -1850) was born in Cockermouth, England, and was part of the famous Lake Poets group. Wordsworth was the United Kingdom's Poet Laureate from 1843 until his death. He is best-known for his collection of poems, Lyrical Ballads, that he wrote and published with his friend and fellow Lake Poet, Samuel Taylor Coleridge. The seminal collection helped to set England's Romantic Era in motion.",
    
    },
    {
      "name":"Poetry Will Save Your Life",
      "author":"Jill Bialosky",
      "bookImage":"book172.jpg",
      "bookPrize":"$ 930.00",
      "orginalBookPrize":"$ 1.350.0",
      "publisher":"Reprint  ",
      "relesedDate":" 2 October 2018  ",
      "bookStockDetails":"Available",
      "aboutbook":"From a critically acclaimed New York Times bestselling author and poet comes “a delightfully hybrid book: part anthology, part critical study, part autobiography” (Chicago Tribune) that is organized around fifty-one remarkable poems by poets such as Robert Frost, Emily Dickinson, Wallace Stevens, and Sylvia Plath.For Jill Bialosky, certain poems stand out like signposts at pivotal moments in a life: the death of a father, adolescence, first love, leaving home, the suicide of a sister, marriage, the birth of a child, the day in New York City the Twin Towers fell. As Bialosky narrates these moments, she illuminates the ways in which particular poems offered insight, compassion, and connection, and shows how poetry can be a blueprint for living. In Poetry Will Save Your Life, Bialosky recalls when she encountered each formative poem, and how its importance and meaning evolved over time, allowing new insights and perceptions to emerge.While Bialosky’s personal stories animate each poem, they touch on many universal experiences, from the awkwardness of girlhood, to crises of faith and identity, from braving a new life in a foreign city to enduring the loss of a loved one, from becoming a parent to growing creatively as a poet and artist. Each moment and poem illustrate “not only how to read poetry, but also how to love poetry” (Christian Science Monitor). ",
      "aboutAuthor":"Jill Bialosky is the author of four acclaimed collections of poetry. Her poems have appeared in The New Yorker, The New York Times, and The Atlantic, among others. She is the author of several books, including History of a Suicide, Asylum, and Poetry Will Save Your Life. In 2015, Jill was honored by the Poetry Society of America for her distinguished contribution to the field of poetry. She lives in New York City. Find out more at JillBialosky.com. “Poetry Will Save Your Life is one of the most moving memoirs I’ve ever read, but it’s so much more. Bialosky does something miraculous: as she shares stories from her life, she shows how specific poems can help all of us make sense of our own lives and the world. Here are classic and contemporary poems that help us see and hear one another more clearly; that speak to us in times of loss and grief; that guide us through our every days. If you’ve always loved poetry, this book will captivate you. And if you want to love poetry, then this book will open worlds. Poetry Will Save Your Life is itself a life-saving book.” -- Will Schwalbe, New York Times bestselling author of The End of Your Life Book Club and Books for Living",
    },
    {
      "name":"Whispers of Heartache ",
      "author":"Kavya",
      "bookImage":"book91.webp",
      "bookPrize":"$ 161.00",
      "orginalBookPrize":"$ 250.00",
      "publisher":" Writer's Pocket ",
      "relesedDate":"  15 January 2022 ",
      "bookStockDetails":"Available",
      "aboutbook":"A great poetry book for all those who want to experience the beautifully sad emotions that come along with a heartbreak. What letting go feels like, how broken a person can get, how it feels to fall in love with someone, and a lot more. Get this relatable poetry book for gift and the person will surely fall in love with the poems in it. Words are just whispers of the heartache we suffer from, we scream but our screams don't seem to reach others. So maybe, just maybe, if we whisper our holding, our letting go, our falling and our loving, some who listen to silence will hear what we are going through.",
      "aboutAuthor":"A great poetry book for all those who want to experience the beautifully sad emotions that come along with a heartbreak. What letting go feels like, how broken a person can get, how it feels to fall in love with someone, and a lot more. Get this relatable poetry book for gift and the person will surely fall in love with the poems in it.",
    },
    {
      "name":"Tirukkural: The Book of Desire ",
      "author":"Meena Kandasamy",
      "bookImage":"book173.jpg",
      "bookPrize":"$ 449.00",
      "orginalBookPrize":"$499.00",
      "publisher":" Penguin Hamish Hamilton ",
      "relesedDate":" 23 January 2023  ",
      "bookStockDetails":"Available",
      "aboutbook":"Written by the poet Thiruvalluvar, the Kamattu-p-pal is the third part of the Tirukkural - one of the most important texts in Tamil literature. The most intimate section of this great work - it is also, historically, the part that has been most heavily censored. Although hundreds of male translations of the text have been published, it has also only ever been translated by a woman once before. Tirukkural is award-winning writer Meena Kandasamy's luminous translation of the Kamattu-p-pal.Meena Kandasamy delves into this classic, and provides the first feminist interventionist translation into English-remaining true to the desire throbbing through the lifeblood of the text, while retaining the drama that pervades the quintessential Tamil world of exaggerated hurt, lover's quarrels and evenings lost to longing.With her trademark wit, lyricism and passionate insight, Meena weaves a magic spell: taking the reader on a journey through 250 kurals, organised under separate headings - 'The Pleasure of Sex', 'Renouncing Shame', 'The Delights of Sulking' - the result is a fresh, vital, and breath-taking translation that conveys powerful messages about female sensuality, agency, and desire. It is a revolution 2000 years in the making.",
      "aboutAuthor":"Tiruvalluvar was an ancient Tamil poet and philosopher best known for writing the Tirukkural, a collection of couplets on matters ranging from love to ethics.Meena Kandasamy is an anti-caste activist, poet, novelist and translator. She has written books of poems such as Touch (2006) and Ms. Militancy (2010), as well as three novels, The Gypsy Goddess (2014), When I Hit You (2017), and Exquisite Cadavers (2019). Her novels have been shortlisted for the Women's Prize for Fiction, the International Dylan Thomas Prize, the Jhalak Prize and the Hindu Lit Prize.She has been a fellow of the University of Iowa's International Writing Program, a Charles Wallace India Trust Fellow at the University of Kent and a fellow of the Berlin-based Junge Akademie. In 2022, she was elected as a Fellow of the Royal Society of Literature (FRSL), United Kingdom.",
    },
    {
      "name":"Few Days of Cute Cringe",
      "author":" Ishwariya Gopi ",
      "bookImage":"book174.jpg",
      "bookPrize":"$ 146.00",
      "orginalBookPrize":"$ 260.00",
      "publisher":" Writer's Pocket ",
      "relesedDate":"12 December 2022   ",
      "bookStockDetails":"Available",
      "aboutbook":"These days, we're too busy to stop and spend time with the ones we love. Often, we are working tirelessly to satisfy their comfort. Our robotic lives deserve a break too. Gestures of love can also be termed as cringe sometimes.If you think about it, what is love without romance? What is romance without moments of cute cringe? This poetry book is a collection of poetries based on stages of love-romance-cute cringe.Ishwariya was born and raised in Bangalore, graduated in Chennai and had been in Hyderabad for a while. Technically, adaptable anywhere! Someone who loves pen and paper language. Every time, she finds an opportunity, she escapes from her corporate life for an adventure. Vacations and poetries have been her favourite things in this world and beyond!",
      "aboutAuthor":"Ishwariya was born and raised in Bangalore, graduated in Chennai and had been in Hyderabad for a while. Technically, adaptable anywhere! Someone who loves pen and paper language. Every time, she finds an opportunity, she escapes from her corporate life for an adventure. Vacations and poetries have been her favourite things in this world and beyond!..Ishwariya Gopi is the author of Few Days of Cute Cringe,",
    },
    {
      "name":"Ruskin Bond's Book of Verse ",
      "author":"Ruskin Bond ",
      "bookImage":"book175.jpg",
      "bookPrize":"$ 202.00",
      "orginalBookPrize":"$ 250.00",
      "publisher":" Penguin Books Limited ",
      "relesedDate":"  18 July 2016 ",
      "bookStockDetails":"Available",
      "aboutbook":"Ruskin Bond’s Book of Verse brings together the poetry of one of India’s best-loved writers. This charming collector’s edition is a treasury of poems on love and nature, travel, humour and childhood and will be a lasting source of delight to readers.This leaf, so complete in itself,Is only part of a tree.And this tree, so complete in itself,Is only part of the mountain.And the mountain runs down to the sea.And the sea, so complete in itself,Rests like a raindrop..On the hand of God. ",
      "aboutAuthor":"Ruskin Bond is one of India’s best-loved writers, who has written over 500 short stories, essays and novellas and more than forty books for children. He won the Sahitya Akademi Award in 1992, the Padma Shri in 1999 and Padma Bhushan in 2014.",
    },
    {
      "name":" Eternal Memories",
      "author":"PS Punith Krishna ",
      "bookImage":"book176.jpg",
      "bookPrize":"$ 157.00",
      "orginalBookPrize":"$ 200.00",
      "publisher":" Writer's Pocket ",
      "relesedDate":" 25 December 2022  ",
      "bookStockDetails":"Available",
      "aboutbook":"What you’re holding are memories of a soul and body that survived this journey of poetry A collection of smiles, tears and blood, The story of a heart placed in hands that couldn’t keep it in one piece One that starts in love, ending with hope. Broken, but still alive. Forever carrying the pain-filled between the crevices formed in a heart Forever instilled in these eternal memories of ours.",
      "aboutAuthor":" PS Punith Krishna  The story of a heart placed in hands that couldn’t keep it in one piece One that starts in love, ending with hope. Broken, but still alive. ",
    },
    {
      "name":"Hues in Ink",
      "author":"Vaanee Tripathi",
      "bookImage":"book177.jpg",
      "bookPrize":"$ 249.00",
      "orginalBookPrize":"$ 310.00",
      "publisher":" Penguin media ",
      "relesedDate":"  9 August 2022 ",
      "bookStockDetails":"Available",
      "aboutbook":"Hues in Ink is a collection of 25 poems which traverse a plethora of themes. Just like the visual world has a multitude of colours to adorn, beautify and enhance our experiences, the emotional world has feelings, emotions, thoughts, opinions, and philosophies. This book brings to you the culmination of a tryst of these two worlds. It associates colours with words and words with more than what words can say.Hues in Ink is not just a book. It is a journey across the spectrum of emotions on the wheels of poetry. Is it one you're willing to take?",
      "aboutAuthor":"Discover more of the author’s books, see similar authors, read author blogs and more..the emotional world has feelings, emotions, thoughts, opinions, and philosophies. This book brings to you the culmination of a tryst of these two worlds. It associates colours with words and words with more than what words can say.",
    },
    {
      "name":"Too Young to Think Twice",
      "author":"Areeb Sami ",
      "bookImage":"book178.jpg",
      "bookPrize":"$ 125.00",
      "orginalBookPrize":"$ 148.00",
      "publisher":"  ",
      "relesedDate":"  11 August 2020 ",
      "bookStockDetails":"Available",
      "aboutbook":"What I read ignores most of what I see. So, I wanted to write for people who mostly see what I see. Through Too Young to Think Twice, I intend to rekindle our desires, to cherish our individuality and to eulogize our persevering young blood. Takes me back to the memories of fearless tigers we were as boys. Takes me back to the mysterious sense of faith and coming together as one in prayer. Takes me back into reimagining the countless times of self talk and the unforgettable journey of young and deep emotions. Moments of love, boyhood, family, belongingness, loss, truth, courage, struggle and growth into acceptance. The author in his witty, beautiful, and craftily worded poems, reveals heartfelt stories that would touch every young mind. There is surely something to love about a poem when it's written about you, this is a whole book of them. Great poems along side beautiful illustrations. Would highly recommend. I found my favourites in the 'He has a heart' but a lot of my favourites were also scattered in between the lines and poems in the first two parts. Beauty in words.     ",
      "aboutAuthor":" Areeb Sami The writer definately poured his heart out !! Eyes follow me was quite relatable ! I think it's a really great grab for youth beacause you guys can literally find relatable feelings. Renegade perfectly written ! I read the whole book in one go couldn't stop myself and I'm sure you guys are gonna love this .",
    },
    {
      "name":"Ninety-Seven Poems",
      "author":"Terribly Tiny Tales ",
      "bookImage":"book179.webp",
      "bookPrize":"$ 213.00",
      "orginalBookPrize":"$ 260.00",
      "publisher":" Penguin ",
      "relesedDate":"  13 July 2018 ",
      "bookStockDetails":"Available",
      "aboutbook":"This is a book of pictures.Of a park bench and a prescription. And a toothbrush in a mug. It's got half-lit cigarettes and broken geysers. And a cute apartment in Prague. There's a fortune cookie, some pigeons in cages and stars tumbling from the sky. There's the usual traffic, a digital wristwatch and a violin from Uncle James.We can go on, but you'd rather see for yourself.For we think this book has pictures.But some say it's full of poems.After their first bestseller, Terribly Tiny Tales and Penguin come together on the same page once again.",
      "aboutAuthor":"Cat GIFs, silly memes and WhatsApp forwards. The year 2013 saw attention spans dwindling, and stories struggled to stay in our feeds. So we hand-picked a bunch of stellar writers, shrunk stories to 140 characters and put them out for the world to read. And what started as a page on Facebook slowly became the Internet's most loved micro-fiction platform.Now reaching millions every week, Terribly Tiny Tales continues to explore newer formats, with writers and readers from around the globe. We believe the best stories aren't just the ones that move you while reading. They're the ones that stay.To read more stories and write your own, download the TTT app for Android and iOS at terriblytinytales.com/app.",
    },
    {
      "name":"Healing Comes In Waves",
      "author":"Twinkle Patel ",
      "bookImage":"book180.jpg",
      "bookPrize":"$ 248.00",
      "orginalBookPrize":"$ 321.00",
      "publisher":" Writer's Pocket ",
      "relesedDate":"  8 August 2022 ",
      "bookStockDetails":"Available",
      "aboutbook":"Healing Comes In Waves is a poetry collection for the mind and heart. If our feelings and emotions makes us feel anxious, overwhelmed, and demotivated- it also has the power to make us feel hope, joy and love. Getting re-direction when one is feeling lost is a part of healing and unlearning ones toxic trait is also a part of healing journey. This poetry book is a reminder that all our feelings and emotions are of the essence and, learning the tool of expression is a life-long process. The true essence of life is in the course of finding our unique tool of expression in art- it atomates the nurturing process of our mental health by forming a deeper level of undersatnding about self and life. Everyone you meet is healing from either psychological, emotional or mental wounds at a varied degree. Be kind. Words matter.",
      "aboutAuthor":"Healing comes in waves is a amazing book by author Twinkle patel . The storyline is amazing and the characters are well developed. Healing Comes In Waves will heal our heart and mind from various things and also it gives some hope to move on. The quotes in the beginning of every chapter related to each topic and a brief introduction that took place before entering into the chapters of poems are all will give an idea before jumping into the emotional pool filled with words of poems. But I am not sure how these topics are interrelated and what basis the author has selected the headers to give a complete feel of book. It doesn't look like a story related to each other instead it resembles like random pick and common things are discussed to get healed. Anyways with an easy language and precise manner, the author has crafted all the emotions nicely to heal the mind and it shows a ray of hope to nurture us. i recommend this book.",
    },
    {
      "name":"Best of Faiz",
      "author":"Kuldip Salil",
      "bookImage":"book181.jpg",
      "bookPrize":"$ 380.0",
      "orginalBookPrize":"$ 680.0",
      "publisher":"  Rajpal and Sons ",
      "relesedDate":"Dec 2015  ",
      "bookStockDetails":"Available",
      "aboutbook":"This Volume Is A Compilation Of Faiz'S Work. It Carries The Urdu Text With Parallel Roman Script, A New Introduction, Several New Poems -- And Substantive Revisions, Wherever Necessary.Faiz Ahmed Faiz is the most famous contemporary Urdu poet of the twentieth century who appeals both to the common man as well as the elite connoisseurs of poetry. Faiz's ghazals reflect a strong influence of the Persian style and diction, because of which he is often considered the inheritor of the tradition of Ghalib; and at the same time several of them are written in a simple conversational style dealing with the problems of the common man. Faiz was a committed poet who regarded poetry as a vehicle of serious thought rather than just a pleasurable pastime and often used it to champion the cause of socialistic humanism. Born in Sialkot in 1911, Faiz began his career as a lecturer in English but soon turned to journalism where he excelled, rising to the post of editor of The Pakistan Times. In 1951 the Pakistan government sentenced him to four years imprisonment on the charges of complicity in a failed coup attempt known as the Rawalpindi Conspiracy case. While in jail he wrote two of his greatest works, Dasta-e-Saba and Zindan-Nama. During the regime of Zia-ul-Haq he was forced into exile to Beirut. He returned to Pakistan in 1982 and two years later he passed away. This book offers a selection of the best of Faiz's ghazals and nazms along with their English translations as well as transliterations so you can enjoy the beauty and richness of Urdu language as you read the English transliteration while the translation helps you understand the meaning with all its subtle nuances. ",
      "aboutAuthor":"Faiz Ahmad Faiz MBE NI was a Pakistani poet, and author of Urdu and Punjabi literature. Faiz was one of the most celebrated Pakistani Urdu writers of his time.This Volume Is A Compilation Of Faiz'S Work ",
    },
    {
      "name":"The moon",
      "author":"K Tolnoe",
      "bookImage":"book182.jpg",
      "bookPrize":"$ 310.00",
      "orginalBookPrize":"$ 463.00",
      "publisher":"  Tolno ",
      "relesedDate":"  01 Jan 2020  ",
      "bookStockDetails":"Available",
      "aboutbook":"the moon is a poetry collection that illuminates the phases of the human experience in all its lightness and darkness. It is the first book in the nothern collection with 4 books coming out in 2020.Written and illustrated by instagram poet and artist, Kamilla Tolnø, the moon guides readers through a journey that is both familiar and unknown. The poems tell stories of loss, love, grief, struggle, transformation, and most of all, hope.Just as the moon orbits earth, the moon poetry book revolves around its reader, their resilience, their healing, and their growth. the moon will always be there when you need her most. All you have to do is turn the page.",
      "aboutAuthor":"K Tolnoe was a poet Kamilla Tolnø (k. tolnoe) is a danish writer and poet. She is known for her way to express complex emotions with simple words and minimalistic drawings.",
    },
    {
      "name":"Greatest Poetry Ever Written",
      "author":"Grapevine",
      "bookImage":"book183.jpg",
      "bookPrize":"$145.00 ",
      "orginalBookPrize":"$ 310.00",
      "publisher":"  Grapevine India ",
      "relesedDate":"15 May 2018   ",
      "bookStockDetails":"Available",
      "aboutbook":"Poetry gives meaning to our lives. For many of us, it's a way of understanding the world around us. This book is an attempt to bring together the greatest words ever written by some men and women to have walked this planet.Poetry gives meaning to our lives. For many of us, it's a way of understanding the world around us. This book is an attempt to bring together the greatest words ever written by some men and women to have walked this planet.",
      "aboutAuthor":"Grapevine This collection is very scattered to say the least. Apart from covering prominent writers of the Romantic era and some others of Pre-modernist era with relative efficacy, the criteria of inclusion feels very obscure and poorly executed.",

    },
    {
      "name":"To the man I loved too much",
      "author":"Gabrielle G ",
      "bookImage":"book184.jpg",
      "bookPrize":"$ 871.00",
      "orginalBookPrize":"$ 980.00",
      "publisher":" Gabrielle Guillon ",
      "relesedDate":"14 Feb 2021   ",
      "bookStockDetails":"Available",
      "aboutbook":"In her first collection of poems, Gabrielle G. depicts different love stories from the initial spark to the last heartbreak and writes in verses the heartache we've all been through.Every night I meet you in my dreams, Sinfully in love and surreally yours. Impossible by Gabrielle G. In this collection of poems, Gabrielle G. depicts different love stories from the initial spark to the last heartbreak and writes in verses the heartache we've all been through.In her first collection of poems, Gabrielle G. depicts different love stories from the initial spark to the last heartbreak and writes in verses the heartache we've all been through. A poetry book to make your heart smile and weep at the same time. ",
      "aboutAuthor":"Gabrielle G.'s writing is driven by pure emotion and will leave you out of breath, yearning for more, while at the same time wiping away tears.She will do anything for a hot cup of tea, still celebrates her half-birthdays, and feels everyone has an inner temptuous voice.Born in France and having lived in Switzerland, Gabrielle currently resides in Montreal with her family, and an extremely moody cat."
    },
    {
      "name":"Home Body",
      "author":"Rupi Kaur",
      "bookImage":"book185.jpg",
      "bookPrize":"$345.00 ",
      "orginalBookPrize":"$ 479.00",
      "publisher":" Simon & Schuster ",
      "relesedDate":" 17 November 2020  ",
      "bookStockDetails":"Available",
      "aboutbook":"Rupi Kaur constantly embraces growth, and in home body, she walks readers through a reflective and intimate journey visiting the past, the present, and the potential of the self. home body is a collection of raw, honest conversations with oneself – reminding readers to fill up on love, acceptance, community, family, and embrace change. Illustrated by the author, themes of nature and nurture, light and dark, rest here. ",
      "aboutAuthor":"A breakout literary phenomenon and #1 New York Times Bestselling Author, Rupi Kaur wrote, illustrated, and self-published her first poetry collection, 'milk and honey' in 2014. Next came its artistic siblings 'the sun and her flowers' and ‘home body’, both debuting at #1 on bestseller lists across the world. These collections have sold more than 11 million copies and have been translated into over 43 languages. Most recently in 2022- she released her 4th book ‘Healing Through Words’ which is a journey of guided writing exercises to help the reader explore their creativity.As she has done from the very beginning, Rupi self-produced ‘Rupi Kaur Live’, the first poetry special of its kind, which debuted on Amazon Prime Video in 2021.Rupi Kaur graces stages across the globe on sold-out world tours. These shows are a poetic theatrical experience interlaced with her own touch of stand-up. Her work touches on love, loss, trauma, healing, femininity, and migration. She feels most at home when creating art, performing her poetry onstage, and spending time with family and friends. "
    },
    {
      "name":"When He Leaves You ",
      "author":"Michaela Angemeer",
      "bookImage":"book186.jpg",
      "bookPrize":"$ 1,028.0",
      "orginalBookPrize":"$ 1,470.0",
      "publisher":" Michaela Angemeer ",
      "relesedDate":"18 Mar 2018   ",
      "bookStockDetails":"Available",
      "aboutbook":"When He Leaves You is a collection of short poetry and prose, biopsied with tears and red wine. It dives into themes of love, loss, a connection to water, and never forgetting what it means to be alive. Separated into six sections: Childhood, Him, Everything Is You, Over, Repairing, and Perspective, it takes you on a journey to find a new outlook.When He Leaves You is a collection of short poetry and prose, biopsied with tears and red wine. It dives into themes of love, loss, a connection to water, and never forgetting what it means to be alive. Separated into six sections: Childhood, Him, Everything Is You, Over, Repairing, and Perspective, it takes you on a journey to find a new outlook.",
      "aboutAuthor":"Michaela Angemeer is a Canadian poet who grew up in Brampton, Ontario. She went to the University of Waterloo to pursue her love of introspection and words, receiving her Bachelor of Arts in Psychology and English. Michaela Angemeer is a Spanish Canadian poet who grew up in Brampton, Ontario. She went to the University of Waterloo to pursue her love of introspection and words, receiving her Bachelor of Arts in Psychology and English. As someone who learned to read before she could walk, she's always imagined herself writing a book. When He Leaves You is her debut poetry collection, an honest reflection of her life. Michaela now lives in a one-bedroom apartment in Waterloo, Ontario with her books, too many throw pillows, and empty bottles of red wine. Find her on Instagram: @michaelapoetry"
    }
  ]

}
